In [1]:
pip install -r requirements.txt

    100% |████████████████████████████████| 92.5MB 13kB/s 
    100% |████████████████████████████████| 17.3MB 100kB/s 
    100% |████████████████████████████████| 10.1MB 162kB/s 
    100% |████████████████████████████████| 13.0MB 98kB/s 
    100% |████████████████████████████████| 317kB 2.5MB/s 
    100% |████████████████████████████████| 368kB 2.1MB/s 
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
    100% |████████████████████████████████| 1.3MB 1.1MB/s 
    100% |████████████████████████████████| 3.2MB 495kB/s 
    100% |████████████████████████████████| 20.9MB 53kB/s 
    100% |████████████████████████████████| 133kB 2.7MB/s 
    100% |████████████████████████████████| 51kB 6.9MB/s 
    100% |████████████████████████████████| 51kB 3.9MB/s 
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-

In [2]:
# Artificial Neural Network

# Installing Theano
# pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
# pip install tensorflow

# Installing Keras
# pip install --upgrade keras

# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [3]:
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]
[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [4]:
np.shape(X_train)

(8000, 12)

In [6]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 12))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'tanh'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
8000/8000 [==============================] - 1s 87us/step - loss: 0.5143 - acc: 0.8009
Epoch 2/100
8000/8000 [==============================] - 1s 67us/step - loss: 0.4186 - acc: 0.8070
Epoch 3/100
8000/8000 [==============================] - 1s 65us/step - loss: 0.3991 - acc: 0.8157
Epoch 4/100
8000/8000 [==============================] - 1s 67us/step - loss: 0.3861 - acc: 0.8262
Epoch 5/100
8000/8000 [==============================] - 1s 66us/step - loss: 0.3762 - acc: 0.8370
Epoch 6/100
8000/8000 [==============================] - 1s 66us/step - loss: 0.3708 - acc: 0.8414
Epoch 7/100
8000/8000 [==============================] - 1s 66us/step - loss: 0.3670 - acc: 0.8441
Epoch 8/100
8000/8000 [==============================] - 1s 65us/step - loss: 0.3652 - acc: 0.8424
Epoch 9/100
8000/8000 [==============================] - 1s 65us/step - loss: 0.3636 - acc: 0.8426
Epoch 10/100
8000/8000 [==============================] - 1s 

In [7]:
# Part 3 - Making predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [8]:
print(cm)

[[1518   77]
 [ 198  207]]
