In [1]:
pip install -r requirements.txt

    100% |████████████████████████████████| 92.5MB 19kB/s 
    100% |████████████████████████████████| 17.3MB 99kB/s 
    100% |████████████████████████████████| 10.1MB 167kB/s 
    100% |████████████████████████████████| 13.0MB 130kB/s 
    100% |████████████████████████████████| 317kB 1.1MB/s 
    100% |████████████████████████████████| 133kB 1.7MB/s 
    100% |████████████████████████████████| 51kB 2.0MB/s 
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
    100% |████████████████████████████████| 3.2MB 437kB/s 
    100% |████████████████████████████████| 51kB 2.6MB/s 
    100% |████████████████████████████████| 1.3MB 767kB/s 
    100% |████████████████████████████████| 20.9MB 78kB/s 
    100% |████████████████████████████████| 368kB 1.2MB/s 
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-

In [2]:

# Artificial Neural Network

# Installing Theano
# pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
# pip install tensorflow

# Installing Keras
# pip install --upgrade keras

# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [9]:

# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [12]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 12))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'tanh'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 30)

Instructions for updating:
Use tf.cast instead.
Epoch 1/30
8000/8000 [==============================] - 2s 199us/step - loss: 0.4794 - acc: 0.7960
Epoch 2/30
8000/8000 [==============================] - 0s 58us/step - loss: 0.4229 - acc: 0.7960
Epoch 3/30
8000/8000 [==============================] - 0s 56us/step - loss: 0.4163 - acc: 0.7947
Epoch 4/30
8000/8000 [==============================] - 0s 57us/step - loss: 0.4084 - acc: 0.8041
Epoch 5/30
8000/8000 [==============================] - 0s 60us/step - loss: 0.3979 - acc: 0.8114
Epoch 6/30
8000/8000 [==============================] - 0s 62us/step - loss: 0.3957 - acc: 0.8214
Epoch 7/30
8000/8000 [==============================] - 0s 56us/step - loss: 0.4027 - acc: 0.8351
Epoch 8/30
8000/8000 [==============================] - 0s 56us/step - loss: 0.4017 - acc: 0.8387
Epoch 9/30
8000/8000 [==============================] - 0s 55us/step - loss: 0.3844 - acc: 0.8364
Epoch 10/30
8000/8000 [==============================] - 0s 56us/step

In [13]:
# Part 3 - Making predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [14]:
print(cm)

[[1520   75]
 [ 211  194]]
