# **REDES NEURAIS ARTIFICIAIS**

Aula 3 de Deep Learning da Engenharia de Software da UnB

In [1]:
# Installing Theano
! pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
! pip install --upgrade tensorflow

# Installing Keras
! pip install --upgrade keras

# Install other packages
! pip install --upgrade pip pandas numpy matplotlib sklearn

Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal.main import main
ImportError: No module named main
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal.main import main
ImportError: No module named main
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal.main import main
ImportError: No module named main
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal.main import main
ImportError: No module named main


# **Parte 1 - Preprocessamento dos Dados**

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


In [4]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]
print("X >>\n",X)

X >>
 [[0.0000000e+00 0.0000000e+00 6.1900000e+02 ... 1.0000000e+00
  1.0000000e+00 1.0134888e+05]
 [0.0000000e+00 1.0000000e+00 6.0800000e+02 ... 0.0000000e+00
  1.0000000e+00 1.1254258e+05]
 [0.0000000e+00 0.0000000e+00 5.0200000e+02 ... 1.0000000e+00
  0.0000000e+00 1.1393157e+05]
 ...
 [0.0000000e+00 0.0000000e+00 7.0900000e+02 ... 0.0000000e+00
  1.0000000e+00 4.2085580e+04]
 [1.0000000e+00 0.0000000e+00 7.7200000e+02 ... 1.0000000e+00
  0.0000000e+00 9.2888520e+04]
 [0.0000000e+00 0.0000000e+00 7.9200000e+02 ... 1.0000000e+00
  0.0000000e+00 3.8190780e+04]]


/home/luciana/.local/lib/python3.5/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/luciana/.local/lib/python3.5/site-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


# **Dividindo o dataset em conjunto de treinamento e conjunto de teste**

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# **Feature Scaling**

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

---
# **Parte 2 -Vamos construir uma ANN!**

## **Importando o Keras**


In [7]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [0]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# **Ajustando a ANN ao conjunto de treinamento**

In [9]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 1s 79us/step - loss: 0.4907 - accuracy: 0.7959
Epoch 2/100
8000/8000 [==============================] - 1s 64us/step - loss: 0.4277 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 65us/step - loss: 0.4217 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 65us/step - loss: 0.4172 - accuracy: 0.8186
Epoch 5/100
8000/8000 [==============================] - 1s 66us/step - loss: 0.4153 - accuracy: 0.8294
Epoch 6/100
8000/8000 [==============================] - 1s 64us/step - loss: 0.4134 - accuracy: 0.8304
Epoch 7/100
8000/8000 [==============================] - 1s 63us/step - loss: 0.4119 - accuracy: 0.8336
Epoch 8/100
8000/8000 [==============================] - 1s 68us/step - loss: 0.4105 - accuracy: 0.8338
Epoch 9/100
8000/8000 [==============================] - 0s 60us/step - loss: 0.4094 - accuracy: 0.8349
Epoch 10/100
8000/8000 [==============================] - 0s 57u

# **Parte 3 - Fazendo predições e avaliando o modelo**

## **Prevendo os resultados com o conjunto de testes**

In [0]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# **Criando uma Confusion Matrix**

In [11]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1484  111]
 [ 181  224]]


# **Initiate activation function experimentation**

# **Initialising the 2nd ANN**

In [12]:
del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 1s 126us/step - loss: 0.5225 - accuracy: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 114us/step - loss: 0.4797 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 105us/step - loss: 0.4657 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 116us/step - loss: 0.4525 - accuracy: 0.7960
Epoch 5/100
8000/8000 [==============================] - 1s 128us/step - loss: 0.4423 - accuracy: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.4361 - accuracy: 0.7960
Epoch 7/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.4323 - accuracy: 0.7960
Epoch 8/100
8000/8000 [==============================] - 1s 100us/step - loss: 0.4307 - accuracy: 0.7960
Epoch 9/100
8000/8000 [==============================] - 1s 104us/step - loss: 0.4297 - accuracy: 0.7960
Epoch 10/100
8000/8000 [==============================]

In [0]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# **Making the Confusion Matrix**


In [14]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1542   53]
 [ 265  140]]


# **Initialising the 3rd ANN**


In [15]:
del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'relu'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 1s 82us/step - loss: 0.5415 - accuracy: 0.7986
Epoch 2/100
8000/8000 [==============================] - 1s 75us/step - loss: 0.4131 - accuracy: 0.8117
Epoch 3/100
8000/8000 [==============================] - 1s 74us/step - loss: 0.4106 - accuracy: 0.8079
Epoch 4/100
8000/8000 [==============================] - 1s 75us/step - loss: 0.3993 - accuracy: 0.8170
Epoch 5/100
8000/8000 [==============================] - 1s 74us/step - loss: 0.3969 - accuracy: 0.8207
Epoch 6/100
8000/8000 [==============================] - 1s 74us/step - loss: 0.3910 - accuracy: 0.8244
Epoch 7/100
8000/8000 [==============================] - 1s 74us/step - loss: 0.3837 - accuracy: 0.8307
Epoch 8/100
8000/8000 [==============================] - 1s 74us/step - loss: 0.3769 - accuracy: 0.8378
Epoch 9/100
8000/8000 [==============================] - 1s 74us/step - loss: 0.3827 - accuracy: 0.8438
Epoch 10/100
8000/8000 [==============================] - 1s 75u

In [0]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# **Making the Confusion Matrix**

In [17]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1418  177]
 [ 147  258]]


In [18]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()
print("accuracies:%s\nmean:%s\nvariance:%s".format(accuracies, mean, variance))

accuracies:%s
mean:%s
variance:%s


In [0]:
from keras.layers import Dropout

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()

In [0]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense

def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier)

In [21]:
parameters = {'batch_size': [10, 24],
              'epochs': [10, 20],
              'optimizer': ['adam', 'rmsprop']}

grid_search = GridSearchCV(estimator = classifier,
                           scoring = 'accuracy',
                           param_grid = parameters,
                           cv = 10)

grid_search = grid_search.fit(X_train, y_train)

best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

Epoch 1/10
7200/7200 [==============================] - 1s 108us/step - loss: 0.5847 - accuracy: 0.7989
Epoch 2/10
7200/7200 [==============================] - 1s 88us/step - loss: 0.4388 - accuracy: 0.8069
Epoch 3/10
7200/7200 [==============================] - 1s 89us/step - loss: 0.4273 - accuracy: 0.8143
Epoch 4/10
7200/7200 [==============================] - 1s 88us/step - loss: 0.4198 - accuracy: 0.8142
Epoch 5/10
7200/7200 [==============================] - 1s 88us/step - loss: 0.4163 - accuracy: 0.8164
Epoch 6/10
7200/7200 [==============================] - 1s 93us/step - loss: 0.4025 - accuracy: 0.8229
Epoch 7/10
7200/7200 [==============================] - 1s 89us/step - loss: 0.4039 - accuracy: 0.8228
Epoch 8/10
7200/7200 [==============================] - 1s 87us/step - loss: 0.3950 - accuracy: 0.8317
Epoch 9/10
7200/7200 [==============================] - 1s 89us/step - loss: 0.3931 - accuracy: 0.8286
Epoch 10/10
7200/7200 [==============================] - 1s 88us/step - 