# **REDES NEURAIS ARTIFICIAIS**

Aula 3 de Deep Learning da Engenharia de Software da UnB

In [1]:
# Installing Theano
! pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
! pip install --upgrade tensorflow

# Installing Keras
! pip install --upgrade keras

# Install other packages
! pip install --upgrade pip pandas numpy matplotlib sklearn

Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal.main import main
ImportError: No module named main
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal.main import main
ImportError: No module named main
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal.main import main
ImportError: No module named main
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal.main import main
ImportError: No module named main


# **Parte 1 - Preprocessamento dos Dados**

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


In [4]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]
print("X >>\n",X)

X >>
 [[0.0000000e+00 0.0000000e+00 6.1900000e+02 ... 1.0000000e+00
  1.0000000e+00 1.0134888e+05]
 [0.0000000e+00 1.0000000e+00 6.0800000e+02 ... 0.0000000e+00
  1.0000000e+00 1.1254258e+05]
 [0.0000000e+00 0.0000000e+00 5.0200000e+02 ... 1.0000000e+00
  0.0000000e+00 1.1393157e+05]
 ...
 [0.0000000e+00 0.0000000e+00 7.0900000e+02 ... 0.0000000e+00
  1.0000000e+00 4.2085580e+04]
 [1.0000000e+00 0.0000000e+00 7.7200000e+02 ... 1.0000000e+00
  0.0000000e+00 9.2888520e+04]
 [0.0000000e+00 0.0000000e+00 7.9200000e+02 ... 1.0000000e+00
  0.0000000e+00 3.8190780e+04]]


/home/luciana/.local/lib/python3.5/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/luciana/.local/lib/python3.5/site-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


# **Dividindo o dataset em conjunto de treinamento e conjunto de teste**

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# **Feature Scaling**

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

---
# **Parte 2 -Vamos construir uma ANN!**

## **Importando o Keras**


In [7]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [0]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# **Ajustando a ANN ao conjunto de treinamento**

In [9]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 2s 223us/step - loss: 0.4914 - accuracy: 0.7958
Epoch 2/100
8000/8000 [==============================] - 1s 64us/step - loss: 0.4197 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 0s 62us/step - loss: 0.4100 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 63us/step - loss: 0.4000 - accuracy: 0.8204
Epoch 5/100
8000/8000 [==============================] - 1s 63us/step - loss: 0.3924 - accuracy: 0.8279
Epoch 6/100
8000/8000 [==============================] - 1s 66us/step - loss: 0.3856 - accuracy: 0.8289
Epoch 7/100
8000/8000 [==============================] - 1s 65us/step - loss: 0.3803 - accuracy: 0.8338
Epoch 8/100
8000/8000 [==============================] - 1s 64us/step - loss: 0.3763 - accuracy: 0.8420
Epoch 9/100
8000/8000 [==============================] - 0s 62us/step - loss: 0.3723 - accuracy: 0.8478
Epoch 10/100
8000/8000 [==============================] - 1s 63

# **Parte 3 - Fazendo predições e avaliando o modelo**

## **Prevendo os resultados com o conjunto de testes**

In [0]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# **Criando uma Confusion Matrix**

In [11]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1506   89]
 [ 194  211]]


# **Initiate activation function experimentation**

# **Initialising the 2nd ANN**

In [12]:
del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'tanh'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 1s 97us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 85us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 93us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 93us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 5/100
8000/8000 [==============================] - 1s 106us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 139us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 7/100
8000/8000 [==============================] - 1s 128us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 8/100
8000/8000 [==============================] - 1s 137us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 9/100
8000/8000 [==============================] - 1s 126us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 10/100
8000/8000 [==============================] - 1

In [0]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# **Making the Confusion Matrix**


In [14]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1595    0]
 [ 405    0]]


# **Initialising the 3rd ANN**


In [15]:
del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 1s 86us/step - loss: 0.5049 - accuracy: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 78us/step - loss: 0.4455 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 77us/step - loss: 0.4329 - accuracy: 0.7956
Epoch 4/100
8000/8000 [==============================] - 1s 76us/step - loss: 0.4290 - accuracy: 0.8010
Epoch 5/100
8000/8000 [==============================] - 1s 78us/step - loss: 0.4281 - accuracy: 0.8024
Epoch 6/100
8000/8000 [==============================] - 1s 77us/step - loss: 0.4276 - accuracy: 0.8029
Epoch 7/100
8000/8000 [==============================] - 1s 76us/step - loss: 0.4273 - accuracy: 0.8044
Epoch 8/100
8000/8000 [==============================] - 1s 76us/step - loss: 0.4273 - accuracy: 0.8046
Epoch 9/100
8000/8000 [==============================] - 1s 76us/step - loss: 0.4272 - accuracy: 0.8039
Epoch 10/100
8000/8000 [==============================] - 1s 76u

In [0]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# **Making the Confusion Matrix**

In [23]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1539   56]
 [ 254  151]]


In [18]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()
print("accuracies:%s\nmean:%s\nvariance:%s".format(accuracies, mean, variance))

accuracies:%s
mean:%s
variance:%s


In [0]:
from keras.layers import Dropout

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()

In [0]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense

def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier)

In [22]:
parameters = {'batch_size': [10, 24],
              'epochs': [10, 20],
              'optimizer': ['adam', 'rmsprop']}

grid_search = GridSearchCV(estimator = classifier,
                           scoring = 'accuracy',
                           param_grid = parameters,
                           cv = 10)

grid_search = grid_search.fit(X_train, y_train)

best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

Epoch 1/10
7200/7200 [==============================] - 1s 114us/step - loss: 0.5090 - accuracy: 0.7967
Epoch 2/10
7200/7200 [==============================] - 1s 101us/step - loss: 0.4324 - accuracy: 0.8143
Epoch 3/10
7200/7200 [==============================] - 1s 117us/step - loss: 0.4228 - accuracy: 0.8219
Epoch 4/10
7200/7200 [==============================] - 1s 102us/step - loss: 0.4209 - accuracy: 0.8214
Epoch 5/10
7200/7200 [==============================] - 1s 104us/step - loss: 0.4184 - accuracy: 0.8217
Epoch 6/10
7200/7200 [==============================] - 1s 103us/step - loss: 0.4074 - accuracy: 0.8244
Epoch 7/10
7200/7200 [==============================] - 1s 107us/step - loss: 0.4089 - accuracy: 0.8201
Epoch 8/10
7200/7200 [==============================] - 1s 110us/step - loss: 0.4047 - accuracy: 0.8200
Epoch 9/10
7200/7200 [==============================] - 1s 115us/step - loss: 0.4049 - accuracy: 0.8232
Epoch 10/10
7200/7200 [==============================] - 1s 106u