# REDES NEURAIS ARTIFICIAIS

* Estudante: Welison Lucas Almeida Regis
* Matrícula: 17/0024121

[Aula 3 de Deep Learning](http://bit.ly/dn-unb03) da Engenharia de Software da UnB

In [11]:
# Installing Theano
! pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
! pip install --upgrade tensorflow

# Installing Keras
! pip install --upgrade keras

# Install other packages
! pip install --upgrade pip pandas numpy matplotlib sklearn

  Cloning git://github.com/Theano/Theano.git to /tmp/pip-req-build-biztoh5u
  Created wheel for Theano: filename=Theano-1.0.5+1.geb6a4125c-py3-none-any.whl size=2668280 sha256=710135698845761fb982ea49c2933f8dd3e1209f807b6dcade31746441717c88
  Stored in directory: /tmp/pip-ephem-wheel-cache-4c2bzbsk/wheels/8b/00/4b/8447c44e506676c90f88cce84840acfef30bace41499422025
Successfully built Theano
  Attempting uninstall: Theano
    Found existing installation: Theano 1.0.5+1.geb6a4125c
    Uninstalling Theano-1.0.5+1.geb6a4125c:
      Successfully uninstalled Theano-1.0.5+1.geb6a4125c
Requirement already up-to-date: tensorflow in /home/welison/.local/lib/python3.8/site-packages (2.3.0)
  Using cached numpy-1.18.5-cp38-cp38-manylinux1_x86_64.whl (20.6 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.2
    Uninstalling numpy-1.19.2:
      Successfully uninstalled numpy-1.19.2
Requirement already up-to-date: keras in /home/welison/.local/lib/python3.8/site-packages (2

  Attempting uninstall: numpy
    Found existing installation: numpy 1.18.5
    Uninstalling numpy-1.18.5:
      Successfully uninstalled numpy-1.18.5
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

tensorflow 2.3.0 requires numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.2 which is incompatible.


# Parte 1 - Preprocessamento dos Dados

### Importar as libs

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Importar o dataset

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


### Transformando os dados categóricos

* Observação:
    * Necessário mudar a implementação da função "OneHotEncoder", visto que sua implementação sofreu modificações em versões recentes. Detalhes no [link](https://stackoverflow.com/questions/59476165/typeerror-init-got-an-unexpected-keyword-argument-categorical-features).


In [3]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])

labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
columnTransformer = ColumnTransformer([("Country", OneHotEncoder(), [1])], remainder="passthrough")
X = columnTransformer.fit_transform(X)

X = X[:, 1:]
print("X >>\n",X)

X >>
 [[0.0 0.0 619 ... 1 1 101348.88]
 [0.0 1.0 608 ... 0 1 112542.58]
 [0.0 0.0 502 ... 1 0 113931.57]
 ...
 [0.0 0.0 709 ... 0 1 42085.58]
 [1.0 0.0 772 ... 1 0 92888.52]
 [0.0 0.0 792 ... 1 0 38190.78]]


# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

---
# Parte 2 -Vamos construir uma ANN!

## Importando o Keras


In [6]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [7]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Ajustando a ANN ao conjunto de treinamento

In [8]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 0s 511us/step - loss: 0.6112 - accuracy: 0.7971
Epoch 2/100
800/800 [==============================] - 0s 508us/step - loss: 0.4841 - accuracy: 0.84200s - loss: 0.4843 - accuracy: 0.84
Epoch 3/100
800/800 [==============================] - 0s 508us/step - loss: 0.4176 - accuracy: 0.8524
Epoch 4/100
800/800 [==============================] - 0s 505us/step - loss: 0.3887 - accuracy: 0.8524
Epoch 5/100
800/800 [==============================] - 0s 508us/step - loss: 0.3730 - accuracy: 0.8546
Epoch 6/100
800/800 [==============================] - 0s 501us/step - loss: 0.3643 - accuracy: 0.8549
Epoch 7/100
800/800 [==============================] - 0s 507us/step - loss: 0.3595 - accuracy: 0.8575
Epoch 8/100
800/800 [==============================] - 0s 507us/step - loss: 0.3559 - accuracy: 0.85660s - loss: 0.3595 - accuracy
Epoch 9/100
800/800 [==============================] - 0s 530us/step - loss: 0.3533 - accuracy: 0.8594
Epoch 10/10

800/800 [==============================] - 0s 552us/step - loss: 0.3327 - accuracy: 0.8645
Epoch 79/100
800/800 [==============================] - 0s 550us/step - loss: 0.3326 - accuracy: 0.8634
Epoch 80/100
800/800 [==============================] - 0s 551us/step - loss: 0.3323 - accuracy: 0.8627
Epoch 81/100
800/800 [==============================] - 0s 557us/step - loss: 0.3335 - accuracy: 0.8636
Epoch 82/100
800/800 [==============================] - 0s 558us/step - loss: 0.3327 - accuracy: 0.8626
Epoch 83/100
800/800 [==============================] - 0s 557us/step - loss: 0.3326 - accuracy: 0.8624
Epoch 84/100
800/800 [==============================] - 0s 554us/step - loss: 0.3323 - accuracy: 0.8649
Epoch 85/100
800/800 [==============================] - 0s 557us/step - loss: 0.3321 - accuracy: 0.8636
Epoch 86/100
800/800 [==============================] - 0s 473us/step - loss: 0.3325 - accuracy: 0.8635
Epoch 87/100
800/800 [==============================] - 0s 459us/step - loss:

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [9]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Criando uma Confusion Matrix

In [10]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1516   79]
 [ 200  205]]


# Initiate activation function experimentation

* Funções de ativação: softsign, relu, sigmoid.
* Acurácia em torno de 86%.

# Initialising the 2nd ANN

In [11]:
del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'softsign', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 0s 490us/step - loss: 0.4851 - accuracy: 0.7956
Epoch 2/100
800/800 [==============================] - 0s 499us/step - loss: 0.4281 - accuracy: 0.7955
Epoch 3/100
800/800 [==============================] - 0s 502us/step - loss: 0.4214 - accuracy: 0.8059
Epoch 4/100
800/800 [==============================] - 0s 615us/step - loss: 0.4098 - accuracy: 0.8141
Epoch 5/100
800/800 [==============================] - 0s 591us/step - loss: 0.3977 - accuracy: 0.8123
Epoch 6/100
800/800 [==============================] - 1s 703us/step - loss: 0.3909 - accuracy: 0.8164
Epoch 7/100
800/800 [==============================] - 1s 699us/step - loss: 0.3868 - accuracy: 0.8196
Epoch 8/100
800/800 [==============================] - 0s 599us/step - loss: 0.3840 - accuracy: 0.8207
Epoch 9/100
800/800 [==============================] - 1s 668us/step - loss: 0.3798 - accuracy: 0.8210
Epoch 10/100
800/800 [==============================] - 0s 612us/step - l

800/800 [==============================] - 0s 556us/step - loss: 0.3365 - accuracy: 0.8605
Epoch 80/100
800/800 [==============================] - 0s 557us/step - loss: 0.3360 - accuracy: 0.8616
Epoch 81/100
800/800 [==============================] - 0s 568us/step - loss: 0.3360 - accuracy: 0.8634
Epoch 82/100
800/800 [==============================] - 0s 567us/step - loss: 0.3360 - accuracy: 0.8622
Epoch 83/100
800/800 [==============================] - 0s 561us/step - loss: 0.3361 - accuracy: 0.8630
Epoch 84/100
800/800 [==============================] - 0s 565us/step - loss: 0.3360 - accuracy: 0.8612
Epoch 85/100
800/800 [==============================] - 0s 564us/step - loss: 0.3361 - accuracy: 0.8622
Epoch 86/100
800/800 [==============================] - 0s 560us/step - loss: 0.3361 - accuracy: 0.8624
Epoch 87/100
800/800 [==============================] - 0s 564us/step - loss: 0.3359 - accuracy: 0.8619
Epoch 88/100
800/800 [==============================] - 0s 560us/step - loss:

In [12]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix

In [13]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1502   93]
 [ 192  213]]


# Initialising the 3rd ANN

In [14]:
del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 0s 496us/step - loss: 0.5263 - accuracy: 0.7933
Epoch 2/100
800/800 [==============================] - 0s 500us/step - loss: 0.4498 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 0s 526us/step - loss: 0.4372 - accuracy: 0.7960
Epoch 4/100
800/800 [==============================] - 0s 580us/step - loss: 0.4312 - accuracy: 0.7960
Epoch 5/100
800/800 [==============================] - 1s 687us/step - loss: 0.4288 - accuracy: 0.7981
Epoch 6/100
800/800 [==============================] - 1s 656us/step - loss: 0.4281 - accuracy: 0.7994
Epoch 7/100
800/800 [==============================] - 0s 542us/step - loss: 0.4276 - accuracy: 0.7994
Epoch 8/100
800/800 [==============================] - 0s 521us/step - loss: 0.4274 - accuracy: 0.8025
Epoch 9/100
800/800 [==============================] - 0s 514us/step - loss: 0.4275 - accuracy: 0.8033
Epoch 10/100
800/800 [==============================] - 0s 532us/step - l

800/800 [==============================] - 0s 530us/step - loss: 0.3998 - accuracy: 0.8342
Epoch 80/100
800/800 [==============================] - 0s 505us/step - loss: 0.3995 - accuracy: 0.8345
Epoch 81/100
800/800 [==============================] - 0s 526us/step - loss: 0.3995 - accuracy: 0.8350
Epoch 82/100
800/800 [==============================] - 1s 631us/step - loss: 0.3995 - accuracy: 0.8353
Epoch 83/100
800/800 [==============================] - 0s 609us/step - loss: 0.3992 - accuracy: 0.8354
Epoch 84/100
800/800 [==============================] - 1s 718us/step - loss: 0.3988 - accuracy: 0.8347
Epoch 85/100
800/800 [==============================] - 1s 692us/step - loss: 0.3990 - accuracy: 0.8353
Epoch 86/100
800/800 [==============================] - 0s 563us/step - loss: 0.3988 - accuracy: 0.8355
Epoch 87/100
800/800 [==============================] - 0s 506us/step - loss: 0.3987 - accuracy: 0.8359
Epoch 88/100
800/800 [==============================] - 1s 653us/step - loss:

In [15]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix

In [16]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1549   46]
 [ 262  143]]


---
# Parte 4 - Evaluating, Improving and Tuning the ANN

## Evaluating the ANN

In [21]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'softsign', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()
print("accuracies:{}\nmean:{}\nvariance:{}".format(accuracies, mean, variance))

accuracies:[0.84875    0.815      0.88       0.84249997 0.84500003 0.85124999
 0.85000002 0.815      0.84125    0.86124998]
mean:0.8449999988079071
variance:0.018405161363963043


# Improving the ANN
# Dropout Regularization to reduce overfitting if needed

In [18]:
from keras.layers import Dropout

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()

# Tuning the ANN

In [19]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense

def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier)

In [20]:
parameters = {'batch_size': [10, 24, 32],
              'epochs': [50, 100, 200],
              'optimizer': ['adam', 'rmsprop']}

grid_search = GridSearchCV(estimator = classifier,
                           scoring = 'accuracy',
                           param_grid = parameters,
                           cv = 10)

grid_search = grid_search.fit(X_train, y_train)

best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

Epoch 1/50
720/720 [==============================] - 0s 581us/step - loss: 0.4941 - accuracy: 0.7965
Epoch 2/50
720/720 [==============================] - 0s 617us/step - loss: 0.4328 - accuracy: 0.7971
Epoch 3/50
720/720 [==============================] - 0s 662us/step - loss: 0.4311 - accuracy: 0.7971
Epoch 4/50
720/720 [==============================] - 0s 592us/step - loss: 0.4287 - accuracy: 0.7971
Epoch 5/50
720/720 [==============================] - 1s 734us/step - loss: 0.4287 - accuracy: 0.7971
Epoch 6/50
720/720 [==============================] - 1s 700us/step - loss: 0.4251 - accuracy: 0.8143
Epoch 7/50
720/720 [==============================] - 0s 557us/step - loss: 0.4262 - accuracy: 0.8213
Epoch 8/50
720/720 [==============================] - 0s 507us/step - loss: 0.4229 - accuracy: 0.8239
Epoch 9/50
720/720 [==============================] - 0s 504us/step - loss: 0.4256 - accuracy: 0.8247
Epoch 10/50
720/720 [==============================] - 0s 514us/step - loss: 0.425

Epoch 25/50
720/720 [==============================] - 0s 538us/step - loss: 0.4224 - accuracy: 0.8303
Epoch 26/50
720/720 [==============================] - 0s 521us/step - loss: 0.4222 - accuracy: 0.8293
Epoch 27/50
720/720 [==============================] - 0s 526us/step - loss: 0.4268 - accuracy: 0.8289
Epoch 28/50
720/720 [==============================] - 0s 532us/step - loss: 0.4264 - accuracy: 0.8306
Epoch 29/50
720/720 [==============================] - 0s 535us/step - loss: 0.4195 - accuracy: 0.8304
Epoch 30/50
720/720 [==============================] - 0s 540us/step - loss: 0.4228 - accuracy: 0.82780s - loss: 0.4237 - accuracy: 
Epoch 31/50
720/720 [==============================] - 0s 544us/step - loss: 0.4260 - accuracy: 0.8293
Epoch 32/50
720/720 [==============================] - 0s 553us/step - loss: 0.4198 - accuracy: 0.8296
Epoch 33/50
720/720 [==============================] - 0s 552us/step - loss: 0.4249 - accuracy: 0.8300
Epoch 34/50
720/720 [======================

720/720 [==============================] - 0s 546us/step - loss: 0.4282 - accuracy: 0.7975
Epoch 4/50
720/720 [==============================] - 0s 549us/step - loss: 0.4269 - accuracy: 0.7975
Epoch 5/50
720/720 [==============================] - 0s 549us/step - loss: 0.4221 - accuracy: 0.8093
Epoch 6/50
720/720 [==============================] - 0s 525us/step - loss: 0.4249 - accuracy: 0.8232
Epoch 7/50
720/720 [==============================] - 0s 548us/step - loss: 0.4219 - accuracy: 0.8256
Epoch 8/50
720/720 [==============================] - 0s 634us/step - loss: 0.4236 - accuracy: 0.8282
Epoch 9/50
720/720 [==============================] - 0s 633us/step - loss: 0.4199 - accuracy: 0.8281
Epoch 10/50
720/720 [==============================] - 0s 510us/step - loss: 0.4217 - accuracy: 0.8290
Epoch 11/50
720/720 [==============================] - 0s 531us/step - loss: 0.4236 - accuracy: 0.8290
Epoch 12/50
720/720 [==============================] - 0s 614us/step - loss: 0.4210 - accur

720/720 [==============================] - 0s 531us/step - loss: 0.3881 - accuracy: 0.8411
Epoch 33/50
720/720 [==============================] - 0s 585us/step - loss: 0.3850 - accuracy: 0.8436
Epoch 34/50
720/720 [==============================] - 0s 546us/step - loss: 0.3896 - accuracy: 0.8438
Epoch 35/50
720/720 [==============================] - 0s 570us/step - loss: 0.3891 - accuracy: 0.8425
Epoch 36/50
720/720 [==============================] - 0s 547us/step - loss: 0.3872 - accuracy: 0.84260s - loss: 0.3737 - accuracy: 
Epoch 37/50
720/720 [==============================] - 0s 632us/step - loss: 0.3869 - accuracy: 0.8431
Epoch 38/50
720/720 [==============================] - 0s 657us/step - loss: 0.3803 - accuracy: 0.8444
Epoch 39/50
720/720 [==============================] - 0s 670us/step - loss: 0.3836 - accuracy: 0.8435
Epoch 40/50
720/720 [==============================] - 0s 555us/step - loss: 0.3903 - accuracy: 0.8449
Epoch 41/50
720/720 [==============================] - 

720/720 [==============================] - 0s 531us/step - loss: 0.4201 - accuracy: 0.8256
Epoch 12/50
720/720 [==============================] - 0s 544us/step - loss: 0.4147 - accuracy: 0.8300
Epoch 13/50
720/720 [==============================] - 0s 547us/step - loss: 0.4209 - accuracy: 0.8225
Epoch 14/50
720/720 [==============================] - 0s 540us/step - loss: 0.4165 - accuracy: 0.8233
Epoch 15/50
720/720 [==============================] - 0s 549us/step - loss: 0.4191 - accuracy: 0.8256
Epoch 16/50
720/720 [==============================] - 0s 549us/step - loss: 0.4159 - accuracy: 0.8281
Epoch 17/50
720/720 [==============================] - 0s 539us/step - loss: 0.4162 - accuracy: 0.8276
Epoch 18/50
720/720 [==============================] - 0s 604us/step - loss: 0.4133 - accuracy: 0.8282
Epoch 19/50
720/720 [==============================] - 0s 603us/step - loss: 0.4155 - accuracy: 0.8276
Epoch 20/50
720/720 [==============================] - 0s 664us/step - loss: 0.4163 -

720/720 [==============================] - 0s 567us/step - loss: 0.4185 - accuracy: 0.8276
Epoch 41/50
720/720 [==============================] - 0s 538us/step - loss: 0.4194 - accuracy: 0.8311
Epoch 42/50
720/720 [==============================] - 0s 531us/step - loss: 0.4224 - accuracy: 0.8301
Epoch 43/50
720/720 [==============================] - 0s 585us/step - loss: 0.4162 - accuracy: 0.8294
Epoch 44/50
720/720 [==============================] - 0s 572us/step - loss: 0.4182 - accuracy: 0.8306
Epoch 45/50
720/720 [==============================] - 0s 546us/step - loss: 0.4200 - accuracy: 0.8299
Epoch 46/50
720/720 [==============================] - 0s 546us/step - loss: 0.4188 - accuracy: 0.8315
Epoch 47/50
720/720 [==============================] - 0s 508us/step - loss: 0.4203 - accuracy: 0.8294
Epoch 48/50
720/720 [==============================] - 0s 531us/step - loss: 0.4202 - accuracy: 0.8325
Epoch 49/50
720/720 [==============================] - 0s 616us/step - loss: 0.4206 -

KeyboardInterrupt: 

# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)