# REDES NEURAIS ARTIFICIAIS

[Aula 3 de Deep Learning](http://bit.ly/dn-unb03) da Engenharia de Software da UnB

# Parte 1 - Pré-processamento dos Dados

### Importar as libs

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.2.0'

### Importar o dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


### Transformando os dados categóricos


In [5]:
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]
[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
np.shape(X_train)

(8000, 12)

---
# Parte 2 -Vamos construir uma ANN!


### Initializing the ANN

In [9]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(64, kernel_initializer='lecun_normal', activation='selu'))

In [11]:
#ann.add(tf.keras.layers.Dense(units=12, activation='relu'))

### Adding the second hidden layer

In [12]:
#ann.add(tf.keras.layers.Dense(units=12, activation='relu'))

In [13]:
ann.add(tf.keras.layers.Dense(32, kernel_initializer='lecun_normal', activation='selu'))

### Adding the output layer

In [14]:
#ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [15]:
ann.add(tf.keras.layers.Dense(16, kernel_initializer='lecun_normal', activation='selu'))
ann.add(tf.keras.layers.Dense(10, activation='softmax'))

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [17]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [18]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 565us/step - loss: 0.5641 - accuracy: 0.1009
Epoch 2/100
250/250 [==============================] - 0s 543us/step - loss: 0.5554 - accuracy: 0.0932
Epoch 3/100
250/250 [==============================] - 0s 539us/step - loss: 0.5546 - accuracy: 0.0941
Epoch 4/100
250/250 [==============================] - 0s 577us/step - loss: 0.5542 - accuracy: 0.0976
Epoch 5/100
250/250 [==============================] - 0s 556us/step - loss: 0.5540 - accuracy: 0.0920
Epoch 6/100
250/250 [==============================] - 0s 553us/step - loss: 0.5539 - accuracy: 0.0940
Epoch 7/100
250/250 [==============================] - 0s 613us/step - loss: 0.5538 - accuracy: 0.0844
Epoch 8/100
250/250 [==============================] - 0s 567us/step - loss: 0.5538 - accuracy: 0.0839
Epoch 9/100
250/250 [==============================] - 0s 556us/step - loss: 0.5537 - accuracy: 0.0833
Epoch 10/100
250/250 [==============================] - 0s 562us/step - l

250/250 [==============================] - 0s 512us/step - loss: 0.5536 - accuracy: 0.1028
Epoch 80/100
250/250 [==============================] - 0s 501us/step - loss: 0.5536 - accuracy: 0.0769
Epoch 81/100
250/250 [==============================] - 0s 501us/step - loss: 0.5536 - accuracy: 0.1064
Epoch 82/100
250/250 [==============================] - 0s 490us/step - loss: 0.5536 - accuracy: 0.0971
Epoch 83/100
250/250 [==============================] - 0s 498us/step - loss: 0.5536 - accuracy: 0.0675
Epoch 84/100
250/250 [==============================] - 0s 512us/step - loss: 0.5536 - accuracy: 0.1260
Epoch 85/100
250/250 [==============================] - 0s 533us/step - loss: 0.5536 - accuracy: 0.0608
Epoch 86/100
250/250 [==============================] - 0s 548us/step - loss: 0.5536 - accuracy: 0.0532
Epoch 87/100
250/250 [==============================] - 0s 533us/step - loss: 0.5536 - accuracy: 0.0780
Epoch 88/100
250/250 [==============================] - 0s 506us/step - loss:

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [19]:
y_pred = ann.predict(X_test)
y_pred

array([[0.09998748, 0.10000029, 0.10005578, ..., 0.09993683, 0.09996992,
        0.10004209],
       [0.09999616, 0.09999076, 0.0999281 , ..., 0.10003062, 0.100092  ,
        0.09993714],
       [0.10006294, 0.09997555, 0.10005169, ..., 0.09984722, 0.1000784 ,
        0.09998   ],
       ...,
       [0.10007229, 0.09999349, 0.10003654, ..., 0.09997302, 0.10005049,
        0.09994376],
       [0.09999897, 0.09997822, 0.10004406, ..., 0.09999807, 0.09992399,
        0.10001165],
       [0.10001615, 0.10001513, 0.1001041 , ..., 0.09991575, 0.09993739,
        0.10009843]], dtype=float32)

In [20]:
y_pred = (y_pred > 0.5)
y_pred

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

# Criando uma Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

ValueError: Classification metrics can't handle a mix of binary and multilabel-indicator targets

# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)