# REDES NEURAIS ARTIFICIAIS

[Aula 3 de Deep Learning](http://bit.ly/dn-unb03) da Engenharia de Software da UnB

# Parte 1 - Pré-processamento dos Dados

### Importar as libs

In [2]:
pip install tensorflow

     |████████████████████████████████| 394.4 MB 43 kB/s s eta 0:00:01    |██▉                             | 35.2 MB 27.0 MB/s eta 0:00:14     |███▌                            | 43.6 MB 27.0 MB/s eta 0:00:13     |████▊                           | 58.2 MB 31.8 MB/s eta 0:00:11     |█████▊                          | 69.9 MB 31.8 MB/s eta 0:00:11     |██████▎                         | 77.1 MB 31.8 MB/s eta 0:00:10     |██████▊                         | 82.9 MB 30.8 MB/s eta 0:00:11     |███████                         | 85.7 MB 30.8 MB/s eta 0:00:11     |███████                         | 87.2 MB 30.8 MB/s eta 0:00:10     |████████▋                       | 106.0 MB 30.8 MB/s eta 0:00:10     |█████████████▏                  | 162.2 MB 25.6 MB/s eta 0:00:10     |█████████████████               | 209.0 MB 24.9 MB/s eta 0:00:08     |███████████████████▍            | 238.6 MB 27.2 MB/s eta 0:00:06     |█████████████████████           | 259.1 MB 30.3 MB/s eta 0:00:05     |███████████████████████

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.4.1'

### Importar o dataset

In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


### Transformando os dados categóricos


In [6]:
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]
[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [28]:
np.shape(X_train)

(8000, 12)

---
# Parte 2 -Vamos construir uma ANN!


### Initializing the ANN

In [29]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [30]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [31]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [32]:
ann.add(tf.keras.layers.Dense(units=6, activation='softmax'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='tah'))

### Adding the output layer

In [33]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [34]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [35]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 979us/step - loss: 0.6622 - accuracy: 0.5670
Epoch 2/100
250/250 [==============================] - 0s 895us/step - loss: 0.5077 - accuracy: 0.8008
Epoch 3/100
250/250 [==============================] - 0s 888us/step - loss: 0.4738 - accuracy: 0.8032
Epoch 4/100
250/250 [==============================] - 0s 910us/step - loss: 0.4514 - accuracy: 0.8070
Epoch 5/100
250/250 [==============================] - 0s 898us/step - loss: 0.4454 - accuracy: 0.8116
Epoch 6/100
250/250 [==============================] - 0s 908us/step - loss: 0.4302 - accuracy: 0.8229
Epoch 7/100
250/250 [==============================] - 0s 932us/step - loss: 0.4313 - accuracy: 0.8237
Epoch 8/100
250/250 [==============================] - 0s 884us/step - loss: 0.4233 - accuracy: 0.8274
Epoch 9/100
250/250 [==============================] - 0s 895us/step - loss: 0.4270 - accuracy: 0.8202
Epoch 10/100
250/250 [==============================] - 0s 883us/step - l

250/250 [==============================] - 0s 874us/step - loss: 0.3372 - accuracy: 0.8615
Epoch 80/100
250/250 [==============================] - 0s 883us/step - loss: 0.3276 - accuracy: 0.8666
Epoch 81/100
250/250 [==============================] - 0s 909us/step - loss: 0.3374 - accuracy: 0.8644
Epoch 82/100
250/250 [==============================] - 0s 954us/step - loss: 0.3399 - accuracy: 0.8621
Epoch 83/100
250/250 [==============================] - 0s 906us/step - loss: 0.3275 - accuracy: 0.8678
Epoch 84/100
250/250 [==============================] - 0s 880us/step - loss: 0.3485 - accuracy: 0.8587
Epoch 85/100
250/250 [==============================] - 0s 879us/step - loss: 0.3416 - accuracy: 0.8591
Epoch 86/100
250/250 [==============================] - 0s 890us/step - loss: 0.3323 - accuracy: 0.8655
Epoch 87/100
250/250 [==============================] - 0s 877us/step - loss: 0.3377 - accuracy: 0.8575
Epoch 88/100
250/250 [==============================] - 0s 878us/step - loss:

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [36]:
y_pred = ann.predict(X_test)
y_pred

array([[0.24515888],
       [0.33670524],
       [0.1178062 ],
       ...,
       [0.1478169 ],
       [0.180673  ],
       [0.23727572]], dtype=float32)

In [37]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

# Criando uma Confusion Matrix

In [38]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1526   69]
 [ 214  191]]


In [39]:
def printResults(hits,misses):
    print(f'O modelo teve {(hits/(misses+hits))*100}% de acerto')

printResults(np.trace(cm), np.trace(np.fliplr(cm)))

O modelo teve 85.85000000000001% de acerto


# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)