# REDES NEURAIS ARTIFICIAIS

[Aula 3 de Deep Learning](http://bit.ly/dn-unb03) da Engenharia de Software da UnB

In [10]:
# Installing Theano
! pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
! pip install --upgrade tensorflow

# Installing Keras
! pip install --upgrade keras

# Install other packages
! pip install --upgrade pip pandas numpy matplotlib sklearn

  Cloning git://github.com/Theano/Theano.git to /tmp/pip-req-build-yg28slel
  Running command git clone -q git://github.com/Theano/Theano.git /tmp/pip-req-build-yg28slel
  Created wheel for Theano: filename=Theano-1.0.4+21.g8f510a1-cp35-none-any.whl size=2667468 sha256=1bc0e174abbfa8dc518300a78cdb5f7df6951377534daaee6ca3768461d1f3f5
  Stored in directory: /tmp/pip-ephem-wheel-cache-funqt_j_/wheels/ae/32/7c/62beb8371953eb20c271b3bac7d0e56e1a2020d46994346b52
Successfully built Theano
  Found existing installation: Theano 1.0.4+21.g8f510a1
    Uninstalling Theano-1.0.4+21.g8f510a1:
      Successfully uninstalled Theano-1.0.4+21.g8f510a1
Requirement already up-to-date: tensorflow in /home/guiz/unb/dl-unb/dl-unb/lib/python3.5/site-packages (1.14.0)
Requirement already up-to-date: keras in /home/guiz/unb/dl-unb/dl-unb/lib/python3.5/site-packages (2.3.0)
Requirement already up-to-date: pip in /home/guiz/unb/dl-unb/dl-unb/lib/python3.5/site-packages (19.2.3)
Requirement already up-to-date: pan

# Parte 1 - Preprocessamento dos Dados

### Importar as libs

In [11]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Importar o dataset

In [12]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


### Transformando os dados categóricos


In [21]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]
print("X >>\n",X)

X >>
 [[0.0000000e+00 0.0000000e+00 6.1900000e+02 ... 1.0000000e+00
  1.0000000e+00 1.0134888e+05]
 [0.0000000e+00 1.0000000e+00 6.0800000e+02 ... 0.0000000e+00
  1.0000000e+00 1.1254258e+05]
 [0.0000000e+00 0.0000000e+00 5.0200000e+02 ... 1.0000000e+00
  0.0000000e+00 1.1393157e+05]
 ...
 [0.0000000e+00 0.0000000e+00 7.0900000e+02 ... 0.0000000e+00
  1.0000000e+00 4.2085580e+04]
 [1.0000000e+00 0.0000000e+00 7.7200000e+02 ... 1.0000000e+00
  0.0000000e+00 9.2888520e+04]
 [0.0000000e+00 0.0000000e+00 7.9200000e+02 ... 1.0000000e+00
  0.0000000e+00 3.8190780e+04]]


/home/guiz/unb/dl-unb/dl-unb/lib/python3.5/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/guiz/unb/dl-unb/dl-unb/lib/python3.5/site-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

---
# Parte 2 -Vamos construir uma ANN!

## Importando o Keras


In [24]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [25]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'softsign'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Ajustando a ANN ao conjunto de treinamento

In [26]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 1s 121us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 106us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 105us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 116us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 5/100
8000/8000 [==============================] - 1s 154us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 114us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 7/100
8000/8000 [==============================] - 1s 114us/step - loss: 3.1467 - accuracy: 0.79600s - loss: 3.1481 
Epoch 8/100
8000/8000 [==============================] - 1s 122us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 9/100
8000/8000 [==============================] - 1s 108us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 10/100
8000/8000 [=============

8000/8000 [==============================] - 1s 88us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 79/100
8000/8000 [==============================] - 1s 87us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 80/100
8000/8000 [==============================] - 1s 86us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 81/100
8000/8000 [==============================] - 1s 86us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 82/100
8000/8000 [==============================] - 1s 85us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 83/100
8000/8000 [==============================] - 1s 86us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 84/100
8000/8000 [==============================] - 1s 90us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 85/100
8000/8000 [==============================] - 1s 120us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 86/100
8000/8000 [==============================] - 1s 150us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 87/100
8000/8000 [==============================] - 1s 130us

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [27]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Criando uma Confusion Matrix

In [28]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1595    0]
 [ 405    0]]


# Initiate activation function experimentation

# Initialising the 2nd ANN

In [29]:
del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'softsign'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 1s 138us/step - loss: 0.5160 - accuracy: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 129us/step - loss: 0.4901 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 164us/step - loss: 0.4633 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 2s 197us/step - loss: 0.4421 - accuracy: 0.7960
Epoch 5/100
8000/8000 [==============================] - 1s 180us/step - loss: 0.4369 - accuracy: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 151us/step - loss: 0.4373 - accuracy: 0.7960
Epoch 7/100
8000/8000 [==============================] - 2s 204us/step - loss: 0.4341 - accuracy: 0.7960
Epoch 8/100
8000/8000 [==============================] - 1s 138us/step - loss: 0.4329 - accuracy: 0.7960
Epoch 9/100
8000/8000 [==============================] - 1s 116us/step - loss: 0.4316 - accuracy: 0.7960
Epoch 10/100
8000/8000 [==============================]

8000/8000 [==============================] - 1s 107us/step - loss: 0.3744 - accuracy: 0.8394
Epoch 79/100
8000/8000 [==============================] - 1s 108us/step - loss: 0.3782 - accuracy: 0.8405
Epoch 80/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.3830 - accuracy: 0.8426
Epoch 81/100
8000/8000 [==============================] - 1s 108us/step - loss: 0.3751 - accuracy: 0.8428
Epoch 82/100
8000/8000 [==============================] - 1s 94us/step - loss: 0.3750 - accuracy: 0.8430
Epoch 83/100
8000/8000 [==============================] - 1s 87us/step - loss: 0.3754 - accuracy: 0.8422
Epoch 84/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.3728 - accuracy: 0.8429
Epoch 85/100
8000/8000 [==============================] - 1s 108us/step - loss: 0.3733 - accuracy: 0.8430
Epoch 86/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.3729 - accuracy: 0.8429
Epoch 87/100
8000/8000 [==============================] - 1s 

In [30]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix

In [31]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1505   90]
 [ 224  181]]


# Initialising the 3rd ANN

In [32]:
del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 1s 120us/step - loss: 0.5114 - accuracy: 0.7952
Epoch 2/100
8000/8000 [==============================] - 1s 103us/step - loss: 0.4461 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 103us/step - loss: 0.4342 - accuracy: 0.7964
Epoch 4/100
8000/8000 [==============================] - 1s 103us/step - loss: 0.4296 - accuracy: 0.7980
Epoch 5/100
8000/8000 [==============================] - 1s 103us/step - loss: 0.4282 - accuracy: 0.8006
Epoch 6/100
8000/8000 [==============================] - 1s 103us/step - loss: 0.4277 - accuracy: 0.8021
Epoch 7/100
8000/8000 [==============================] - 1s 104us/step - loss: 0.4272 - accuracy: 0.8026
Epoch 8/100
8000/8000 [==============================] - 1s 104us/step - loss: 0.4271 - accuracy: 0.8041
Epoch 9/100
8000/8000 [==============================] - 1s 104us/step - loss: 0.4272 - accuracy: 0.8044
Epoch 10/100
8000/8000 [==============================]

8000/8000 [==============================] - 1s 124us/step - loss: 0.3969 - accuracy: 0.8340
Epoch 79/100
8000/8000 [==============================] - 1s 103us/step - loss: 0.3965 - accuracy: 0.8353
Epoch 80/100
8000/8000 [==============================] - 1s 104us/step - loss: 0.3962 - accuracy: 0.8353
Epoch 81/100
8000/8000 [==============================] - 1s 105us/step - loss: 0.3961 - accuracy: 0.8353
Epoch 82/100
8000/8000 [==============================] - 1s 105us/step - loss: 0.3957 - accuracy: 0.8353
Epoch 83/100
8000/8000 [==============================] - 1s 104us/step - loss: 0.3957 - accuracy: 0.8342
Epoch 84/100
8000/8000 [==============================] - 1s 104us/step - loss: 0.3957 - accuracy: 0.8351
Epoch 85/100
8000/8000 [==============================] - 1s 105us/step - loss: 0.3953 - accuracy: 0.8359
Epoch 86/100
8000/8000 [==============================] - 1s 104us/step - loss: 0.3953 - accuracy: 0.8345
Epoch 87/100
8000/8000 [==============================] - 1

In [33]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix

In [34]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1539   56]
 [ 256  149]]


---
# Parte 4 - Evaluating, Improving and Tuning the ANN

## Evaluating the ANN

In [ ]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()
print("accuracies:%s\nmean:%s\nvariance:%s".format(accuracies, mean, variance))

# Improving the ANN
# Dropout Regularization to reduce overfitting if needed

In [ ]:
from keras.layers import Dropout

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()

# Tuning the ANN

In [ ]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense

def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier)

In [ ]:
parameters = {'batch_size': [10, 24, 32],
              'epochs': [50, 100, 200],
              'optimizer': ['adam', 'rmsprop']}

grid_search = GridSearchCV(estimator = classifier,
                           scoring = 'accuracy',
                           param_grid = parameters,
                           cv = 10)

grid_search = grid_search.fit(X_train, y_train)

best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)