# REDES NEURAIS ARTIFICIAIS

[Aula 3 de Deep Learning](http://bit.ly/dn-unb03) da Engenharia de Software da UnB

# Parte 1 - Preprocessamento dos Dados

In [1]:
# Installing Theano
! pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
! pip install --upgrade tensorflow

# Installing Keras
! pip install --upgrade keras

# Install other packages
! pip install --upgrade pip pandas numpy matplotlib sklearn

Eugenio


### Importar as libs

In [6]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

### Importar o dataset

In [7]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


### Transformando os dados categóricos


In [8]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]
print("X >>\n",X)

X >>
 [[0.0000000e+00 0.0000000e+00 6.1900000e+02 ... 1.0000000e+00
  1.0000000e+00 1.0134888e+05]
 [0.0000000e+00 1.0000000e+00 6.0800000e+02 ... 0.0000000e+00
  1.0000000e+00 1.1254258e+05]
 [0.0000000e+00 0.0000000e+00 5.0200000e+02 ... 1.0000000e+00
  0.0000000e+00 1.1393157e+05]
 ...
 [0.0000000e+00 0.0000000e+00 7.0900000e+02 ... 0.0000000e+00
  1.0000000e+00 4.2085580e+04]
 [1.0000000e+00 0.0000000e+00 7.7200000e+02 ... 1.0000000e+00
  0.0000000e+00 9.2888520e+04]
 [0.0000000e+00 0.0000000e+00 7.9200000e+02 ... 1.0000000e+00
  0.0000000e+00 3.8190780e+04]]


# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

---
# Parte 2 -Vamos construir uma ANN!

## Importando o Keras


In [16]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [17]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'tanh'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Ajustando a ANN ao conjunto de treinamento

In [47]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 2s 236us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 2/100
8000/8000 [==============================] - 2s 218us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 175us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 181us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 5/100
8000/8000 [==============================] - 2s 189us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 6/100
8000/8000 [==============================] - 2s 249us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 7/100
8000/8000 [==============================] - 1s 176us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 8/100
8000/8000 [==============================] - 2s 188us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 9/100
8000/8000 [==============================] - 1s 183us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 10/100
8000/8000 [==============================]

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [18]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Criando uma Confusion Matrix

In [19]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1595    0]
 [ 405    0]]


# Accuracy of Tanh

In [20]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy of tanh as activation function: {}'.format(accuracy))

Accuracy of tanh as activation function: 0.7975


# Initiate activation function experimentation

# Initialising the 2nd ANN

In [53]:
del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'elu'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 2s 225us/step - loss: 0.5242 - accuracy: 0.7995
Epoch 2/100
8000/8000 [==============================] - 1s 185us/step - loss: 0.4189 - accuracy: 0.8104
Epoch 3/100
8000/8000 [==============================] - 2s 207us/step - loss: 0.4016 - accuracy: 0.8150
Epoch 4/100
8000/8000 [==============================] - 1s 175us/step - loss: 0.3918 - accuracy: 0.8254
Epoch 5/100
8000/8000 [==============================] - 1s 175us/step - loss: 0.3854 - accuracy: 0.8317
Epoch 6/100
8000/8000 [==============================] - 1s 175us/step - loss: 0.3755 - accuracy: 0.8356
Epoch 7/100
8000/8000 [==============================] - 1s 178us/step - loss: 0.3733 - accuracy: 0.8415
Epoch 8/100
8000/8000 [==============================] - 1s 186us/step - loss: 0.3735 - accuracy: 0.8422
Epoch 9/100
8000/8000 [==============================] - 1s 182us/step - loss: 0.3737 - accuracy: 0.8406
Epoch 10/100
8000/8000 [==============================]

In [21]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix

In [22]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1595    0]
 [ 405    0]]


# Accuracy of  Elu

In [23]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy of elu as activation function: {}'.format(accuracy))

Accuracy of elu as activation function: 0.7975


# Initialising the 3rd ANN

In [24]:
del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/100
8000/8000 [==============================] - 3s 344us/step - loss: 0.4778 - accuracy: 0.7959
Epoch 2/100
8000/8000 [==============================] - 1s 156us/step - loss: 0.4257 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 184us/step - loss: 0.4196 - accuracy: 0.8070
Epoch 4/100
8000/8000 [==============================] - 1s 164us/step - loss: 0.4165 - accuracy: 0.8253
Epoch 5/100
8000/8000 [==============================] - 1s 164us/step - loss: 0.4149 - accuracy: 0.8292
Epoch 6/100
8000/8000 [==============================] - 1s 150us/step - loss: 0.4137 - accuracy: 0.8305
Epoch 7/100
8000/8000 [==============================] - 2s 230us/step - loss: 0.4121 - accuracy: 0.8317
Epoch 8/100
8000/8000 [==============================] - 2s 194us/step - loss: 0.4112 - accuracy: 0.8326
Epoch 9/100
8000/8000 [==============================] - 1s 186us/

8000/8000 [==============================] - 1s 145us/step - loss: 0.3676 - accuracy: 0.8421
Epoch 76/100
8000/8000 [==============================] - 1s 145us/step - loss: 0.3674 - accuracy: 0.8434
Epoch 77/100
8000/8000 [==============================] - 1s 143us/step - loss: 0.3676 - accuracy: 0.8434
Epoch 78/100
8000/8000 [==============================] - 1s 145us/step - loss: 0.3672 - accuracy: 0.8420
Epoch 79/100
8000/8000 [==============================] - 1s 147us/step - loss: 0.3670 - accuracy: 0.8435
Epoch 80/100
8000/8000 [==============================] - 1s 144us/step - loss: 0.3671 - accuracy: 0.8426
Epoch 81/100
8000/8000 [==============================] - 1s 146us/step - loss: 0.3667 - accuracy: 0.8440
Epoch 82/100
8000/8000 [==============================] - 1s 146us/step - loss: 0.3671 - accuracy: 0.8424
Epoch 83/100
8000/8000 [==============================] - 1s 145us/step - loss: 0.3676 - accuracy: 0.8425
Epoch 84/100
8000/8000 [==============================] - 1

In [25]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix

In [26]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1531   64]
 [ 250  155]]


# Accuracy of Sigmoid

In [27]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy of tanh as activation function: {}'.format(accuracy))

Accuracy of tanh as activation function: 0.843


---
# Parte 4 - Evaluating, Improving and Tuning the ANN

## Evaluating the ANN

In [ ]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()
print("accuracies:%s\nmean:%s\nvariance:%s".format(accuracies, mean, variance))

Epoch 1/10
7200/7200 [==============================] - 2s 215us/step - loss: 0.5013 - accuracy: 0.7967
Epoch 2/10
7200/7200 [==============================] - 1s 162us/step - loss: 0.4313 - accuracy: 0.7971
Epoch 3/10
7200/7200 [==============================] - 1s 155us/step - loss: 0.4277 - accuracy: 0.7971
Epoch 4/10
7200/7200 [==============================] - 1s 167us/step - loss: 0.4241 - accuracy: 0.7971
Epoch 5/10
7200/7200 [==============================] - 1s 167us/step - loss: 0.4205 - accuracy: 0.8044
Epoch 6/10
7200/7200 [==============================] - 1s 167us/step - loss: 0.4176 - accuracy: 0.8243
Epoch 7/10
7200/7200 [==============================] - 1s 168us/step - loss: 0.4156 - accuracy: 0.8258
Epoch 8/10
7200/7200 [==============================] - 2s 287us/step - loss: 0.4144 - accuracy: 0.8278
Epoch 9/10
7200/7200 [==============================] - 1s 181us/step - loss: 0.4130 - accuracy: 0.8306
Epoch 10/10
800/800 [==============================] - 0s 154us/

# Improving the ANN
# Dropout Regularization to reduce overfitting if needed

In [ ]:
from keras.layers import Dropout

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()

# Tuning the ANN

In [ ]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense

def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier)

In [ ]:
parameters = {'batch_size': [10, 24, 32],
              'epochs': [50, 100, 200],
              'optimizer': ['adam', 'rmsprop']}

grid_search = GridSearchCV(estimator = classifier,
                           scoring = 'accuracy',
                           param_grid = parameters,
                           cv = 10)

grid_search = grid_search.fit(X_train, y_train)

best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)