# REDES NEURAIS ARTIFICIAIS

[Aula 3 de Deep Learning](http://bit.ly/dn-unb03) da Engenharia de Software da UnB

In [12]:
# Installing Theano
! pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
! pip install --upgrade tensorflow

# Installing Keras
! pip install --upgrade keras

# Install other packages
! pip install --upgrade pip pandas numpy matplotlib sklearn

  Cloning git://github.com/Theano/Theano.git to /tmp/pip-req-build-gd3u691l
  Running command git clone -q git://github.com/Theano/Theano.git /tmp/pip-req-build-gd3u691l
  Created wheel for Theano: filename=Theano-1.0.4+23.g630974a7b-cp37-none-any.whl size=2667498 sha256=a418dcd0071675b8fafa940f379dd7ed482569abaadf3619eb96694233561601
  Stored in directory: /tmp/pip-ephem-wheel-cache-m1l116s5/wheels/ae/32/7c/62beb8371953eb20c271b3bac7d0e56e1a2020d46994346b52
Successfully built Theano
     |████████████████████████████████| 86.3MB 5.8MB/s eta 0:00:011    |████▏                           | 11.3MB 4.4MB/s eta 0:00:17     |███████████▉                    | 32.0MB 11.4MB/s eta 0:00:05     |█████████████▉                  | 37.3MB 11.4MB/s eta 0:00:05     |██████████████                  | 37.8MB 11.4MB/s eta 0:00:05     |███████████████▊                | 42.4MB 8.7MB/s eta 0:00:06     |████████████████                | 43.0MB 8.7MB/s eta 0:00:05     |████████████████▍               | 44.2MB

  Created wheel for wrapt: filename=wrapt-1.11.2-cp37-cp37m-linux_x86_64.whl size=70712 sha256=1c67cb91f00406f7c42d391f12c6232009014995a5e74be848a8c8d3e4f22f68
  Stored in directory: /home/jovyan/.cache/pip/wheels/d7/de/2e/efa132238792efb6459a96e85916ef8597fcb3d2ae51590dfd
  Created wheel for gast: filename=gast-0.2.2-cp37-none-any.whl size=7540 sha256=8bc05060794a9d3c5e514039628d1dacb4a14ac7a201c95422a65f9a919c0cfe
  Stored in directory: /home/jovyan/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
  Created wheel for opt-einsum: filename=opt_einsum-3.1.0-cp37-none-any.whl size=61682 sha256=355c5dea6017765f91b74243448e32268e0f7fba2d42301ea5a8e484bf04ea84
  Stored in directory: /home/jovyan/.cache/pip/wheels/2c/b1/94/43d03e130b929aae7ba3f8d15cbd7bc0d1cb5bb38a5c721833
Successfully built wrapt gast opt-einsum
  Found existing installation: gast 0.3.2
    Uninstalling gast-0.3.2:
      Successfully uninstalled gast-0.3.2
  Found existing installation: tensorbo

# Parte 1 - Preprocessamento dos Dados

### Importar as libs

In [13]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Importar o dataset

In [14]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


### Transformando os dados categóricos


In [15]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]
print("X >>\n",X)

X >>
 [[0.0000000e+00 0.0000000e+00 6.1900000e+02 ... 1.0000000e+00
  1.0000000e+00 1.0134888e+05]
 [0.0000000e+00 1.0000000e+00 6.0800000e+02 ... 0.0000000e+00
  1.0000000e+00 1.1254258e+05]
 [0.0000000e+00 0.0000000e+00 5.0200000e+02 ... 1.0000000e+00
  0.0000000e+00 1.1393157e+05]
 ...
 [0.0000000e+00 0.0000000e+00 7.0900000e+02 ... 0.0000000e+00
  1.0000000e+00 4.2085580e+04]
 [1.0000000e+00 0.0000000e+00 7.7200000e+02 ... 1.0000000e+00
  0.0000000e+00 9.2888520e+04]
 [0.0000000e+00 0.0000000e+00 7.9200000e+02 ... 1.0000000e+00
  0.0000000e+00 3.8190780e+04]]


/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

---
# Parte 2 -Vamos construir uma ANN!

## Importando o Keras


In [18]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [19]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'elu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'selu'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Ajustando a ANN ao conjunto de treinamento

In [20]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 2s 254us/step - loss: 0.4966 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 160us/step - loss: 0.4341 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 139us/step - loss: 0.4293 - acc: 0.7952
Epoch 4/100
8000/8000 [==============================] - 1s 143us/step - loss: 0.4278 - acc: 0.7956
Epoch 5/100
8000/8000 [==============================] - 1s 160us/step - loss: 0.4261 - acc: 0.8011
Epoch 6/100
8000/8000 [==============================] - 1s 170us/step - loss: 0.4221 - acc: 0.8039
Epoch 7/100
8000/8000 [==============================] - 1s 167us/step - loss: 0.4155 - acc: 0.8112
Epoch 8/100
8000/8000 [==============================] - 2s 193us/step - loss: 0.4042 - acc: 0.8154
Epoch 9/100
8000/8000 [==============================] - 1s 154us/step - loss: 0.3914 - acc: 0.8261
Epoch 10/100
8000/8000 [==============================] - 1s 148us/step - loss: 0.3790 - acc: 0.8384

8000/8000 [==============================] - 2s 257us/step - loss: 0.3393 - acc: 0.8620
Epoch 83/100
8000/8000 [==============================] - 3s 314us/step - loss: 0.3442 - acc: 0.8587
Epoch 84/100
8000/8000 [==============================] - 2s 258us/step - loss: 0.3397 - acc: 0.8611
Epoch 85/100
8000/8000 [==============================] - 2s 247us/step - loss: 0.3405 - acc: 0.8615
Epoch 86/100
8000/8000 [==============================] - 2s 282us/step - loss: 0.3403 - acc: 0.8592
Epoch 87/100
8000/8000 [==============================] - 2s 250us/step - loss: 0.3375 - acc: 0.8600
Epoch 88/100
8000/8000 [==============================] - 2s 224us/step - loss: 0.3415 - acc: 0.8607
Epoch 89/100
8000/8000 [==============================] - 2s 257us/step - loss: 0.3407 - acc: 0.8619
Epoch 90/100
8000/8000 [==============================] - 2s 309us/step - loss: 0.3380 - acc: 0.8611
Epoch 91/100
8000/8000 [==============================] - 2s 276us/step - loss: 0.3437 - acc: 0.8625
Epo

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [21]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Criando uma Confusion Matrix

In [22]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1533   62]
 [ 214  191]]


# Initiate activation function experimentation

# Initialising the 2nd ANN

In [23]:
del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'tanh'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 3s 318us/step - loss: 3.2881 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 183us/step - loss: 3.2881 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 170us/step - loss: 3.2881 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 2s 213us/step - loss: 3.2881 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 2s 195us/step - loss: 3.2881 - acc: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 175us/step - loss: 3.2881 - acc: 0.7960
Epoch 7/100
8000/8000 [==============================] - 1s 162us/step - loss: 3.2881 - acc: 0.7960
Epoch 8/100
8000/8000 [==============================] - 1s 152us/step - loss: 3.2881 - acc: 0.7960
Epoch 9/100
8000/8000 [==============================] - 1s 178us/step - loss: 3.2881 - acc: 0.7960
Epoch 10/100
8000/8000 [==============================] - 1s 151us/step - loss: 3.2881 - acc: 0.7960

8000/8000 [==============================] - 2s 203us/step - loss: 3.2881 - acc: 0.7960
Epoch 83/100
8000/8000 [==============================] - 2s 227us/step - loss: 3.2881 - acc: 0.7960
Epoch 84/100
8000/8000 [==============================] - 2s 212us/step - loss: 3.2881 - acc: 0.7960
Epoch 85/100
8000/8000 [==============================] - 2s 225us/step - loss: 3.2881 - acc: 0.7960
Epoch 86/100
8000/8000 [==============================] - 2s 213us/step - loss: 3.2881 - acc: 0.7960
Epoch 87/100
8000/8000 [==============================] - 1s 170us/step - loss: 3.2881 - acc: 0.7960
Epoch 88/100
8000/8000 [==============================] - 1s 178us/step - loss: 3.2881 - acc: 0.7960
Epoch 89/100
8000/8000 [==============================] - 2s 189us/step - loss: 3.2881 - acc: 0.7960
Epoch 90/100
8000/8000 [==============================] - 1s 172us/step - loss: 3.2881 - acc: 0.7960
Epoch 91/100
8000/8000 [==============================] - 1s 171us/step - loss: 3.2881 - acc: 0.7960
Epo

In [15]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix

In [16]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1595    0]
 [ 405    0]]


# Initialising the 3rd ANN

In [17]:
del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 2s 242us/step - loss: 0.5123 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 2s 193us/step - loss: 0.4461 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 191us/step - loss: 0.4341 - acc: 0.7956
Epoch 4/100
8000/8000 [==============================] - 1s 187us/step - loss: 0.4297 - acc: 0.7982
Epoch 5/100
8000/8000 [==============================] - 2s 190us/step - loss: 0.4280 - acc: 0.8000
Epoch 6/100
8000/8000 [==============================] - 1s 186us/step - loss: 0.4276 - acc: 0.8030
Epoch 7/100
8000/8000 [==============================] - 2s 189us/step - loss: 0.4266 - acc: 0.8042
Epoch 8/100
8000/8000 [==============================] - 2s 226us/step - loss: 0.4271 - acc: 0.8045
Epoch 9/100
8000/8000 [==============================] - 2s 252us/step - loss: 0.4268 - acc: 0.8049
Epoch 10/100
8000/8000 [==============================] - 2s 193us/step - loss: 0.4266 - acc: 0.8056

In [9]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix

In [10]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1528   67]
 [ 248  157]]


---
# Parte 4 - Evaluating, Improving and Tuning the ANN

## Evaluating the ANN

In [11]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()
print("accuracies:%s\nmean:%s\nvariance:%s".format(accuracies, mean, variance))

Epoch 1/10
7200/7200 [==============================] - 2s 226us/step - loss: 0.4966 - acc: 0.7960
Epoch 2/10
7200/7200 [==============================] - 2s 227us/step - loss: 0.4293 - acc: 0.7971
Epoch 3/10
7200/7200 [==============================] - 1s 165us/step - loss: 0.4248 - acc: 0.7971
Epoch 4/10
7200/7200 [==============================] - 1s 191us/step - loss: 0.4206 - acc: 0.8051
Epoch 5/10
7200/7200 [==============================] - 2s 210us/step - loss: 0.4180 - acc: 0.8207
Epoch 6/10
7200/7200 [==============================] - 2s 225us/step - loss: 0.4158 - acc: 0.8272
Epoch 7/10
7200/7200 [==============================] - 2s 214us/step - loss: 0.4142 - acc: 0.8271
Epoch 8/10
7200/7200 [==============================] - 2s 212us/step - loss: 0.4126 - acc: 0.8306
Epoch 9/10
7200/7200 [==============================] - 1s 183us/step - loss: 0.4112 - acc: 0.8325
Epoch 10/10
800/800 [==============================] - 0s 119us/step
Epoch 1/10
7200/7200 [==================

7200/7200 [==============================] - 1s 176us/step - loss: 0.4090 - acc: 0.8340
Epoch 10/10
800/800 [==============================] - 0s 282us/step
Epoch 1/10
7200/7200 [==============================] - 2s 253us/step - loss: 0.4908 - acc: 0.7957
Epoch 2/10
7200/7200 [==============================] - 1s 170us/step - loss: 0.4272 - acc: 0.7957
Epoch 3/10
7200/7200 [==============================] - 1s 176us/step - loss: 0.4225 - acc: 0.7957
Epoch 4/10
7200/7200 [==============================] - 1s 200us/step - loss: 0.4186 - acc: 0.8112
Epoch 5/10
7200/7200 [==============================] - 1s 189us/step - loss: 0.4153 - acc: 0.8254
Epoch 6/10
7200/7200 [==============================] - 1s 181us/step - loss: 0.4134 - acc: 0.8324
Epoch 7/10
7200/7200 [==============================] - 1s 178us/step - loss: 0.4110 - acc: 0.8318
Epoch 8/10
7200/7200 [==============================] - 1s 185us/step - loss: 0.4099 - acc: 0.8344
Epoch 9/10
7200/7200 [=============================

# Improving the ANN
# Dropout Regularization to reduce overfitting if needed

In [ ]:
from keras.layers import Dropout

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()

# Tuning the ANN

In [ ]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense

def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier)

In [ ]:
parameters = {'batch_size': [10, 24, 32],
              'epochs': [50, 100, 200],
              'optimizer': ['adam', 'rmsprop']}

grid_search = GridSearchCV(estimator = classifier,
                           scoring = 'accuracy',
                           param_grid = parameters,
                           cv = 10)

grid_search = grid_search.fit(X_train, y_train)

best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)