# REDES NEURAIS ARTIFICIAIS

[Aula 3 de Deep Learning](http://bit.ly/dn-unb03) da Engenharia de Software da UnB

# Parte 1 - Pré-processamento dos Dados

### Importar as libs

In [44]:
!pip3 install tensorflow

Defaulting to user installation because normal site-packages is not writeable
  Using cached numpy-1.19.5-cp38-cp38-manylinux2010_x86_64.whl (14.9 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.2
    Uninstalling numpy-1.21.2:
      Successfully uninstalled numpy-1.21.2


In [47]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [48]:
tf.__version__

'2.6.0'

### Importar o dataset

In [49]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head(50)
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


In [50]:
dataset.Geography.value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [51]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


### Transformando os dados categóricos


In [52]:
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X[:, 2])
print("X >>\n", X)

[0 0 0 ... 0 1 0]
X >>
 [[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [53]:
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(X))
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [54]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [55]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [56]:
np.shape(x_train)

(8000, 12)

In [57]:
x_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

---
# Parte 2 -Vamos construir uma ANN!


### Initializing the ANN

In [58]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [62]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [63]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [71]:
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))

### Adding the output layer

In [72]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

### Compiling the ANN

In [73]:
ann.compile(optimizer = 'sgd', loss = 'binary_crossentropy', metrics = ['accuracy'])

## Part 3 - Training the ANN

### Training the ANN on the Training set

In [74]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 875us/step - loss: 0.5947 - accuracy: 0.7979
Epoch 2/100
250/250 [==============================] - 0s 942us/step - loss: 0.5080 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 979us/step - loss: 0.4751 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 906us/step - loss: 0.4486 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 991us/step - loss: 0.4213 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 0s 903us/step - loss: 0.3962 - accuracy: 0.8311
Epoch 7/100
250/250 [==============================] - 0s 877us/step - loss: 0.3769 - accuracy: 0.8572
Epoch 8/100
250/250 [==============================] - 0s 940us/step - loss: 0.3642 - accuracy: 0.8621
Epoch 9/100
250/250 [==============================] - 0s 851us/step - loss: 0.3567 - accuracy: 0.8614
Epoch 10/100
250/250 [==============================] - 0s 967us/step - l

250/250 [==============================] - 0s 880us/step - loss: 0.3375 - accuracy: 0.8619
Epoch 80/100
250/250 [==============================] - 0s 821us/step - loss: 0.3368 - accuracy: 0.8604
Epoch 81/100
250/250 [==============================] - 0s 996us/step - loss: 0.3373 - accuracy: 0.8630
Epoch 82/100
250/250 [==============================] - 0s 913us/step - loss: 0.3369 - accuracy: 0.8625
Epoch 83/100
250/250 [==============================] - 0s 900us/step - loss: 0.3374 - accuracy: 0.8614
Epoch 84/100
250/250 [==============================] - 0s 906us/step - loss: 0.3369 - accuracy: 0.8619
Epoch 85/100
250/250 [==============================] - 0s 801us/step - loss: 0.3375 - accuracy: 0.8612
Epoch 86/100
250/250 [==============================] - 0s 887us/step - loss: 0.3372 - accuracy: 0.8625
Epoch 87/100
250/250 [==============================] - 0s 784us/step - loss: 0.3367 - accuracy: 0.8634
Epoch 88/100
250/250 [==============================] - 0s 741us/step - loss:

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [75]:
y_pred = ann.predict(x_test)
y_pred

array([[0.2721684 ],
       [0.30417424],
       [0.09643897],
       ...,
       [0.06966501],
       [0.13201615],
       [0.16371918]], dtype=float32)

In [76]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

# Criando uma Confusion Matrix

In [78]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1500   95]
 [ 189  216]]


# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)