# REDES NEURAIS ARTIFICIAIS

[Aula 3 de Deep Learning](http://bit.ly/dn-unb03) da Engenharia de Software da UnB

In [1]:
# Installing Theano
! pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
! pip install --upgrade tensorflow

# Installing Keras
! pip install --upgrade keras

# Install other packages
! pip install --upgrade pip pandas numpy matplotlib sklearn

  Cloning git://github.com/Theano/Theano.git to /private/var/folders/xv/6xdsnhm10jg5y1g0bm3kp9140000gp/T/pip-req-build-8g5oafk2
  Running command git clone -q git://github.com/Theano/Theano.git /private/var/folders/xv/6xdsnhm10jg5y1g0bm3kp9140000gp/T/pip-req-build-8g5oafk2
  Created wheel for Theano: filename=Theano-1.0.4+21.g8f510a1f0-cp36-none-any.whl size=2666379 sha256=041cb3a9e761cab5d820669c49be2cb71215f819b38d3ca8810aee93f4551093
  Stored in directory: /private/var/folders/xv/6xdsnhm10jg5y1g0bm3kp9140000gp/T/pip-ephem-wheel-cache-pri53nb7/wheels/ae/32/7c/62beb8371953eb20c271b3bac7d0e56e1a2020d46994346b52
Successfully built Theano
  Found existing installation: Theano 1.0.4+21.g8f510a1f0
    Uninstalling Theano-1.0.4+21.g8f510a1f0:
      Successfully uninstalled Theano-1.0.4+21.g8f510a1f0
  Using cached https://files.pythonhosted.org/packages/27/8c/7608ba709bd536bc2bccb0d1abbb70aafe9cf7e0170353b4b720ed54cb71/tensorflow-1.14.0-cp36-cp36m-macosx_10_11_x86_64.whl
  Using cached http

# Parte 1 - Preprocessamento dos Dados

### Importar as libs

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Importar o dataset

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


### Transformando os dados categóricos


In [4]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer([("Geography", OneHotEncoder(), [1])], remainder = 'passthrough')
X = ct.fit_transform(X)

labelencoder_X = LabelEncoder()
X[:, 2] = labelencoder_X.fit_transform(X[:, 2])

X = X[:, 1:]

print("X >>\n",X)

X >>
 [[0.0 0 619 ... 1 1 101348.88]
 [0.0 1 608 ... 0 1 112542.58]
 [0.0 0 502 ... 1 0 113931.57]
 ...
 [0.0 0 709 ... 0 1 42085.58]
 [1.0 0 772 ... 1 0 92888.52]
 [0.0 0 792 ... 1 0 38190.78]]


# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

---
# Parte 2 -Vamos construir uma ANN!

## Importando o Keras


In [7]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [21]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'softsign', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Resultado:
Alterando o 'relu' na primeira camada pelo 'softsign' a acurácia aumentou de 83% para 86%

# Ajustando a ANN ao conjunto de treinamento

In [22]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4926 - accuracy: 0.7955
Epoch 2/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4285 - accuracy: 0.7945
Epoch 3/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4244 - accuracy: 0.8008
Epoch 4/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4137 - accuracy: 0.8120
Epoch 5/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3922 - accuracy: 0.8295
Epoch 6/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3728 - accuracy: 0.8388
Epoch 7/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3633 - accuracy: 0.8407
Epoch 8/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3577 - accuracy: 0.8485
Epoch 9/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3539 - accuracy: 0.8526
Epoch 10/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3498 - accura

800/800 [==============================] - 1s 1ms/step - loss: 0.3319 - accuracy: 0.8660
Epoch 82/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3323 - accuracy: 0.8654
Epoch 83/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3315 - accuracy: 0.8635
Epoch 84/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3317 - accuracy: 0.8665
Epoch 85/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3314 - accuracy: 0.8651
Epoch 86/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3318 - accuracy: 0.8658
Epoch 87/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3316 - accuracy: 0.8646
Epoch 88/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3314 - accuracy: 0.8655
Epoch 89/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3320 - accuracy: 0.8630
Epoch 90/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3318 - accuracy: 

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [23]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Criando uma Confusion Matrix

In [24]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1516   79]
 [ 202  203]]


# Initiate activation function experimentation

# Initialising the 2nd ANN

In [26]:
del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'softsign', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'tanh'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 2/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 4/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 5/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 6/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 7/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 8/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 9/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 10/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accura

800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 82/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 83/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 84/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 85/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 86/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 87/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 88/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 89/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 90/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 

In [27]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix

In [29]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1595    0]
 [ 405    0]]


# Initialising the 3rd ANN

In [30]:
del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 1s 1ms/step - loss: 0.5139 - accuracy: 0.7935
Epoch 2/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4452 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4335 - accuracy: 0.7956
Epoch 4/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4294 - accuracy: 0.7975
Epoch 5/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4278 - accuracy: 0.8014
Epoch 6/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4275 - accuracy: 0.8018
Epoch 7/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4274 - accuracy: 0.8024
Epoch 8/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4273 - accuracy: 0.8020
Epoch 9/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4273 - accuracy: 0.8025
Epoch 10/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4273 - accura

800/800 [==============================] - 1s 1ms/step - loss: 0.3959 - accuracy: 0.8356
Epoch 82/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3956 - accuracy: 0.8359
Epoch 83/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3955 - accuracy: 0.8355
Epoch 84/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3952 - accuracy: 0.8359
Epoch 85/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3952 - accuracy: 0.8354
Epoch 86/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3949 - accuracy: 0.8350
Epoch 87/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3947 - accuracy: 0.8346
Epoch 88/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3945 - accuracy: 0.8351
Epoch 89/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3945 - accuracy: 0.8364
Epoch 90/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3944 - accuracy: 

In [31]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix

In [32]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1551   44]
 [ 260  145]]


---
# Parte 4 - Evaluating, Improving and Tuning the ANN

## Evaluating the ANN

In [ ]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()
print("accuracies:%s\nmean:%s\nvariance:%s".format(accuracies, mean, variance))

# Improving the ANN
# Dropout Regularization to reduce overfitting if needed

In [ ]:
from keras.layers import Dropout

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()

# Tuning the ANN

In [ ]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense

def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier)

In [ ]:
parameters = {'batch_size': [10, 24, 32],
              'epochs': [50, 100, 200],
              'optimizer': ['adam', 'rmsprop']}

grid_search = GridSearchCV(estimator = classifier,
                           scoring = 'accuracy',
                           param_grid = parameters,
                           cv = 10)

grid_search = grid_search.fit(X_train, y_train)

best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)