In [ ]:
# Artificial Neural Network

# Installing Theano
# pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
# pip install tensorflow

# Installing Keras
# pip install --upgrade keras

# Part 1 - Data Preprocessing

In [ ]:
!pip install -r requirements.txt

In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [3]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

/home/igor/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/igor/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [4]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [5]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [6]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [7]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.


In [8]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
8000/8000 [==============================] - 2s 299us/step - loss: 0.4802 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 96us/step - loss: 0.4263 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 95us/step - loss: 0.4204 - acc: 0.8019
Epoch 4/100
8000/8000 [==============================] - 1s 99us/step - loss: 0.4172 - acc: 0.8232
Epoch 5/100
8000/8000 [==============================] - 1s 100us/step - loss: 0.4156 - acc: 0.8277
Epoch 6/100
8000/8000 [==============================] - 1s 100us/step - loss: 0.4141 - acc: 0.8299
Epoch 7/100
8000/8000 [==============================] - 1s 139us/step - loss: 0.4129 - acc: 0.8314
Epoch 8/100
8000/8000 [==============================] - 1s 101us/step - loss: 0.4117 - acc: 0.8327
Epoch 9/100
8000/8000 [==============================] - 1s 114us/step - loss: 0.4103 - acc: 0.8325
Epoch 10/100
8000/8000 [==============================]

8000/8000 [==============================] - 1s 72us/step - loss: 0.3946 - acc: 0.8355
Epoch 80/100
8000/8000 [==============================] - 1s 89us/step - loss: 0.3940 - acc: 0.8357
Epoch 81/100
8000/8000 [==============================] - 1s 84us/step - loss: 0.3943 - acc: 0.8367
Epoch 82/100
8000/8000 [==============================] - 1s 88us/step - loss: 0.3942 - acc: 0.8379
Epoch 83/100
8000/8000 [==============================] - 1s 94us/step - loss: 0.3943 - acc: 0.8379
Epoch 84/100
8000/8000 [==============================] - 1s 80us/step - loss: 0.3937 - acc: 0.8371
Epoch 85/100
8000/8000 [==============================] - 1s 100us/step - loss: 0.3944 - acc: 0.8370
Epoch 86/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.3943 - acc: 0.8364
Epoch 87/100
8000/8000 [==============================] - 1s 84us/step - loss: 0.3943 - acc: 0.8360
Epoch 88/100
8000/8000 [==============================] - 1s 77us/step - loss: 0.3944 - acc: 0.8360
Epoch 89/10

In [9]:

# Part 3 - Making predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [10]:
print(cm)

[[1548   47]
 [ 266  139]]


In [23]:
# Initialising the second ANN
classifier2 = Sequential()

# Adding the input layer and the first hidden layer
classifier2.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'tanh', input_dim = 11))

# Adding the second hidden layer
classifier2.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier2.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'hard_sigmoid'))

# Compiling the ANN
classifier2.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [24]:
# Fitting the ANN to the Training set
classifier2.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 1s 156us/step - loss: 0.5068 - acc: 0.7954
Epoch 2/100
8000/8000 [==============================] - 1s 133us/step - loss: 0.4331 - acc: 0.7999
Epoch 3/100
8000/8000 [==============================] - 1s 112us/step - loss: 0.4373 - acc: 0.8079
Epoch 4/100
8000/8000 [==============================] - 1s 114us/step - loss: 0.4330 - acc: 0.8066
Epoch 5/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.4275 - acc: 0.8102
Epoch 6/100
8000/8000 [==============================] - 1s 112us/step - loss: 0.4270 - acc: 0.8131
Epoch 7/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.4272 - acc: 0.8147
Epoch 8/100
8000/8000 [==============================] - 1s 121us/step - loss: 0.4208 - acc: 0.8165
Epoch 9/100
8000/8000 [==============================] - 1s 131us/step - loss: 0.4186 - acc: 0.8225
Epoch 10/100
8000/8000 [==============================] - 1s 164us/step - loss: 0.4099 - acc: 0.8294

8000/8000 [==============================] - 1s 100us/step - loss: 0.3344 - acc: 0.8625
Epoch 83/100
8000/8000 [==============================] - 1s 108us/step - loss: 0.3340 - acc: 0.8632
Epoch 84/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.3355 - acc: 0.8640
Epoch 85/100
8000/8000 [==============================] - 1s 100us/step - loss: 0.3351 - acc: 0.8639
Epoch 86/100
8000/8000 [==============================] - 1s 102us/step - loss: 0.3384 - acc: 0.8634
Epoch 87/100
8000/8000 [==============================] - 1s 119us/step - loss: 0.3410 - acc: 0.8609
Epoch 88/100
8000/8000 [==============================] - 1s 116us/step - loss: 0.3361 - acc: 0.8634
Epoch 89/100
8000/8000 [==============================] - 1s 104us/step - loss: 0.3349 - acc: 0.8625
Epoch 90/100
8000/8000 [==============================] - 1s 124us/step - loss: 0.3373 - acc: 0.8620
Epoch 91/100
8000/8000 [==============================] - 1s 104us/step - loss: 0.3342 - acc: 0.8627
Epo

In [25]:
# Part 3 - Making predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier2.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm2 = confusion_matrix(y_test, y_pred)

In [18]:
# Result with activations (tanh, tanh, hard_sigmoid)
print(cm2)

[[1517   78]
 [ 188  217]]


In [22]:
# Result with activations (relu, tanh, hard_sigmoid)
print(cm2)

[[1526   69]
 [ 202  203]]


In [26]:
# Result with activations (tanh, relu, hard_sigmoid)
print(cm2)

[[1518   77]
 [ 202  203]]
