In [1]:
# Artificial Neural Network

# Installing Theano
# pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
# pip install tensorflow

# Installing Keras
# pip install --upgrade keras

# Part 1 - Data Preprocessing

In [1]:
!pip install -r requirements.txt

  Using cached https://files.pythonhosted.org/packages/93/0e/30aaa357c3065957344b240482818eef31d4080f73dfa5f1ef7dcd8744d2/numpy-1.16.2-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
  Using cached https://files.pythonhosted.org/packages/82/7e/184d995d711e3401722769cd6982b46d42aee14a82ba54a3a79425f939c9/matplotlib-3.0.3-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
  Stored in directory: /Users/thiagolima/Library/Caches/pip/wheels/76/03/bb/589d421d27431bcd2c6da284d5f2286c8e3b2ea3cf1594c074
Successfully built sklearn
  Found existing installation: numpy 1.16.3
    Uninstalling numpy-1.16.3:
      Successfully uninstalled numpy-1.16.3
  Found existing installation: matplotlib 3.1.0
    Uninstalling matplotlib-3.1.0:
      Successfully uninstalled matplotlib-3.1.0


In [2]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [4]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

/Users/thiagolima/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:414: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/Users/thiagolima/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:450: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [5]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [6]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [27]:
from sklearn.metrics import confusion_matrix

# Ann prediction
def prediction(act1, act2, act3):
    """Predict and evaluate models based 3 activation functions"""
    # Initialising the ANN
    classifier = Sequential()

    # Adding the input layer and the first hidden layer
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = act1, input_dim = 11))

    # Adding the second hidden layer
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = act2))

    # Adding the output layer
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = act3))

    # Compiling the ANN
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    
    # Fitting the ANN to the Training set
    classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)
    
    # Part 3 - Making predictions and evaluating the model

    # Predicting the Test set results
    y_pred = classifier.predict(X_test)
    y_pred = (y_pred > 0.5)

    # Making the Confusion Matrix
    cm = confusion_matrix(y_test, y_pred)
    #print(cm)
    return cm
    

## Evaluate functions

In [31]:
relu_relu_sig = prediction('relu', 'relu', 'sigmoid')

Epoch 1/100
8000/8000 [==============================] - 3s 401us/step - loss: 0.5027 - acc: 0.7952
Epoch 2/100
8000/8000 [==============================] - 1s 164us/step - loss: 0.4286 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 250us/step - loss: 0.4222 - acc: 0.8024
Epoch 4/100
8000/8000 [==============================] - 2s 198us/step - loss: 0.4158 - acc: 0.8312
Epoch 5/100
8000/8000 [==============================] - 1s 133us/step - loss: 0.4111 - acc: 0.8297
Epoch 6/100
8000/8000 [==============================] - 1s 153us/step - loss: 0.4078 - acc: 0.8336
Epoch 7/100
8000/8000 [==============================] - 1s 134us/step - loss: 0.4058 - acc: 0.8345
Epoch 8/100
8000/8000 [==============================] - 1s 135us/step - loss: 0.4037 - acc: 0.8350
Epoch 9/100
8000/8000 [==============================] - 1s 132us/step - loss: 0.4021 - acc: 0.8362
Epoch 10/100
8000/8000 [==============================] - 1s 132us/step - loss: 0.4010 - acc: 0.8352

8000/8000 [==============================] - 1s 163us/step - loss: 0.3436 - acc: 0.8625
Epoch 83/100
8000/8000 [==============================] - 1s 158us/step - loss: 0.3440 - acc: 0.8619
Epoch 84/100
8000/8000 [==============================] - 1s 157us/step - loss: 0.3437 - acc: 0.8625
Epoch 85/100
8000/8000 [==============================] - 1s 151us/step - loss: 0.3430 - acc: 0.8634
Epoch 86/100
8000/8000 [==============================] - 1s 180us/step - loss: 0.3431 - acc: 0.8626
Epoch 87/100
8000/8000 [==============================] - 1s 155us/step - loss: 0.3427 - acc: 0.8636
Epoch 88/100
8000/8000 [==============================] - 1s 153us/step - loss: 0.3422 - acc: 0.8632
Epoch 89/100
8000/8000 [==============================] - 1s 152us/step - loss: 0.3425 - acc: 0.8624
Epoch 90/100
8000/8000 [==============================] - 1s 153us/step - loss: 0.3427 - acc: 0.8635
Epoch 91/100
8000/8000 [==============================] - 1s 154us/step - loss: 0.3420 - acc: 0.8617
Epo

In [28]:
sig_sig_tanh = prediction('sigmoid', 'sigmoid', 'tanh')

Epoch 1/100
8000/8000 [==============================] - 2s 254us/step - loss: 3.2881 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 175us/step - loss: 3.2881 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 170us/step - loss: 3.2881 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 2s 269us/step - loss: 3.2881 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 2s 223us/step - loss: 3.2881 - acc: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 172us/step - loss: 3.2881 - acc: 0.7960
Epoch 7/100
8000/8000 [==============================] - 2s 189us/step - loss: 3.2881 - acc: 0.7960
Epoch 8/100
8000/8000 [==============================] - 1s 177us/step - loss: 3.2881 - acc: 0.7960
Epoch 9/100
8000/8000 [==============================] - 2s 213us/step - loss: 3.2881 - acc: 0.7960
Epoch 10/100
8000/8000 [==============================] - 1s 180us/step - loss: 3.2881 - acc: 0.7960

8000/8000 [==============================] - 1s 162us/step - loss: 3.2881 - acc: 0.7960
Epoch 82/100
8000/8000 [==============================] - 2s 208us/step - loss: 3.2881 - acc: 0.7960
Epoch 83/100
8000/8000 [==============================] - 2s 239us/step - loss: 3.2881 - acc: 0.7960
Epoch 84/100
8000/8000 [==============================] - 2s 217us/step - loss: 3.2881 - acc: 0.7960
Epoch 85/100
8000/8000 [==============================] - 1s 161us/step - loss: 3.2881 - acc: 0.7960
Epoch 86/100
8000/8000 [==============================] - 1s 165us/step - loss: 3.2881 - acc: 0.7960
Epoch 87/100
8000/8000 [==============================] - 1s 164us/step - loss: 3.2881 - acc: 0.7960
Epoch 88/100
8000/8000 [==============================] - 1s 160us/step - loss: 3.2881 - acc: 0.7960
Epoch 89/100
8000/8000 [==============================] - 1s 165us/step - loss: 3.2881 - acc: 0.7960
Epoch 90/100
8000/8000 [==============================] - 1s 160us/step - loss: 3.2881 - acc: 0.7960
Epo

In [32]:
sig_relu_sig = prediction('sigmoid', 'relu', 'sigmoid')

Epoch 1/100
8000/8000 [==============================] - 2s 256us/step - loss: 0.5145 - acc: 0.7950
Epoch 2/100
8000/8000 [==============================] - 1s 171us/step - loss: 0.4459 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 174us/step - loss: 0.4338 - acc: 0.7961
Epoch 4/100
8000/8000 [==============================] - 1s 175us/step - loss: 0.4295 - acc: 0.7975
Epoch 5/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.4279 - acc: 0.8015
Epoch 6/100
8000/8000 [==============================] - 1s 173us/step - loss: 0.4277 - acc: 0.8027
Epoch 7/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.4271 - acc: 0.8030
Epoch 8/100
8000/8000 [==============================] - 2s 214us/step - loss: 0.4271 - acc: 0.8036
Epoch 9/100
8000/8000 [==============================] - 1s 178us/step - loss: 0.4269 - acc: 0.8041
Epoch 10/100
8000/8000 [==============================] - 1s 176us/step - loss: 0.4265 - acc: 0.8050

8000/8000 [==============================] - 2s 209us/step - loss: 0.3958 - acc: 0.8371
Epoch 82/100
8000/8000 [==============================] - 1s 180us/step - loss: 0.3960 - acc: 0.8364
Epoch 83/100
8000/8000 [==============================] - 1s 183us/step - loss: 0.3953 - acc: 0.8376
Epoch 84/100
8000/8000 [==============================] - 1s 176us/step - loss: 0.3956 - acc: 0.8356
Epoch 85/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.3956 - acc: 0.8366
Epoch 86/100
8000/8000 [==============================] - 1s 178us/step - loss: 0.3954 - acc: 0.8379
Epoch 87/100
8000/8000 [==============================] - 2s 199us/step - loss: 0.3954 - acc: 0.8367
Epoch 88/100
8000/8000 [==============================] - 2s 205us/step - loss: 0.3952 - acc: 0.8370
Epoch 89/100
8000/8000 [==============================] - 1s 183us/step - loss: 0.3951 - acc: 0.8356
Epoch 90/100
8000/8000 [==============================] - 1s 181us/step - loss: 0.3949 - acc: 0.8369
Epo

In [33]:
tanh_tanh_relu = prediction('tanh', 'tanh', 'relu')

Epoch 1/100
8000/8000 [==============================] - 2s 300us/step - loss: 3.2881 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 2s 200us/step - loss: 3.2881 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 200us/step - loss: 3.2881 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 2s 198us/step - loss: 3.2881 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 2s 201us/step - loss: 3.2881 - acc: 0.7960
Epoch 6/100
8000/8000 [==============================] - 2s 200us/step - loss: 3.2881 - acc: 0.7960
Epoch 7/100
8000/8000 [==============================] - 2s 207us/step - loss: 3.2881 - acc: 0.7960
Epoch 8/100
8000/8000 [==============================] - 2s 237us/step - loss: 3.2881 - acc: 0.7960
Epoch 9/100
8000/8000 [==============================] - 2s 196us/step - loss: 3.2881 - acc: 0.7960
Epoch 10/100
8000/8000 [==============================] - 2s 192us/step - loss: 3.2881 - acc: 0.7960

8000/8000 [==============================] - 1s 154us/step - loss: 3.2881 - acc: 0.7960
Epoch 82/100
8000/8000 [==============================] - 1s 156us/step - loss: 3.2881 - acc: 0.7960
Epoch 83/100
8000/8000 [==============================] - 1s 168us/step - loss: 3.2881 - acc: 0.7960
Epoch 84/100
8000/8000 [==============================] - 2s 188us/step - loss: 3.2881 - acc: 0.7960
Epoch 85/100
8000/8000 [==============================] - 1s 153us/step - loss: 3.2881 - acc: 0.7960
Epoch 86/100
8000/8000 [==============================] - 1s 177us/step - loss: 3.2881 - acc: 0.7960
Epoch 87/100
8000/8000 [==============================] - 1s 159us/step - loss: 3.2881 - acc: 0.7960
Epoch 88/100
8000/8000 [==============================] - 1s 163us/step - loss: 3.2881 - acc: 0.7960
Epoch 89/100
8000/8000 [==============================] - 2s 212us/step - loss: 3.2881 - acc: 0.7960
Epoch 90/100
8000/8000 [==============================] - 1s 171us/step - loss: 3.2881 - acc: 0.7960
Epo

In [34]:
sig_sig_relu = prediction('sigmoid', 'sigmoid', 'relu')

Epoch 1/100
8000/8000 [==============================] - 2s 239us/step - loss: 0.5100 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 147us/step - loss: 0.4832 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 143us/step - loss: 0.4455 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 147us/step - loss: 0.4336 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 1s 148us/step - loss: 0.4311 - acc: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 149us/step - loss: 0.4308 - acc: 0.7960
Epoch 7/100
8000/8000 [==============================] - 1s 145us/step - loss: 0.4300 - acc: 0.7969
Epoch 8/100
8000/8000 [==============================] - 1s 158us/step - loss: 0.4292 - acc: 0.7951
Epoch 9/100
8000/8000 [==============================] - 1s 179us/step - loss: 0.4295 - acc: 0.7954
Epoch 10/100
8000/8000 [==============================] - 3s 437us/step - loss: 0.4291 - acc: 0.7956

8000/8000 [==============================] - 1s 147us/step - loss: 0.3561 - acc: 0.8529
Epoch 83/100
8000/8000 [==============================] - 1s 161us/step - loss: 0.3558 - acc: 0.8527
Epoch 84/100
8000/8000 [==============================] - 2s 217us/step - loss: 0.3595 - acc: 0.8531
Epoch 85/100
8000/8000 [==============================] - 2s 248us/step - loss: 0.3726 - acc: 0.8491
Epoch 86/100
8000/8000 [==============================] - 2s 287us/step - loss: 0.4134 - acc: 0.8427
Epoch 87/100
8000/8000 [==============================] - 3s 338us/step - loss: 0.3933 - acc: 0.8474
Epoch 88/100
8000/8000 [==============================] - 3s 314us/step - loss: 0.3811 - acc: 0.8494
Epoch 89/100
8000/8000 [==============================] - 2s 286us/step - loss: 0.3693 - acc: 0.8519
Epoch 90/100
8000/8000 [==============================] - 2s 224us/step - loss: 0.3604 - acc: 0.8527
Epoch 91/100
8000/8000 [==============================] - 1s 182us/step - loss: 0.3574 - acc: 0.8530
Epo

## Ann comparation

In [36]:
print("\nrelu, relu, sigmoid")
print(relu_relu_sig)

print("\nsigmoid, sigmoid, tanh")
print(sig_sig_tanh)

print("\nsigmoid, relu, sigmoid")
print(sig_relu_sig)
      
print("\ntanh, tanh, relu")
print(tanh_tanh_relu)
      
print("\nsigmoid, sigmoid, relu")
print(sig_sig_relu)


relu, relu, sigmoid
[[1503   92]
 [ 187  218]]

sigmoid, sigmoid, tanh
[[1595    0]
 [ 405    0]]

sigmoid, relu, sigmoid
[[1551   44]
 [ 268  137]]

tanh, tanh, relu
[[1595    0]
 [ 405    0]]

sigmoid, sigmoid, relu
[[1529   66]
 [ 215  190]]


In [8]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

W0701 16:42:07.561146 4645553600 deprecation_wrapper.py:119] From /Users/thiagolima/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0701 16:42:07.580023 4645553600 deprecation_wrapper.py:119] From /Users/thiagolima/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0701 16:42:07.582029 4645553600 deprecation_wrapper.py:119] From /Users/thiagolima/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0701 16:42:07.681150 4645553600 deprecation_wrapper.py:119] From /Users/thiagolima/anaconda3/lib/python3.6/site-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0701 16

In [9]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

W0701 16:42:09.121665 4645553600 deprecation_wrapper.py:119] From /Users/thiagolima/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/100
8000/8000 [==============================] - 1s 152us/step - loss: 0.4760 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 122us/step - loss: 0.4275 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 125us/step - loss: 0.4218 - acc: 0.8020
Epoch 4/100
8000/8000 [==============================] - 1s 120us/step - loss: 0.4184 - acc: 0.8245
Epoch 5/100
8000/8000 [==============================] - 1s 138us/step - loss: 0.4156 - acc: 0.8282
Epoch 6/100
8000/8000 [==============================] - 1s 161us/step - loss: 0.4142 - acc: 0.8300
Epoch 7/100
8000/8000 [==============================] - 1s 185us/step - loss: 0.4132 - acc: 0.8314
Epoch 8/100
8000/8000 [==============================] - 2s 208us/step - loss: 0.4121 - acc: 0.8316
Epoch 9/100
8000/8000 [==============================] - 1s 136us/step - loss: 0.4105 - acc: 0.8334
Epoch 10/100
8000/8000 [==============================] - 1s 144us/step - loss: 0.4100 - acc: 0.8336

8000/8000 [==============================] - 2s 205us/step - loss: 0.4004 - acc: 0.8351
Epoch 82/100
8000/8000 [==============================] - 2s 191us/step - loss: 0.4006 - acc: 0.8349
Epoch 83/100
8000/8000 [==============================] - 1s 137us/step - loss: 0.4006 - acc: 0.8337
Epoch 84/100
8000/8000 [==============================] - 1s 137us/step - loss: 0.4007 - acc: 0.8342
Epoch 85/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.4003 - acc: 0.8345
Epoch 86/100
8000/8000 [==============================] - 1s 109us/step - loss: 0.4007 - acc: 0.8355
Epoch 87/100
8000/8000 [==============================] - 1s 135us/step - loss: 0.4005 - acc: 0.8352
Epoch 88/100
8000/8000 [==============================] - 1s 100us/step - loss: 0.4008 - acc: 0.8342
Epoch 89/100
8000/8000 [==============================] - 1s 167us/step - loss: 0.4007 - acc: 0.8347
Epoch 90/100
8000/8000 [==============================] - 1s 153us/step - loss: 0.4008 - acc: 0.8359
Epo

In [10]:
# Part 3 - Making predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1547   48]
 [ 265  140]]


In [12]:
# Initiate activation function experimentation

# Initialising the 2nd ANN

del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'tanh'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 4s 551us/step - loss: 0.5026 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 4s 522us/step - loss: 0.4681 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 4s 516us/step - loss: 0.4359 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 4s 511us/step - loss: 0.4320 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 4s 525us/step - loss: 0.4311 - acc: 0.7956
Epoch 6/100
8000/8000 [==============================] - 4s 524us/step - loss: 0.4313 - acc: 0.7957
Epoch 7/100
8000/8000 [==============================] - 4s 527us/step - loss: 0.4294 - acc: 0.7951
Epoch 8/100
8000/8000 [==============================] - 4s 512us/step - loss: 0.4291 - acc: 0.7959 1s - loss: 0.4396 - 
Epoch 9/100
8000/8000 [==============================] - 4s 535us/step - loss: 0.4284 - acc: 0.7979
Epoch 10/100
8000/8000 [==============================] - 4s 526us/step - loss:

In [11]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1547   48]
 [ 265  140]]


> Outstanding result... is that?

In [12]:
# Initialising the 3rd ANN

del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 1s 160us/step - loss: 0.5235 - acc: 0.7945
Epoch 2/100
8000/8000 [==============================] - 1s 128us/step - loss: 0.4488 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 133us/step - loss: 0.4367 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 176us/step - loss: 0.4310 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 1s 127us/step - loss: 0.4286 - acc: 0.7976
Epoch 6/100
8000/8000 [==============================] - 1s 161us/step - loss: 0.4279 - acc: 0.7981
Epoch 7/100
8000/8000 [==============================] - 1s 186us/step - loss: 0.4275 - acc: 0.8000
Epoch 8/100
8000/8000 [==============================] - 1s 126us/step - loss: 0.4273 - acc: 0.8015
Epoch 9/100
8000/8000 [==============================] - 1s 140us/step - loss: 0.4272 - acc: 0.8034
Epoch 10/100
8000/8000 [==============================] - 1s 125us/step - loss: 0.4269 - acc: 0.8034

8000/8000 [==============================] - 1s 146us/step - loss: 0.3606 - acc: 0.8492
Epoch 82/100
8000/8000 [==============================] - 1s 135us/step - loss: 0.3594 - acc: 0.8497
Epoch 83/100
8000/8000 [==============================] - 2s 206us/step - loss: 0.3580 - acc: 0.8507
Epoch 84/100
8000/8000 [==============================] - 2s 188us/step - loss: 0.3570 - acc: 0.8522
Epoch 85/100
8000/8000 [==============================] - 1s 145us/step - loss: 0.3555 - acc: 0.8520
Epoch 86/100
8000/8000 [==============================] - 1s 166us/step - loss: 0.3542 - acc: 0.8541
Epoch 87/100
8000/8000 [==============================] - 1s 139us/step - loss: 0.3527 - acc: 0.8547
Epoch 88/100
8000/8000 [==============================] - 1s 112us/step - loss: 0.3520 - acc: 0.8546
Epoch 89/100
8000/8000 [==============================] - 1s 133us/step - loss: 0.3506 - acc: 0.8559
Epoch 90/100
8000/8000 [==============================] - 1s 159us/step - loss: 0.3498 - acc: 0.8551
Epo

In [14]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1523   72]
 [ 205  200]]


In [37]:
# Part 4 - Evaluating, Improving and Tuning the ANN

# Evaluating the ANN
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense
#from keras.layers import Dropout
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()


KeyboardInterrupt: 

In [ ]:
# Improving the ANN
# Dropout Regularization to reduce overfitting if needed
from keras.layers import Dropout

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()


In [ ]:
# Tuning the ANN
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense

def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier)

In [ ]:
parameters = {'batch_size': [10, 25, 32],
              'epochs': [100, 500],
              'optimizer': ['adam', 'rmsprop']}

grid_search = GridSearchCV(estimator = classifier,
                           scoring = 'accuracy',
                           param_grid = parameters,
                           cv = 10)

grid_search = grid_search.fit(X_train, y_train)

best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_