# REDES NEURAIS ARTIFICIAIS

[Aula 3 de Deep Learning](http://bit.ly/dn-unb03) da Engenharia de Software da UnB

In [1]:
# Installing Theano
# ! pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
! pip install --upgrade tensorflow

# Installing Keras
! pip install --upgrade keras

# Install other packages
! pip install --upgrade pip pandas numpy matplotlib sklearn

Defaulting to user installation because normal site-packages is not writeable
  Using cached tensorflow-2.3.1-cp36-cp36m-manylinux2010_x86_64.whl (320.4 MB)
  Using cached tensorflow_estimator-2.3.0-py2.py3-none-any.whl (459 kB)
     |████████████████████████████████| 20.1 MB 4.5 kB/s eta 0:00:01
  Using cached tensorboard-2.3.0-py3-none-any.whl (6.8 MB)
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 1.13.0
    Uninstalling tensorflow-estimator-1.13.0:
      Successfully uninstalled tensorflow-estimator-1.13.0
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.2
    Uninstalling numpy-1.19.2:
      Successfully uninstalled numpy-1.19.2
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 1.13.1
    Uninstalling tensorboard-1.13.1:
      Successfully uninstalled tensorboard-1.13.1
  Attempting uninstall: tensorflow
    Found existing installation: tensorflow 1.13.1
    Uninstalling ten

  Attempting uninstall: numpy
    Found existing installation: numpy 1.18.5
    Uninstalling numpy-1.18.5:
      Successfully uninstalled numpy-1.18.5
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

tensorflow 2.3.1 requires numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.2 which is incompatible.


# Parte 1 - Preprocessamento dos Dados

### Importar as libs

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Importar o dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


### Transformando os dados categóricos


In [5]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
columnTransformer = ColumnTransformer(transformers=[("OneHot", OneHotEncoder(), [1])],
                                      remainder="passthrough")

X = columnTransformer.fit_transform(X.tolist())
X = X.astype("float64")
X = X[:, 1:]
print("X >>\n",X)

X >>
 [[0.0000000e+00 0.0000000e+00 6.1900000e+02 ... 1.0000000e+00
  1.0000000e+00 1.0134888e+05]
 [0.0000000e+00 1.0000000e+00 6.0800000e+02 ... 0.0000000e+00
  1.0000000e+00 1.1254258e+05]
 [0.0000000e+00 0.0000000e+00 5.0200000e+02 ... 1.0000000e+00
  0.0000000e+00 1.1393157e+05]
 ...
 [0.0000000e+00 0.0000000e+00 7.0900000e+02 ... 0.0000000e+00
  1.0000000e+00 4.2085580e+04]
 [1.0000000e+00 0.0000000e+00 7.7200000e+02 ... 1.0000000e+00
  0.0000000e+00 9.2888520e+04]
 [0.0000000e+00 0.0000000e+00 7.9200000e+02 ... 1.0000000e+00
  0.0000000e+00 3.8190780e+04]]


# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

---
# Parte 2 -Vamos construir uma ANN!

## Importando o Keras


In [8]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [9]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 10, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'tanh'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Ajustando a ANN ao conjunto de treinamento

In [10]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 2/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 4/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 5/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 6/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 7/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 8/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 9/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 10/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accura

800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 82/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 83/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 84/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 85/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 86/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 87/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 88/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 89/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 90/100
800/800 [==============================] - 1s 1ms/step - loss: 3.1467 - accuracy: 

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [11]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Criando uma Confusion Matrix

In [12]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print('-'*30)
print("Confusion matrix")
print(cm)
print(f"Hit = {cm[0][0] + cm[1][1]} ({round(((cm[0][0] + cm[1][1]) / np.sum(cm))*100, 2)}%)")
print(f"Miss = {cm[0][1] + cm[1][0]} ({round(((cm[0][1] + cm[1][0]) / np.sum(cm))*100, 2)}%)")
print(f"Total = {np.sum(cm)}") 

------------------------------
Confusion matrix
[[1595    0]
 [ 405    0]]
Hit = 1595 (79.75%)
Miss = 405 (20.25%)
Total = 2000


# Initiate activation function experimentation

# Initialising the 2nd ANN

In [13]:
del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'tanh'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 1s 1ms/step - loss: 0.5154 - accuracy: 0.7960
Epoch 2/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4860 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4554 - accuracy: 0.7960
Epoch 4/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4378 - accuracy: 0.7960
Epoch 5/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4321 - accuracy: 0.7960
Epoch 6/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4313 - accuracy: 0.7960
Epoch 7/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4297 - accuracy: 0.7960
Epoch 8/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4303 - accuracy: 0.7960
Epoch 9/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4295 - accuracy: 0.7956
Epoch 10/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4289 - accura

800/800 [==============================] - 1s 1ms/step - loss: 0.3475 - accuracy: 0.8574
Epoch 82/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3473 - accuracy: 0.8572
Epoch 83/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3500 - accuracy: 0.8575
Epoch 84/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3488 - accuracy: 0.8575
Epoch 85/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3582 - accuracy: 0.8585
Epoch 86/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3468 - accuracy: 0.8570
Epoch 87/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3494 - accuracy: 0.8564
Epoch 88/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3467 - accuracy: 0.8586
Epoch 89/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3541 - accuracy: 0.8574
Epoch 90/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3462 - accuracy: 

In [14]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix

In [15]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print('-'*30)
print("Confusion matrix")
print(cm)
print(f"Hit = {cm[0][0] + cm[1][1]} ({round(((cm[0][0] + cm[1][1]) / np.sum(cm))*100, 2)}%)")
print(f"Miss = {cm[0][1] + cm[1][0]} ({round(((cm[0][1] + cm[1][0]) / np.sum(cm))*100, 2)}%)")
print(f"Total = {np.sum(cm)}") 

------------------------------
Confusion matrix
[[1539   56]
 [ 213  192]]
Hit = 1731 (86.55%)
Miss = 269 (13.45%)
Total = 2000


# Initialising the 3rd ANN

In [16]:
del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 1s 1ms/step - loss: 0.5114 - accuracy: 0.7958
Epoch 2/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4462 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4340 - accuracy: 0.7964
Epoch 4/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4294 - accuracy: 0.7980
Epoch 5/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4281 - accuracy: 0.8016
Epoch 6/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4275 - accuracy: 0.8014
Epoch 7/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4272 - accuracy: 0.8049
Epoch 8/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4272 - accuracy: 0.8041
Epoch 9/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4271 - accuracy: 0.8050
Epoch 10/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4265 - accura

800/800 [==============================] - 1s 1ms/step - loss: 0.3960 - accuracy: 0.8365
Epoch 82/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3959 - accuracy: 0.8353
Epoch 83/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3957 - accuracy: 0.8353
Epoch 84/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3956 - accuracy: 0.8351
Epoch 85/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3956 - accuracy: 0.8360
Epoch 86/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3952 - accuracy: 0.8363
Epoch 87/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3952 - accuracy: 0.8365
Epoch 88/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3951 - accuracy: 0.8363
Epoch 89/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3949 - accuracy: 0.8364
Epoch 90/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3948 - accuracy: 

In [17]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix

In [18]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print('-'*30)
print("Confusion matrix")
print(cm)
print(f"Hit = {cm[0][0] + cm[1][1]} ({round(((cm[0][0] + cm[1][1]) / np.sum(cm))*100, 2)}%)")
print(f"Miss = {cm[0][1] + cm[1][0]} ({round(((cm[0][1] + cm[1][0]) / np.sum(cm))*100, 2)}%)")
print(f"Total = {np.sum(cm)}") 

------------------------------
Confusion matrix
[[1553   42]
 [ 266  139]]
Hit = 1692 (84.6%)
Miss = 308 (15.4%)
Total = 2000


---
# Parte 4 - Evaluating, Improving and Tuning the ANN

## Evaluating the ANN

In [ ]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()
print("accuracies:%s\nmean:%s\nvariance:%s".format(accuracies, mean, variance))

# Improving the ANN
# Dropout Regularization to reduce overfitting if needed

In [ ]:
from keras.layers import Dropout

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()

# Tuning the ANN

In [ ]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense

def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier)

In [ ]:
parameters = {'batch_size': [10, 24, 32],
              'epochs': [50, 100, 200],
              'optimizer': ['adam', 'rmsprop']}

grid_search = GridSearchCV(estimator = classifier,
                           scoring = 'accuracy',
                           param_grid = parameters,
                           cv = 10)

grid_search = grid_search.fit(X_train, y_train)

best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)