# REDES NEURAIS ARTIFICIAIS

[Aula 3 de Deep Learning](http://bit.ly/dn-unb03) da Engenharia de Software da UnB

In [1]:
# Installing Theano
! pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
! pip install --upgrade tensorflow

# Installing Keras
! pip install --upgrade keras

# Install other packages
! pip install --upgrade pip pandas numpy matplotlib sklearn

  Cloning git://github.com/Theano/Theano.git to /tmp/pip-req-build-aedxy6dl
  Running command git clone -q git://github.com/Theano/Theano.git /tmp/pip-req-build-aedxy6dl
  fatal: unable to connect to github.com:
  github.com[0: 140.82.113.3]: errno=Tempo esgotado para conexão

ERROR: Command errored out with exit status 128: git clone -q git://github.com/Theano/Theano.git /tmp/pip-req-build-aedxy6dl Check the logs for full command output.
     |████████▌                       | 22.9MB 404kB/s eta 0:02:37     |███████▊                        | 20.7MB 526kB/s eta 0:02:05^C

ERROR: Operation cancelled by user
     |████████████████████████████████| 378kB 480kB/s eta 0:00:01
  Found existing installation: Keras 2.2.4
    Uninstalling Keras-2.2.4:
      Successfully uninstalled Keras-2.2.4
Requirement already up-to-date: pip in /home/victorcmoura/.virtualenvs/deeplearning/lib/python3.7/site-packages (19.3.1)
  Using cached https://files.pythonhosted.org/packages/63/e0/a1b39cdcb2c391f087a153

# Parte 1 - Preprocessamento dos Dados

### Importar as libs

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Importar o dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


### Transformando os dados categóricos


In [4]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]
print("X >>\n",X)

X >>
 [[0.0000000e+00 0.0000000e+00 6.1900000e+02 ... 1.0000000e+00
  1.0000000e+00 1.0134888e+05]
 [0.0000000e+00 1.0000000e+00 6.0800000e+02 ... 0.0000000e+00
  1.0000000e+00 1.1254258e+05]
 [0.0000000e+00 0.0000000e+00 5.0200000e+02 ... 1.0000000e+00
  0.0000000e+00 1.1393157e+05]
 ...
 [0.0000000e+00 0.0000000e+00 7.0900000e+02 ... 0.0000000e+00
  1.0000000e+00 4.2085580e+04]
 [1.0000000e+00 0.0000000e+00 7.7200000e+02 ... 1.0000000e+00
  0.0000000e+00 9.2888520e+04]
 [0.0000000e+00 0.0000000e+00 7.9200000e+02 ... 1.0000000e+00
  0.0000000e+00 3.8190780e+04]]


/home/victorcmoura/.virtualenvs/deeplearning/local/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/victorcmoura/.virtualenvs/deeplearning/local/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

---
# Parte 2 -Vamos construir uma ANN!

## Importando o Keras


In [7]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.
/home/victorcmoura/.virtualenvs/deeplearning/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/victorcmoura/.virtualenvs/deeplearning/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/victorcmoura/.virtualenvs/deeplearning/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype

In [8]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.


# Ajustando a ANN ao conjunto de treinamento

In [9]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
8000/8000 [==============================] - 2s 218us/step - loss: 0.4816 - accuracy: 0.8023
Epoch 2/100
8000/8000 [==============================] - 2s 208us/step - loss: 0.4088 - accuracy: 0.8225
Epoch 3/100
8000/8000 [==============================] - 2s 201us/step - loss: 0.3969 - accuracy: 0.8256
Epoch 4/100
8000/8000 [==============================] - 2s 236us/step - loss: 0.3881 - accuracy: 0.8288
Epoch 5/100
8000/8000 [==============================] - 2s 230us/step - loss: 0.3811 - accuracy: 0.8306
Epoch 6/100
8000/8000 [==============================] - 2s 197us/step - loss: 0.3756 - accuracy: 0.8341
Epoch 7/100
8000/8000 [==============================] - 1s 183us/step - loss: 0.3726 - accuracy: 0.8449
Epoch 8/100
8000/8000 [==============================] - 2s 201us/step - loss: 0.3696 - accuracy: 0.8479
Epoch 9/100
8000/8000 [==============================] - 2s 188us/step - loss: 0.3661 - accuracy: 0.8496
Epoch 1

8000/8000 [==============================] - 1s 163us/step - loss: 0.3366 - accuracy: 0.8609
Epoch 76/100
8000/8000 [==============================] - 1s 168us/step - loss: 0.3374 - accuracy: 0.8606
Epoch 77/100
8000/8000 [==============================] - 1s 170us/step - loss: 0.3368 - accuracy: 0.8618
Epoch 78/100
8000/8000 [==============================] - 1s 170us/step - loss: 0.3371 - accuracy: 0.8605
Epoch 79/100
8000/8000 [==============================] - 1s 164us/step - loss: 0.3369 - accuracy: 0.8615
Epoch 80/100
8000/8000 [==============================] - 1s 168us/step - loss: 0.3366 - accuracy: 0.8605
Epoch 81/100
8000/8000 [==============================] - 1s 168us/step - loss: 0.3376 - accuracy: 0.8621
Epoch 82/100
8000/8000 [==============================] - 1s 170us/step - loss: 0.3358 - accuracy: 0.8631
Epoch 83/100
8000/8000 [==============================] - 1s 168us/step - loss: 0.3361 - accuracy: 0.8601
Epoch 84/100
8000/8000 [==============================] - 1

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [10]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Criando uma Confusion Matrix

In [11]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1523   72]
 [ 199  206]]


# Initiate activation function experimentation

# Initialising the 2nd ANN

In [12]:
del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'tanh'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 2s 253us/step - loss: 3.2881 - accuracy: 0.7960
Epoch 2/100
8000/8000 [==============================] - 2s 223us/step - loss: 3.2881 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 213us/step - loss: 3.2881 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 177us/step - loss: 3.2881 - accuracy: 0.7960
Epoch 5/100
8000/8000 [==============================] - 2s 198us/step - loss: 3.2881 - accuracy: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 172us/step - loss: 3.2881 - accuracy: 0.7960
Epoch 7/100
8000/8000 [==============================] - 1s 171us/step - loss: 3.2881 - accuracy: 0.7960
Epoch 8/100
8000/8000 [==============================] - 1s 170us/step - loss: 3.2881 - accuracy: 0.7960
Epoch 9/100
8000/8000 [==============================] - 1s 171us/step - loss: 3.2881 - accuracy: 0.7960
Epoch 10/100
8000/8000 [==============================]

8000/8000 [==============================] - 1s 177us/step - loss: 3.2881 - accuracy: 0.7960
Epoch 79/100
8000/8000 [==============================] - 1s 131us/step - loss: 3.2881 - accuracy: 0.7960
Epoch 80/100
8000/8000 [==============================] - 1s 126us/step - loss: 3.2881 - accuracy: 0.7960
Epoch 81/100
8000/8000 [==============================] - 1s 126us/step - loss: 3.2881 - accuracy: 0.7960
Epoch 82/100
8000/8000 [==============================] - 1s 126us/step - loss: 3.2881 - accuracy: 0.7960
Epoch 83/100
8000/8000 [==============================] - 1s 142us/step - loss: 3.2881 - accuracy: 0.7960
Epoch 84/100
8000/8000 [==============================] - 1s 153us/step - loss: 3.2881 - accuracy: 0.7960
Epoch 85/100
8000/8000 [==============================] - 1s 139us/step - loss: 3.2881 - accuracy: 0.7960
Epoch 86/100
8000/8000 [==============================] - 1s 138us/step - loss: 3.2881 - accuracy: 0.7960
Epoch 87/100
8000/8000 [==============================] - 1

In [13]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix

In [14]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1595    0]
 [ 405    0]]


# Initialising the 3rd ANN

In [ ]:
del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'relu'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 1s 116us/step - loss: 0.5807 - accuracy: 0.8008
Epoch 2/100
8000/8000 [==============================] - 1s 95us/step - loss: 0.4081 - accuracy: 0.8123
Epoch 3/100
8000/8000 [==============================] - 1s 97us/step - loss: 0.3989 - accuracy: 0.8183
Epoch 4/100
8000/8000 [==============================] - 1s 93us/step - loss: 0.3906 - accuracy: 0.8267
Epoch 5/100
8000/8000 [==============================] - 1s 95us/step - loss: 0.3843 - accuracy: 0.8345
Epoch 6/100
8000/8000 [==============================] - 1s 96us/step - loss: 0.3965 - accuracy: 0.8341
Epoch 7/100
8000/8000 [==============================] - 1s 97us/step - loss: 0.4706 - accuracy: 0.8199
Epoch 8/100
8000/8000 [==============================] - 1s 95us/step - loss: 0.4021 - accuracy: 0.8207
Epoch 9/100
8000/8000 [==============================] - 1s 98us/step - loss: 0.3966 - accuracy: 0.8236
Epoch 10/100
8000/8000 [==============================] - 1s 94

In [16]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix

In [17]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1511   84]
 [ 202  203]]


---
# Parte 4 - Evaluating, Improving and Tuning the ANN

## Evaluating the ANN

In [18]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()
print("accuracies:%s\nmean:%s\nvariance:%s".format(accuracies, mean, variance))

KeyboardInterrupt: 

# Improving the ANN
# Dropout Regularization to reduce overfitting if needed

In [ ]:
from keras.layers import Dropout

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()

# Tuning the ANN

In [ ]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense

def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier)

In [ ]:
parameters = {'batch_size': [10, 24, 32],
              'epochs': [50, 100, 200],
              'optimizer': ['adam', 'rmsprop']}

grid_search = GridSearchCV(estimator = classifier,
                           scoring = 'accuracy',
                           param_grid = parameters,
                           cv = 10)

grid_search = grid_search.fit(X_train, y_train)

best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)