# REDES NEURAIS ARTIFICIAIS

[Aula 3 de Deep Learning](http://bit.ly/dn-unb03) da Engenharia de Software da UnB

# Parte 1 - Pré-processamento dos Dados

### Importar as libs

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.2.0'

### Importar o dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


### Transformando os dados categóricos


In [5]:
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]
[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
np.shape(X_train)

(8000, 12)

---
# Parte 2 -Vamos construir uma ANN!


### Initializing the ANN

In [9]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(64, kernel_initializer='lecun_normal', activation='selu'))

In [11]:
#ann.add(tf.keras.layers.Dense(units=12, activation='relu'))

### Adding the second hidden layer

In [12]:
#ann.add(tf.keras.layers.Dense(units=12, activation='relu'))

In [13]:
ann.add(tf.keras.layers.Dense(32, kernel_initializer='lecun_normal', activation='selu'))

### Adding the output layer

In [14]:
#ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [15]:
ann.add(tf.keras.layers.Dense(16, kernel_initializer='lecun_normal', activation='selu'))
ann.add(tf.keras.layers.Dense(10, activation='softmax'))

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [17]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [18]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 513us/step - loss: 0.5358 - accuracy: 0.8011
Epoch 2/100
250/250 [==============================] - 0s 504us/step - loss: 0.4654 - accuracy: 0.8284
Epoch 3/100
250/250 [==============================] - 0s 496us/step - loss: 0.4237 - accuracy: 0.8317
Epoch 4/100
250/250 [==============================] - 0s 500us/step - loss: 0.4032 - accuracy: 0.8393
Epoch 5/100
250/250 [==============================] - 0s 501us/step - loss: 0.3896 - accuracy: 0.8594
Epoch 6/100
250/250 [==============================] - 0s 504us/step - loss: 0.3793 - accuracy: 0.8593
Epoch 7/100
250/250 [==============================] - 0s 481us/step - loss: 0.3724 - accuracy: 0.8622
Epoch 8/100
250/250 [==============================] - 0s 516us/step - loss: 0.3670 - accuracy: 0.8606
Epoch 9/100
250/250 [==============================] - 0s 490us/step - loss: 0.3624 - accuracy: 0.8637
Epoch 10/100
250/250 [==============================] - 0s 489us/step - l

250/250 [==============================] - 0s 517us/step - loss: 0.2768 - accuracy: 0.8946
Epoch 80/100
250/250 [==============================] - 0s 487us/step - loss: 0.2737 - accuracy: 0.8970
Epoch 81/100
250/250 [==============================] - 0s 493us/step - loss: 0.2738 - accuracy: 0.8970
Epoch 82/100
250/250 [==============================] - 0s 497us/step - loss: 0.2727 - accuracy: 0.8995
Epoch 83/100
250/250 [==============================] - 0s 509us/step - loss: 0.2701 - accuracy: 0.8988
Epoch 84/100
250/250 [==============================] - 0s 540us/step - loss: 0.2706 - accuracy: 0.8979
Epoch 85/100
250/250 [==============================] - 0s 503us/step - loss: 0.2732 - accuracy: 0.8959
Epoch 86/100
250/250 [==============================] - 0s 501us/step - loss: 0.2685 - accuracy: 0.9003
Epoch 87/100
250/250 [==============================] - 0s 513us/step - loss: 0.2686 - accuracy: 0.8990
Epoch 88/100
250/250 [==============================] - 0s 509us/step - loss:

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [19]:
y_pred = ann.predict(X_test)
y_pred

array([[0.3020215 ],
       [0.07842138],
       [0.07813784],
       ...,
       [0.03407356],
       [0.26528135],
       [0.06625548]], dtype=float32)

In [20]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

# Criando uma Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1487  108]
 [ 190  215]]


# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)

In [22]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [23]:
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'selu', input_dim = 12))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'selu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifer.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['acc'])
    return classifer

In [24]:
classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)