# REDES NEURAIS ARTIFICIAIS

[Aula 3 de Deep Learning](http://bit.ly/dn-unb03) da Engenharia de Software da UnB

In [2]:
# Installing Theano
! pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
! pip install --upgrade tensorflow

# Installing Keras
! pip install --upgrade keras

# Install other packages
! pip install --upgrade pip pandas numpy matplotlib sklearn

  Cloning git://github.com/Theano/Theano.git to /tmp/pip-req-build-m66yg5qz
  Running command git clone -q git://github.com/Theano/Theano.git /tmp/pip-req-build-m66yg5qz
  Created wheel for Theano: filename=Theano-1.0.4+21.g8f510a1f0-cp37-none-any.whl size=2667497 sha256=f32d7ae24a6823ea2d61e4c02c4f2444334549f3bbe60d3eff4a8ec7424f44b5
  Stored in directory: /tmp/pip-ephem-wheel-cache-4cc6urvr/wheels/ae/32/7c/62beb8371953eb20c271b3bac7d0e56e1a2020d46994346b52
Successfully built Theano
  Using cached https://files.pythonhosted.org/packages/f4/28/96efba1a516cdacc2e2d6d081f699c001d414cc8ca3250e6d59ae657eb2b/tensorflow-1.14.0-cp37-cp37m-manylinux1_x86_64.whl
  Using cached https://files.pythonhosted.org/packages/91/2d/2ed263449a078cd9c8a9ba50ebd50123adf1f8cfbea1492f9084169b89d9/tensorboard-1.14.0-py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/3c/d5/21860a5b11caf0678fbc8319341b0ae21a07156911132e0e71bffed0510d/tensorflow_estimator-1.14.0-py2.py3-none-any.whl
  Found e

# Parte 1 - Preprocessamento dos Dados

### Importar as libs

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Importar o dataset

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


### Transformando os dados categóricos


In [3]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]
print("X >>\n",X)

X >>
 [[0.0000000e+00 0.0000000e+00 6.1900000e+02 ... 1.0000000e+00
  1.0000000e+00 1.0134888e+05]
 [0.0000000e+00 1.0000000e+00 6.0800000e+02 ... 0.0000000e+00
  1.0000000e+00 1.1254258e+05]
 [0.0000000e+00 0.0000000e+00 5.0200000e+02 ... 1.0000000e+00
  0.0000000e+00 1.1393157e+05]
 ...
 [0.0000000e+00 0.0000000e+00 7.0900000e+02 ... 0.0000000e+00
  1.0000000e+00 4.2085580e+04]
 [1.0000000e+00 0.0000000e+00 7.7200000e+02 ... 1.0000000e+00
  0.0000000e+00 9.2888520e+04]
 [0.0000000e+00 0.0000000e+00 7.9200000e+02 ... 1.0000000e+00
  0.0000000e+00 3.8190780e+04]]


/home/ziegler/PyEnv/DeepLearning/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/ziegler/PyEnv/DeepLearning/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

---
# Parte 2 -Vamos construir uma ANN!

## Importando o Keras


In [9]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [11]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Ajustando a ANN ao conjunto de treinamento

In [12]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 0s 57us/step - loss: 0.4835 - accuracy: 0.7959
Epoch 2/100
8000/8000 [==============================] - 0s 46us/step - loss: 0.4271 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 0s 41us/step - loss: 0.4210 - accuracy: 0.8000
Epoch 4/100
8000/8000 [==============================] - 0s 40us/step - loss: 0.4173 - accuracy: 0.8250
Epoch 5/100
8000/8000 [==============================] - 0s 40us/step - loss: 0.4148 - accuracy: 0.8298
Epoch 6/100
8000/8000 [==============================] - 0s 39us/step - loss: 0.4127 - accuracy: 0.8300
Epoch 7/100
8000/8000 [==============================] - 0s 41us/step - loss: 0.4091 - accuracy: 0.8335
Epoch 8/100
8000/8000 [==============================] - 0s 41us/step - loss: 0.4063 - accuracy: 0.8346
Epoch 9/100
8000/8000 [==============================] - 0s 41us/step - loss: 0.4039 - accuracy: 0.8361
Epoch 10/100
8000/8000 [==============================] - 0s 41u

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [10]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Criando uma Confusion Matrix

In [11]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1510   85]
 [ 196  209]]


# Initiate activation function experimentation

# Initialising the 2nd ANN

In [14]:
del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'tanh'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 2s 242us/step - loss: 3.2881 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 2s 191us/step - loss: 3.2881 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 194us/step - loss: 3.2881 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 2s 254us/step - loss: 3.2881 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 2s 218us/step - loss: 3.2881 - acc: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 187us/step - loss: 3.2881 - acc: 0.7960
Epoch 7/100
8000/8000 [==============================] - 1s 185us/step - loss: 3.2881 - acc: 0.7960
Epoch 8/100
8000/8000 [==============================] - 1s 180us/step - loss: 3.2881 - acc: 0.7960
Epoch 9/100
8000/8000 [==============================] - 1s 183us/step - loss: 3.2881 - acc: 0.7960
Epoch 10/100
8000/8000 [==============================] - 2s 190us/step - loss: 3.2881 - acc: 0.7960

In [14]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix

In [15]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1503   92]
 [ 191  214]]


# Initialising the 3rd ANN

In [16]:
del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 0s 57us/step - loss: 0.5069 - accuracy: 0.7960
Epoch 2/100
8000/8000 [==============================] - 0s 43us/step - loss: 0.4449 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 0s 41us/step - loss: 0.4327 - accuracy: 0.7956
Epoch 4/100
8000/8000 [==============================] - 0s 41us/step - loss: 0.4291 - accuracy: 0.8010
Epoch 5/100
8000/8000 [==============================] - 0s 41us/step - loss: 0.4281 - accuracy: 0.8025
Epoch 6/100
8000/8000 [==============================] - 0s 41us/step - loss: 0.4277 - accuracy: 0.8045
Epoch 7/100
8000/8000 [==============================] - 0s 41us/step - loss: 0.4273 - accuracy: 0.8035
Epoch 8/100
8000/8000 [==============================] - 0s 41us/step - loss: 0.4272 - accuracy: 0.8046
Epoch 9/100
8000/8000 [==============================] - 0s 41us/step - loss: 0.4271 - accuracy: 0.8041
Epoch 10/100
8000/8000 [==============================] - 0s 42u

In [17]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix

In [18]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1549   46]
 [ 265  140]]


---
# Parte 4 - Evaluating, Improving and Tuning the ANN

## Evaluating the ANN

In [21]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()
print("accuracies:{}\nmean:{}\nvariance:{}".format(accuracies, mean, variance))

accuracies:[0.83125001 0.83499998 0.83375001 0.82499999 0.85124999 0.83125001
 0.83499998 0.82125002 0.81999999 0.84375   ]
mean:0.8327499985694885
variance:0.009130987698077214


# Improving the ANN
# Dropout Regularization to reduce overfitting if needed

In [22]:
from keras.layers import Dropout

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()

# Tuning the ANN

In [23]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense

def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier)

In [25]:
parameters = {'batch_size': [10, 24, 32],
              'epochs': [50],
              'optimizer': ['adam', 'rmsprop']}

grid_search = GridSearchCV(estimator = classifier,
                           scoring = 'accuracy',
                           param_grid = parameters,
                           cv = 10)

grid_search = grid_search.fit(X_train, y_train)

best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

Epoch 1/50
7200/7200 [==============================] - 1s 96us/step - loss: 0.4990 - accuracy: 0.7969
Epoch 2/50
7200/7200 [==============================] - 0s 65us/step - loss: 0.4369 - accuracy: 0.7971
Epoch 3/50
7200/7200 [==============================] - 0s 64us/step - loss: 0.4331 - accuracy: 0.7971
Epoch 4/50
7200/7200 [==============================] - 0s 64us/step - loss: 0.4303 - accuracy: 0.7971
Epoch 5/50
7200/7200 [==============================] - 0s 63us/step - loss: 0.4263 - accuracy: 0.7971
Epoch 6/50
7200/7200 [==============================] - 0s 64us/step - loss: 0.4271 - accuracy: 0.7990
Epoch 7/50
7200/7200 [==============================] - 0s 63us/step - loss: 0.4263 - accuracy: 0.8176
Epoch 8/50
7200/7200 [==============================] - 0s 69us/step - loss: 0.4257 - accuracy: 0.8247
Epoch 9/50
7200/7200 [==============================] - 0s 64us/step - loss: 0.4246 - accuracy: 0.8275
Epoch 10/50
7200/7200 [==============================] - 0s 64us/step - l

In [29]:
best_accuracy, best_parameters

(0.840625, {'batch_size': 32, 'epochs': 50, 'optimizer': 'rmsprop'})

# Optimized ANN

In [53]:
def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units=6, kernel_initializer='uniform',
                         activation='relu', input_dim=11))
    classifier.add(Dropout(rate=0.1))
    classifier.add(
        Dense(units=6, kernel_initializer='uniform', activation='relu'))
    classifier.add(Dropout(rate=0.1))
    classifier.add(
        Dense(units=1, kernel_initializer='uniform', activation='sigmoid'))
    classifier.compile(optimizer=optimizer, loss='binary_crossentropy', 
                       metrics=['accuracy'])
    
    return classifier

classifier = KerasClassifier(build_fn=build_classifier, optimizer='rmsprop',
                             batch_size=32, epochs=50, verbose=1)

earlystopping = EarlyStopping(monitor='val_loss', verbose=1)
classifier.fit(X_train, y_train, 
               callbacks=[earlystopping], verbose=1)

accuracies = cross_val_score(estimator=classifier, X=X_train, y=y_train, cv=10, n_jobs=-1)
mean = accuracies.mean()
variance = accuracies.std()
max = accuracies.max()
mean, variance, max

Epoch 1/50
8000/8000 [==============================] - 1s 104us/step - loss: 0.5816 - accuracy: 0.7960
Epoch 2/50
3968/8000 [=============>................] - ETA: 0s - loss: 0.4522 - accuracy: 0.7923

/home/ziegler/PyEnv/DeepLearning/lib/python3.7/site-packages/keras/callbacks/callbacks.py:846: RuntimeWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
  (self.monitor, ','.join(list(logs.keys()))), RuntimeWarning


8000/8000 [==============================] - 0s 38us/step - loss: 0.4474 - accuracy: 0.7960
Epoch 3/50
8000/8000 [==============================] - 0s 35us/step - loss: 0.4362 - accuracy: 0.7960
Epoch 4/50
8000/8000 [==============================] - 0s 35us/step - loss: 0.4342 - accuracy: 0.7960
Epoch 5/50
8000/8000 [==============================] - 0s 35us/step - loss: 0.4352 - accuracy: 0.7960
Epoch 6/50
8000/8000 [==============================] - 0s 35us/step - loss: 0.4349 - accuracy: 0.7960
Epoch 7/50
8000/8000 [==============================] - 0s 34us/step - loss: 0.4291 - accuracy: 0.7960
Epoch 8/50
8000/8000 [==============================] - 0s 35us/step - loss: 0.4295 - accuracy: 0.7960
Epoch 9/50
8000/8000 [==============================] - 0s 35us/step - loss: 0.4277 - accuracy: 0.7960
Epoch 10/50
8000/8000 [==============================] - 0s 35us/step - loss: 0.4289 - accuracy: 0.7960
Epoch 11/50
8000/8000 [==============================] - 0s 35us/step - loss: 0.426

(0.837374997138977, 0.013595150347099768, 0.8600000143051147)

# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)