# REDES NEURAIS ARTIFICIAIS

[Aula 3 de Deep Learning](http://bit.ly/dn-unb03) da Engenharia de Software da UnB

In [1]:
# Installing Theano
! pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
! pip install --upgrade tensorflow

# Installing Keras
! pip install --upgrade keras

# Install other packages
! pip install --upgrade pip pandas numpy matplotlib sklearn

  Cloning git://github.com/Theano/Theano.git to /tmp/pip-req-build-ojg4pqa0
  Running command git clone -q git://github.com/Theano/Theano.git /tmp/pip-req-build-ojg4pqa0
  Created wheel for Theano: filename=Theano-1.0.4+23.g630974a-cp37-none-any.whl size=2667471 sha256=5637cf509588c3831ce6a98c43a3083df3db6f7c9136dd2759af86ba6045421a
  Stored in directory: /tmp/pip-ephem-wheel-cache-sbzvdca_/wheels/ae/32/7c/62beb8371953eb20c271b3bac7d0e56e1a2020d46994346b52
Successfully built Theano
  Found existing installation: Theano 1.0.4+23.g630974a
    Uninstalling Theano-1.0.4+23.g630974a:
      Successfully uninstalled Theano-1.0.4+23.g630974a
Requirement already up-to-date: tensorflow in /home/joao/anaconda3/lib/python3.7/site-packages (2.0.0)
Requirement already up-to-date: keras in /home/joao/anaconda3/lib/python3.7/site-packages (2.3.1)
Requirement already up-to-date: pip in /home/joao/anaconda3/lib/python3.7/site-packages (19.3.1)
Requirement already up-to-date: pandas in /home/joao/anacond

# Parte 1 - Preprocessamento dos Dados

### Importar as libs

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Importar o dataset

### Transformando os dados categóricos


In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


In [4]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]
print("X >>\n",X)

X >>
 [[0.0000000e+00 0.0000000e+00 6.1900000e+02 ... 1.0000000e+00
  1.0000000e+00 1.0134888e+05]
 [0.0000000e+00 1.0000000e+00 6.0800000e+02 ... 0.0000000e+00
  1.0000000e+00 1.1254258e+05]
 [0.0000000e+00 0.0000000e+00 5.0200000e+02 ... 1.0000000e+00
  0.0000000e+00 1.1393157e+05]
 ...
 [0.0000000e+00 0.0000000e+00 7.0900000e+02 ... 0.0000000e+00
  1.0000000e+00 4.2085580e+04]
 [1.0000000e+00 0.0000000e+00 7.7200000e+02 ... 1.0000000e+00
  0.0000000e+00 9.2888520e+04]
 [0.0000000e+00 0.0000000e+00 7.9200000e+02 ... 1.0000000e+00
  0.0000000e+00 3.8190780e+04]]
/home/joao/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a Lab

# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

---
# Parte 2 -Vamos construir uma ANN!

## Importando o Keras


In [7]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [8]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Ajustando a ANN ao conjunto de treinamento

In [9]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 20)

Epoch 1/20
8000/8000 [==============================] - 2s 277us/step - loss: 0.5282 - accuracy: 0.7890
Epoch 2/20
8000/8000 [==============================] - 2s 233us/step - loss: 0.4797 - accuracy: 0.7960
Epoch 3/20
8000/8000 [==============================] - 2s 279us/step - loss: 0.4652 - accuracy: 0.7960
Epoch 4/20
8000/8000 [==============================] - 2s 286us/step - loss: 0.4520 - accuracy: 0.7960
Epoch 5/20
8000/8000 [==============================] - 2s 277us/step - loss: 0.4423 - accuracy: 0.7960
Epoch 6/20
8000/8000 [==============================] - 2s 276us/step - loss: 0.4360 - accuracy: 0.7960
Epoch 7/20
8000/8000 [==============================] - 2s 254us/step - loss: 0.4323 - accuracy: 0.7960
Epoch 8/20
8000/8000 [==============================] - 2s 241us/step - loss: 0.4306 - accuracy: 0.7960
Epoch 9/20
8000/8000 [==============================] - 2s 277us/step - loss: 0.4296 - accuracy: 0.7960
Epoch 10/20
8000/8000 [==============================] - 2s 284u

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [10]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Criando uma Confusion Matrix

In [11]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1595    0]
 [ 405    0]]


# Initiate activation function experimentation

# Initialising the 2nd ANN

In [12]:
del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'relu'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 20)

Epoch 1/20
8000/8000 [==============================] - 2s 216us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 2/20
8000/8000 [==============================] - 2s 192us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 3/20
8000/8000 [==============================] - 2s 197us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 4/20
8000/8000 [==============================] - 2s 201us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 5/20
8000/8000 [==============================] - 2s 197us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 6/20
8000/8000 [==============================] - 2s 201us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 7/20
8000/8000 [==============================] - 2s 228us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 8/20
8000/8000 [==============================] - 2s 203us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 9/20
8000/8000 [==============================] - 2s 242us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 10/20
8000/8000 [==============================] - 2s 239u

In [13]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix

In [14]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1595    0]
 [ 405    0]]


# Initialising the 3rd ANN

In [15]:
del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'relu'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 20)

Epoch 1/20
8000/8000 [==============================] - 2s 311us/step - loss: 0.5113 - accuracy: 0.8035
Epoch 2/20
8000/8000 [==============================] - 3s 333us/step - loss: 0.4130 - accuracy: 0.8135
Epoch 3/20
8000/8000 [==============================] - 2s 269us/step - loss: 0.3973 - accuracy: 0.8205
Epoch 4/20
8000/8000 [==============================] - 3s 315us/step - loss: 0.3916 - accuracy: 0.8290
Epoch 5/20
8000/8000 [==============================] - 2s 274us/step - loss: 0.3800 - accuracy: 0.8375
Epoch 6/20
8000/8000 [==============================] - 2s 250us/step - loss: 0.3752 - accuracy: 0.8410
Epoch 7/20
8000/8000 [==============================] - 2s 250us/step - loss: 0.3763 - accuracy: 0.8415
Epoch 8/20
8000/8000 [==============================] - 2s 227us/step - loss: 0.3755 - accuracy: 0.8397
Epoch 9/20
8000/8000 [==============================] - 2s 227us/step - loss: 0.3694 - accuracy: 0.8389
Epoch 10/20
8000/8000 [==============================] - 2s 255u

In [16]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix

In [17]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1524   71]
 [ 215  190]]


---
# Parte 4 - Evaluating, Improving and Tuning the ANN

## Evaluating the ANN

In [18]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 20)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()

print(accuracies)
print(mean)
print(variance)

[0.82999998 0.83999997 0.85374999 0.83375001 0.85124999 0.82999998
 0.82999998 0.81999999 0.8125     0.86750001]
0.8368749916553497
0.01571474424516427


# Improving the ANN
# Dropout Regularization to reduce overfitting if needed

In [19]:
from keras.layers import Dropout

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()

print(accuracies)
print(mean)
print(variance)

[0.82749999 0.81625003 0.80000001 0.81124997 0.85500002 0.82999998
 0.82625002 0.81375003 0.8175     0.83375001]
0.8231250047683716
0.014309635575369413


# Tuning the ANN

In [20]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense

def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier)

In [21]:
parameters = {'batch_size': [10, 24, 32],
              'epochs': [10, 100, 200],
              'optimizer': ['adam', 'rmsprop']}

grid_search = GridSearchCV(estimator = classifier,
                           scoring = 'accuracy',
                           param_grid = parameters,
                           cv = 10)

grid_search = grid_search.fit(X_train, y_train)

best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

print(best_parameters)
print(best_accuracy)

Epoch 1/50
7200/7200 [==============================] - 2s 295us/step - loss: 0.4893 - accuracy: 0.7968
Epoch 2/50
7200/7200 [==============================] - 2s 270us/step - loss: 0.4280 - accuracy: 0.7971
Epoch 3/50
7200/7200 [==============================] - 2s 238us/step - loss: 0.4190 - accuracy: 0.7971
Epoch 4/50
7200/7200 [==============================] - 2s 240us/step - loss: 0.4178 - accuracy: 0.7975
Epoch 5/50
7200/7200 [==============================] - 2s 253us/step - loss: 0.4144 - accuracy: 0.8218
Epoch 6/50
7200/7200 [==============================] - 2s 259us/step - loss: 0.4121 - accuracy: 0.8238
Epoch 7/50
7200/7200 [==============================] - 2s 267us/step - loss: 0.4091 - accuracy: 0.8235
Epoch 8/50
7200/7200 [==============================] - 2s 239us/step - loss: 0.4097 - accuracy: 0.8258
Epoch 9/50
7200/7200 [==============================] - 2s 234us/step - loss: 0.4099 - accuracy: 0.8219
Epoch 10/50
7200/7200 [==============================] - 2s 260u

# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)