# REDES NEURAIS ARTIFICIAIS

[Aula 3 de Deep Learning](http://bit.ly/dn-unb03) da Engenharia de Software da UnB

# Parte 1 - Pré-processamento dos Dados

### Importar as libs

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.4.1'

### Importar o dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


### Transformando os dados categóricos


In [5]:
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]
[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
np.shape(X_train)

(8000, 12)

---
# Parte 2 -Vamos construir uma ANN!


### Initializing the ANN

In [9]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units=32, activation='sigmoid'))

### Adding the second hidden layer

In [11]:
ann.add(tf.keras.layers.Dense(units=32, activation='tanh'))

### Adding the output layer

In [12]:
ann.add(tf.keras.layers.Dense(units=1, activation='tanh'))

## Part 3 - Training the ANN

### Compiling the ANN

In [13]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [14]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 200)

Epoch 1/200
250/250 [==============================] - 1s 1ms/step - loss: 0.6002 - accuracy: 0.7814
Epoch 2/200
250/250 [==============================] - 0s 999us/step - loss: 0.5782 - accuracy: 0.7235
Epoch 3/200
250/250 [==============================] - 0s 891us/step - loss: 0.5316 - accuracy: 0.7740
Epoch 4/200
250/250 [==============================] - 0s 1ms/step - loss: 0.6426 - accuracy: 0.6268
Epoch 5/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4714 - accuracy: 0.7904
Epoch 6/200
250/250 [==============================] - 0s 1ms/step - loss: 0.5646 - accuracy: 0.7455
Epoch 7/200
250/250 [==============================] - 0s 827us/step - loss: 0.4829 - accuracy: 0.7952
Epoch 8/200
250/250 [==============================] - 0s 886us/step - loss: 0.4908 - accuracy: 0.7665
Epoch 9/200
250/250 [==============================] - 0s 831us/step - loss: 0.5112 - accuracy: 0.8041
Epoch 10/200
250/250 [==============================] - 0s 1ms/step - loss: 0.596

250/250 [==============================] - 0s 1ms/step - loss: 0.3697 - accuracy: 0.8509
Epoch 81/200
250/250 [==============================] - 0s 788us/step - loss: 0.3865 - accuracy: 0.8503
Epoch 82/200
250/250 [==============================] - 0s 780us/step - loss: 0.3771 - accuracy: 0.8557
Epoch 83/200
250/250 [==============================] - 0s 800us/step - loss: 0.3785 - accuracy: 0.8473
Epoch 84/200
250/250 [==============================] - 0s 960us/step - loss: 0.3683 - accuracy: 0.8476
Epoch 85/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3631 - accuracy: 0.8523
Epoch 86/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3733 - accuracy: 0.8590
Epoch 87/200
250/250 [==============================] - 0s 886us/step - loss: 0.3660 - accuracy: 0.8532
Epoch 88/200
250/250 [==============================] - 0s 839us/step - loss: 0.3535 - accuracy: 0.8557
Epoch 89/200
250/250 [==============================] - 0s 807us/step - loss: 0.421

250/250 [==============================] - 0s 807us/step - loss: 0.3372 - accuracy: 0.8633
Epoch 160/200
250/250 [==============================] - 0s 772us/step - loss: 0.3359 - accuracy: 0.8655
Epoch 161/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3380 - accuracy: 0.8601
Epoch 162/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3639 - accuracy: 0.8537
Epoch 163/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3450 - accuracy: 0.8638
Epoch 164/200
250/250 [==============================] - 0s 858us/step - loss: 0.3474 - accuracy: 0.8618
Epoch 165/200
250/250 [==============================] - 0s 790us/step - loss: 0.3315 - accuracy: 0.8676
Epoch 166/200
250/250 [==============================] - 0s 795us/step - loss: 0.3449 - accuracy: 0.8552
Epoch 167/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3510 - accuracy: 0.8439
Epoch 168/200
250/250 [==============================] - 0s 1ms/step - loss: 

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [15]:
y_pred = ann.predict(X_test)
y_pred

array([[0.3158701 ],
       [0.4243134 ],
       [0.31844884],
       ...,
       [0.4163412 ],
       [0.29296577],
       [0.33704594]], dtype=float32)

In [16]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

# Criando uma Confusion Matrix

In [17]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1505   90]
 [ 194  211]]


# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)