# REDES NEURAIS ARTIFICIAIS

[Aula 3 de Deep Learning](http://bit.ly/dn-unb03) da Engenharia de Software da UnB

# Parte 1 - Pré-processamento dos Dados

### Importar as libs

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

2021-09-16 16:27:39.772340: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-09-16 16:27:39.772384: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
tf.__version__

'2.6.0'

### Importar o dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head(50)

RowNumber  CustomerId        Surname  CreditScore Geography  Gender  Age  \
0           1    15634602       Hargrave          619    France  Female   42   
1           2    15647311           Hill          608     Spain  Female   41   
2           3    15619304           Onio          502    France  Female   42   
3           4    15701354           Boni          699    France  Female   39   
4           5    15737888       Mitchell          850     Spain  Female   43   
5           6    15574012            Chu          645     Spain    Male   44   
6           7    15592531       Bartlett          822    France    Male   50   
7           8    15656148         Obinna          376   Germany  Female   29   
8           9    15792365             He          501    France    Male   44   
9          10    15592389             H?          684    France    Male   27   
10         11    15767821         Bearce          528    France    Male   31   
11         12    15737173        Andrews          497     Spain    Male   24   
12         13    15632264            Kay          476    France  Female   34   
13         14    15691483           Chin          549    France  Female   25   
14         15    15600882          Scott          635     Spain  Female   35   
15         16    15643966        Goforth          616   Germany    Male   45   
16         17    15737452          Romeo          653   Germany    Male   58   
17         18    15788218      Henderson          549     Spain  Female   24   
18         19    15661507        Muldrow          587     Spain    Male   45   
19         20    15568982            Hao          726    France  Female   24   
20         21    15577657       McDonald          732    France    Male   41   
21         22    15597945       Dellucci          636     Spain  Female   32   
22         23    15699309      Gerasimov          510     Spain  Female   38   
23         24    15725737         Mosman          669    France    Male   46   
24         25    15625047            Yen          846    France  Female   38   
25         26    15738191        Maclean          577    France    Male   25   
26         27    15736816          Young          756   Germany    Male   36   
27         28    15700772        Nebechi          571    France    Male   44   
28         29    15728693     McWilliams          574   Germany  Female   43   
29         30    15656300       Lucciano          411    France    Male   29   
30         31    15589475        Azikiwe          591     Spain  Female   39   
31         32    15706552  Odinakachukwu          533    France    Male   36   
32         33    15750181      Sanderson          553   Germany    Male   41   
33         34    15659428        Maggard          520     Spain  Female   42   
34         35    15732963       Clements          722     Spain  Female   29   
35         36    15794171       Lombardo          475    France  Female   45   
36         37    15788448         Watson          490     Spain    Male   31   
37         38    15729599        Lorenzo          804     Spain    Male   33   
38         39    15717426      Armstrong          850    France    Male   36   
39         40    15585768        Cameron          582   Germany    Male   41   
40         41    15619360          Hsiao          472     Spain    Male   40   
41         42    15738148         Clarke          465    France  Female   51   
42         43    15687946        Osborne          556    France  Female   61   
43         44    15755196         Lavine          834    France  Female   49   
44         45    15684171        Bianchi          660     Spain  Female   61   
45         46    15754849          Tyler          776   Germany  Female   32   
46         47    15602280         Martin          829   Germany  Female   27   
47         48    15771573        Okagbue          637   Germany  Female   39   
48         49    15766205            Yin          550   Germany    Male   38   
49  

In [4]:
dataset.Geography.value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [5]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


### Transformando os dados categóricos


In [6]:
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X[:, 2])

[0 0 0 ... 0 1 0]


In [7]:
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
np.shape(X_train)

(8000, 12)

In [11]:
X_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

---
# Parte 2 -Vamos construir uma ANN!


### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [15]:
#third layer
ann.add(tf.keras.layers.Dense(units=4, activation='relu'))

### Adding the output layer

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

### Compiling the ANN

In [17]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

## Part 3 - Training the ANN

### Training the ANN on the Training set

In [18]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 120)

2021-09-16 16:27:50.723081: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


Epoch 1/120
250/250 [==============================] - 1s 989us/step - loss: 0.5269 - accuracy: 0.7891
Epoch 2/120
250/250 [==============================] - 0s 998us/step - loss: 0.4406 - accuracy: 0.8019
Epoch 3/120
250/250 [==============================] - 0s 1ms/step - loss: 0.4155 - accuracy: 0.8175
Epoch 4/120
250/250 [==============================] - 0s 986us/step - loss: 0.3970 - accuracy: 0.8291
Epoch 5/120
250/250 [==============================] - 0s 963us/step - loss: 0.3803 - accuracy: 0.8361
Epoch 6/120
250/250 [==============================] - 0s 955us/step - loss: 0.3690 - accuracy: 0.8455
Epoch 7/120
250/250 [==============================] - 0s 953us/step - loss: 0.3622 - accuracy: 0.8476
Epoch 8/120
250/250 [==============================] - 0s 985us/step - loss: 0.3581 - accuracy: 0.8499
Epoch 9/120
250/250 [==============================] - 0s 922us/step - loss: 0.3553 - accuracy: 0.8528
Epoch 10/120
250/250 [==============================] - 0s 929us/step - los

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [19]:
y_pred = ann.predict(X_test)
y_pred

array([[0.25018567],
       [0.37992558],
       [0.21424583],
       ...,
       [0.1604864 ],
       [0.15553358],
       [0.24301049]], dtype=float32)

In [20]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

# Criando uma Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1502   93]
 [ 194  211]]


# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)