# REDES NEURAIS ARTIFICIAIS

[Aula 3 de Deep Learning](http://bit.ly/dn-unb03) da Engenharia de Software da UnB

# Parte 1 - Pré-processamento dos Dados

### Importar as libs

In [356]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [357]:
tf.__version__

'2.6.0'

### Importar o dataset

In [358]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head(50)

RowNumber  CustomerId  ... EstimatedSalary  Exited
0           1    15634602  ...       101348.88       1
1           2    15647311  ...       112542.58       0
2           3    15619304  ...       113931.57       1
3           4    15701354  ...        93826.63       0
4           5    15737888  ...        79084.10       0
5           6    15574012  ...       149756.71       1
6           7    15592531  ...        10062.80       0
7           8    15656148  ...       119346.88       1
8           9    15792365  ...        74940.50       0
9          10    15592389  ...        71725.73       0
10         11    15767821  ...        80181.12       0
11         12    15737173  ...        76390.01       0
12         13    15632264  ...        26260.98       0
13         14    15691483  ...       190857.79       0
14         15    15600882  ...        65951.65       0
15         16    15643966  ...        64327.26       0
16         17    15737452  ...         5097.67       1
17         18    15788218  ...        14406.41       0
18         19    15661507  ...       158684.81       0
19         20    15568982  ...        54724.03       0
20         21    15577657  ...       170886.17       0
21         22    15597945  ...       138555.46       0
22         23    15699309  ...       118913.53       1
23         24    15725737  ...         8487.75       0
24         25    15625047  ...       187616.16       0
25         26    15738191  ...       124508.29       0
26         27    15736816  ...       170041.95       0
27         28    15700772  ...        38433.35       0
28         29    15728693  ...       100187.43       0
29         30    15656300  ...        53483.21       0
30         31    15589475  ...       140469.38       1
31         32    15706552  ...       156731.91       0
32         33    15750181  ...        81898.81       0
33         34    15659428  ...        34410.55       0
34         35    15732963  ...       142033.07       0
35         36    15794171  ...        27822.99       1
36         37    15788448  ...       114066.77       0
37         38    15729599  ...        98453.45       0
38         39    15717426  ...        40812.90       0
39         40    15585768  ...       178074.04       0
40         41    15619360  ...        70154.22       0
41         42    15738148  ...       181297.65       1
42         43    15687946  ...        94153.83       0
43         44    15755196  ...       194365.76       1
44         45    15684171  ...       158338.39       0
45         46    15754849  ...       126517.46       0
46         47    15602280  ...       119708.21       1
47         48    15771573  ...       117622.80       1
48         49    15766205  ...        90878.13       0
49         50    15771873  ...       194099.12       0

[50 rows x 14 columns]

In [359]:
dataset.Geography.value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [360]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


### Transformando os dados categóricos


In [361]:
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X[:, 2])

[0 0 0 ... 0 1 0]


In [362]:
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [363]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [364]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [365]:
np.shape(X_train)

(8000, 12)

In [366]:
X_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

---
# Parte 2 -Vamos construir uma ANN!


### Initializing the ANN

In [367]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [368]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [369]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [370]:
ann.add(tf.keras.layers.Dense(units=1, activation='softsign'))

### Compiling the ANN

In [371]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

## Part 3 - Training the ANN

### Training the ANN on the Training set

In [372]:
ann.fit(X_train, y_train, batch_size = 40, epochs = 150)

Epoch 1/150
200/200 [==============================] - 1s 2ms/step - loss: 2.9700 - accuracy: 0.7962
Epoch 2/150
200/200 [==============================] - 0s 2ms/step - loss: 2.2285 - accuracy: 0.7860
Epoch 3/150
200/200 [==============================] - 0s 1ms/step - loss: 1.6427 - accuracy: 0.7508
Epoch 4/150
200/200 [==============================] - 0s 1ms/step - loss: 1.3066 - accuracy: 0.7206
Epoch 5/150
200/200 [==============================] - 0s 1ms/step - loss: 1.0833 - accuracy: 0.6886
Epoch 6/150
200/200 [==============================] - 0s 1ms/step - loss: 1.0167 - accuracy: 0.7088
Epoch 7/150
200/200 [==============================] - 0s 1ms/step - loss: 0.9535 - accuracy: 0.7347
Epoch 8/150
200/200 [==============================] - 0s 1ms/step - loss: 0.6632 - accuracy: 0.7236
Epoch 9/150
200/200 [==============================] - 0s 1ms/step - loss: 0.5980 - accuracy: 0.7530
Epoch 10/150
200/200 [==============================] - 0s 1ms/step - loss: 0.5763 - accura

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [373]:
y_pred = ann.predict(X_test)
y_pred

array([[0.37878203],
       [0.3977911 ],
       [0.24195729],
       ...,
       [0.22988275],
       [0.18681929],
       [0.2708241 ]], dtype=float32)

In [374]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

# Criando uma Confusion Matrix

In [375]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1532   63]
 [ 207  198]]


# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)