# REDES NEURAIS ARTIFICIAIS

[Aula 3 de Deep Learning](http://bit.ly/dn-unb03) da Engenharia de Software da UnB

# Parte 1 - Pré-processamento dos Dados

### Importar as libs

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'1.13.1'

### Importar o dataset

In [23]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [137]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


### Transformando os dados categóricos


In [138]:
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]
[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [139]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


# Feature Scaling

In [140]:
from sklearn.preprocessing import StandardScaler
#from sklearn.preprocessing import MinMaxScaler

sc = StandardScaler()
#sc = MinMaxScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [141]:
np.shape(X_train)

(8000, 12)

---
# Parte 2 -Vamos construir uma ANN!


### Initializing the ANN

In [142]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [143]:
#ann.add(tf.keras.layers.Dense(units=6))
#ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
#ann.add(tf.keras.layers.Dense(units=6, activation='tanh'))
ann.add(tf.keras.layers.Dense(units=6, activation='sigmoid'))

### Adding the second hidden layer

In [144]:
#ann.add(tf.keras.layers.Dense(units=6))
#ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
#ann.add(tf.keras.layers.Dense(units=6, activation='tanh'))
ann.add(tf.keras.layers.Dense(units=6, activation='sigmoid'))

### Adding the output layer

In [145]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [146]:
ann.compile(optimizer = 'Adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [147]:
ann.fit(X_train, y_train, batch_size = 16, epochs = 120)

Epoch 1/120
8000/8000 [==============================] - 1s 129us/sample - loss: 0.4991 - acc: 0.7960
Epoch 2/120
8000/8000 [==============================] - 1s 85us/sample - loss: 0.4761 - acc: 0.7960
Epoch 3/120
8000/8000 [==============================] - 1s 95us/sample - loss: 0.4505 - acc: 0.7960
Epoch 4/120
8000/8000 [==============================] - 1s 78us/sample - loss: 0.4350 - acc: 0.7960
Epoch 5/120
8000/8000 [==============================] - 1s 105us/sample - loss: 0.4296 - acc: 0.7956
Epoch 6/120
8000/8000 [==============================] - 1s 100us/sample - loss: 0.4276 - acc: 0.7991
Epoch 7/120
8000/8000 [==============================] - 1s 104us/sample - loss: 0.4269 - acc: 0.8014
Epoch 8/120
8000/8000 [==============================] - 1s 100us/sample - loss: 0.4264 - acc: 0.8025
Epoch 9/120
8000/8000 [==============================] - 1s 107us/sample - loss: 0.4260 - acc: 0.8049
Epoch 10/120
8000/8000 [==============================] - 1s 93us/sample - loss: 0.42

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [148]:
y_pred = ann.predict(X_test)
y_pred

array([[0.3076911 ],
       [0.2704481 ],
       [0.13251925],
       ...,
       [0.0858717 ],
       [0.20042261],
       [0.22697765]], dtype=float32)

In [149]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

# Criando uma Confusion Matrix

In [18]:
# Com test size 0.2

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1519   76]
 [ 200  205]]


In [22]:
# Com test size 0.3

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[2251  128]
 [ 303  318]]


In [66]:
# Com MaxMinScaler

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1517   78]
 [ 202  203]]


In [51]:
# Sem usar activation nas camadas

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1533   62]
 [ 313   92]]


In [80]:
# Usando tanh nas camadas

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1512   83]
 [ 191  214]]


In [94]:
# Usando somente sigmoid

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1511   84]
 [ 189  216]]


In [108]:
# Usando sigmoid e SGD

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1520   75]
 [ 304  101]]


In [122]:
# Usando RMSProp, batch de 16 e 120 epochs

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1513   82]
 [ 204  201]]


In [136]:
# Usando tanh, batch de 16

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1522   73]
 [ 199  206]]


In [150]:
# Usando sigmoid e batch de 16

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1507   88]
 [ 194  211]]


In [ ]:
# usando test_size: 0.3 - Pior resultado
# com MinMaxScaler - Pior resultado
# sem utilizar activation - Melhor resultado para uma variavel. Pessimo resultado com a outra
# usando tanh - Pior resultado para uma variavel. Melhor para outra
# usando sigmoid - Melhor resultado no geral
# usando tanto sigmoid quanto sgd - Pior resultado 
# RMSProp, batch de 16 e 120epochs - Resultado razoavel
# tanh e batch de 16 - segundo melhor resultado



# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)