# REDES NEURAIS ARTIFICIAIS

[Aula 3 de Deep Learning](http://bit.ly/dn-unb03) da Engenharia de Software da UnB

# Parte 1 - Pré-processamento dos Dados

### Importar as libs

In [250]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [251]:
tf.__version__

'2.5.0'

### Importar o dataset

In [252]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [253]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


### Transformando os dados categóricos


In [254]:
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)


[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [255]:
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [256]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42)

# Feature Scaling

In [257]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [258]:
np.shape(X_train)

(7500, 12)

In [259]:
X_train

array([[ 1.00053348, -0.57776083, -0.57735027, ..., -1.53973586,
         0.96978946, -1.38284424],
       [-0.99946681,  1.73082   , -0.57735027, ...,  0.64946204,
        -1.03115165, -1.19589044],
       [ 1.00053348, -0.57776083, -0.57735027, ..., -1.53973586,
        -1.03115165, -0.68342242],
       ...,
       [ 1.00053348, -0.57776083, -0.57735027, ..., -1.53973586,
        -1.03115165, -0.14675423],
       [ 1.00053348, -0.57776083, -0.57735027, ...,  0.64946204,
        -1.03115165, -0.0548954 ],
       [-0.99946681,  1.73082   , -0.57735027, ...,  0.64946204,
         0.96978946, -0.81796934]])

---
# Parte 2 -Vamos construir uma ANN!


### Initializing the ANN

In [260]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [261]:
ann.add(tf.keras.layers.Dense(units=6, activation='tanh'))

### Adding the second hidden layer

In [262]:
ann.add(tf.keras.layers.Dense(units=6, activation='tanh'))

### Adding the output layer

In [263]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [264]:
ann.compile(optimizer = 'RMSprop', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [265]:
ann.fit(X_train, y_train, batch_size = 20, epochs = 125)

Epoch 1/125
375/375 [==============================] - 2s 3ms/step - loss: 0.5728 - accuracy: 0.7291
Epoch 2/125
375/375 [==============================] - 1s 2ms/step - loss: 0.4441 - accuracy: 0.8119
Epoch 3/125
375/375 [==============================] - 1s 2ms/step - loss: 0.4231 - accuracy: 0.8165
Epoch 4/125
375/375 [==============================] - 1s 2ms/step - loss: 0.4162 - accuracy: 0.8211
Epoch 5/125
375/375 [==============================] - 1s 4ms/step - loss: 0.4109 - accuracy: 0.8236
Epoch 6/125
375/375 [==============================] - 1s 2ms/step - loss: 0.4059 - accuracy: 0.8259
Epoch 7/125
375/375 [==============================] - 1s 2ms/step - loss: 0.4015 - accuracy: 0.8287
Epoch 8/125
375/375 [==============================] - 1s 3ms/step - loss: 0.3963 - accuracy: 0.8315
Epoch 9/125
375/375 [==============================] - 1s 2ms/step - loss: 0.3904 - accuracy: 0.8328
Epoch 10/125
375/375 [==============================] - 2s 6ms/step - loss: 0.3837 - accura

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [266]:
y_pred = ann.predict(X_test)
y_pred

array([[0.04436556],
       [0.02268645],
       [0.12203491],
       ...,
       [0.01656151],
       [0.09845152],
       [0.03241175]], dtype=float32)

In [267]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

# Criando uma Confusion Matrix

In [268]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1887  116]
 [ 233  264]]


# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)