# REDES NEURAIS ARTIFICIAIS

[Aula 3 de Deep Learning](http://bit.ly/dn-unb03) da Engenharia de Software da UnB

# Parte 1 - Pré-processamento dos Dados

### Importar as libs

In [8]:
!pip3 install -r requirements.txt

Defaulting to user installation because normal site-packages is not writeable
  Using cached numpy-1.16.2-cp36-cp36m-manylinux1_x86_64.whl (17.3 MB)
  Using cached pandas-0.24.2-cp36-cp36m-manylinux1_x86_64.whl (10.1 MB)
  Using cached matplotlib-3.0.3-cp36-cp36m-manylinux1_x86_64.whl (13.0 MB)
     |████████████████████████████████| 320.4 MB 13 kB/s  eta 0:00:01    |█▏                              | 11.3 MB 1.7 MB/s eta 0:03:07     |██▉                             | 28.5 MB 111 kB/s eta 0:43:39     |█████▌                          | 54.9 MB 2.0 MB/s eta 0:02:13     |█████▉                          | 58.1 MB 3.2 MB/s eta 0:01:22     |███████▋                        | 75.7 MB 1.7 MB/s eta 0:02:23     |███████████████████▎            | 193.5 MB 2.0 MB/s eta 0:01:02     |███████████████████▊            | 198.0 MB 1.3 MB/s eta 0:01:34     |████████████████████████████▊   | 287.2 MB 7.8 MB/s eta 0:00:05
     |████████████████████████████████| 459 kB 3.3 MB/s eta 0:00:01


  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.5
    Uninstalling numpy-1.19.5:
      Successfully uninstalled numpy-1.19.5
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.4.0
    Uninstalling tensorflow-estimator-2.4.0:
      Successfully uninstalled tensorflow-estimator-2.4.0
  Attempting uninstall: tensorflow
    Found existing installation: tensorflow 2.4.1
    Uninstalling tensorflow-2.4.1:
      Successfully uninstalled tensorflow-2.4.1
  Attempting uninstall: pandas
    Found existing installation: pandas 0.25.3
    Uninstalling pandas-0.25.3:
      Successfully uninstalled pandas-0.25.3
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.3.4
    Uninstalling matplotlib-3.3.4:
      Successfully uninstalled matplotlib-3.3.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the followi

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.3.1'

### Importar o dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


### Transformando os dados categóricos


In [5]:
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [6]:
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
X_train[1]

array([-1.01460667,  1.75486502, -0.57369368, -2.30455945,  0.91601335,
        0.30102557, -1.37744033, -0.00631193, -0.92159124,  0.64259497,
        0.9687384 , -0.74866447])

In [11]:
np.shape(X_train)

(8000, 12)

In [12]:
np.shape(X_test)

(2000, 12)

---
# Parte 2 -Vamos construir uma ANN!


### Initializing the ANN

In [67]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [74]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [75]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [76]:
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='sigmoid'))

### Adding the output layer

In [77]:
ann.add(tf.keras.layers.Dense(units=1, activation='tanh'))

## Part 3 - Training the ANN

### Compiling the ANN

In [78]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [79]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 767us/step - loss: 0.5202 - accuracy: 0.7820
Epoch 2/100
250/250 [==============================] - 0s 842us/step - loss: 0.4544 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 929us/step - loss: 0.4276 - accuracy: 0.7958
Epoch 4/100
250/250 [==============================] - 0s 995us/step - loss: 0.4199 - accuracy: 0.7964
Epoch 5/100
250/250 [==============================] - 0s 987us/step - loss: 0.4162 - accuracy: 0.7999
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4126 - accuracy: 0.8073
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3952 - accuracy: 0.8194
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4021 - accuracy: 0.8265
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3815 - accuracy: 0.8281
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.378

250/250 [==============================] - 0s 1ms/step - loss: 0.3386 - accuracy: 0.8601
Epoch 82/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3356 - accuracy: 0.8644
Epoch 83/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3364 - accuracy: 0.8629
Epoch 84/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3363 - accuracy: 0.8624
Epoch 85/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3562 - accuracy: 0.8626
Epoch 86/100
250/250 [==============================] - 0s 995us/step - loss: 0.3532 - accuracy: 0.8626
Epoch 87/100
250/250 [==============================] - 0s 975us/step - loss: 0.3366 - accuracy: 0.8630
Epoch 88/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3354 - accuracy: 0.8630
Epoch 89/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3369 - accuracy: 0.8631
Epoch 90/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3405 - accura

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [80]:
y_pred = ann.predict(X_test)
y_pred

array([[0.18795148],
       [0.2864279 ],
       [0.14007875],
       ...,
       [0.18027775],
       [0.13552566],
       [0.1635749 ]], dtype=float32)

In [81]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

# Criando uma Confusion Matrix

In [82]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1539   56]
 [ 220  185]]


In [83]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred, target_names=['não deixa', 'deixa']))

              precision    recall  f1-score   support

   não deixa       0.87      0.96      0.92      1595
       deixa       0.77      0.46      0.57       405

    accuracy                           0.86      2000
   macro avg       0.82      0.71      0.75      2000
weighted avg       0.85      0.86      0.85      2000



### Gerando metricas a partir dos metodos do keras

In [84]:
# evaluate the model
loss, accuracy = ann.evaluate(X_test, y_test, verbose=0)

In [85]:
accuracy

0.8619999885559082

# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)