# REDES NEURAIS ARTIFICIAIS

[Aula 3 de Deep Learning](http://bit.ly/dn-unb03) da Engenharia de Software da UnB

# Parte 1 - Pré-processamento dos Dados

### Importar as libs

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.4.1'

### Importar o dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


### Transformando os dados categóricos


In [5]:
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]
[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
np.shape(X_train)

(8000, 12)

---
# Parte 2 -Vamos construir uma ANN!


### Initializing the ANN

In [9]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units=6, activation='swish'))

### Adding the second hidden layer

In [11]:
ann.add(tf.keras.layers.Dense(units=6, activation='swish'))

### Adding the output layer

In [12]:
ann.add(tf.keras.layers.Dense(units=1, activation='relu'))

## Part 3 - Training the ANN

### Compiling the ANN

In [13]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [14]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 469us/step - loss: 1.3238 - accuracy: 0.7856
Epoch 2/100
250/250 [==============================] - 0s 448us/step - loss: 0.8655 - accuracy: 0.7817
Epoch 3/100
250/250 [==============================] - 0s 456us/step - loss: 0.7565 - accuracy: 0.7860
Epoch 4/100
250/250 [==============================] - 0s 435us/step - loss: 0.6782 - accuracy: 0.7769
Epoch 5/100
250/250 [==============================] - 0s 481us/step - loss: 0.6741 - accuracy: 0.7332
Epoch 6/100
250/250 [==============================] - 0s 463us/step - loss: 0.6665 - accuracy: 0.7272
Epoch 7/100
250/250 [==============================] - 0s 453us/step - loss: 0.6334 - accuracy: 0.7351
Epoch 8/100
250/250 [==============================] - 0s 449us/step - loss: 0.6143 - accuracy: 0.7356
Epoch 9/100
250/250 [==============================] - 0s 432us/step - loss: 0.6215 - accuracy: 0.7280
Epoch 10/100
250/250 [==============================] - 0s 456us/step - l

250/250 [==============================] - 0s 486us/step - loss: 0.3602 - accuracy: 0.8536
Epoch 80/100
250/250 [==============================] - 0s 473us/step - loss: 0.3571 - accuracy: 0.8612
Epoch 81/100
250/250 [==============================] - 0s 408us/step - loss: 0.3562 - accuracy: 0.8558
Epoch 82/100
250/250 [==============================] - 0s 453us/step - loss: 0.3582 - accuracy: 0.8534
Epoch 83/100
250/250 [==============================] - 0s 449us/step - loss: 0.3615 - accuracy: 0.8563
Epoch 84/100
250/250 [==============================] - 0s 455us/step - loss: 0.3647 - accuracy: 0.8567
Epoch 85/100
250/250 [==============================] - 0s 452us/step - loss: 0.3530 - accuracy: 0.8623
Epoch 86/100
250/250 [==============================] - 0s 450us/step - loss: 0.3640 - accuracy: 0.8538
Epoch 87/100
250/250 [==============================] - 0s 465us/step - loss: 0.3546 - accuracy: 0.8572
Epoch 88/100
250/250 [==============================] - 0s 453us/step - loss:

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [15]:
y_pred = ann.predict(X_test)
y_pred

array([[0.2658307 ],
       [0.3349145 ],
       [0.27274677],
       ...,
       [0.11698997],
       [0.13377765],
       [0.21475975]], dtype=float32)

In [16]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

# Criando uma Confusion Matrix

In [17]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

total_linhas = (
        cm[0][0]
        + cm[1][1]
        + cm[0][1]
        + cm[1][0])
predicoes_corretas = cm[0][0] + cm[1][1]
porcentagem_acertos = (predicoes_corretas * 100)  / total_linhas
print(f'Porcentagem acerto: {porcentagem_acertos}')

[[1527   68]
 [ 203  202]]
Porcentagem acerto: 86.45


# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)