# REDES NEURAIS ARTIFICIAIS

[Aula 3 de Deep Learning](http://bit.ly/dn-unb03) da Engenharia de Software da UnB

In [3]:
# Installing Theano
! pip3 install --upgrade --no-deps git+git://github.com/Theano/Theano.git --user

# Installing Tensorflow
! pip3 install --upgrade tensorflow --user

# Installing Keras
! pip3 install --upgrade keras --user

# Install other packages
! pip3 install --upgrade pip pandas numpy matplotlib sklearn --user

  Cloning git://github.com/Theano/Theano.git to /tmp/pip-req-build-t25sj9_2
  Running command git clone -q git://github.com/Theano/Theano.git /tmp/pip-req-build-t25sj9_2
  Created wheel for Theano: filename=Theano-1.0.4+21.g8f510a1f0-cp36-none-any.whl size=2667496 sha256=c0efe54a0d1df8de8fc0f220ac90e55abb620b25ac4578cdacdbbd15f0a5b652
  Stored in directory: /tmp/pip-ephem-wheel-cache-hssx2kv1/wheels/ae/32/7c/62beb8371953eb20c271b3bac7d0e56e1a2020d46994346b52
Successfully built Theano
  Found existing installation: Theano 1.0.4+21.g8f510a1f0
    Uninstalling Theano-1.0.4+21.g8f510a1f0:
      Successfully uninstalled Theano-1.0.4+21.g8f510a1f0
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Requirement already up-to-date: tensorflow in /root/.local/lib/python3.6/site-packages (2.0.0)
Requirement already up-to-date: keras in /root/.local/lib/python3.6/site-packages (2.3.1)
Requirement already up-to-date: pip in /usr/local

# Parte 1 - Preprocessamento dos Dados

In [0]:
! pip freeze > requirements.txt

### Importar as libs

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Importar o dataset

In [6]:
dataset = pd.read_csv('https://raw.githubusercontent.com/deeplearningunb/building-ann/master/Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [7]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


### Transformando os dados categóricos


In [8]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]
print("X >>\n",X)

X >>
 [[0.0000000e+00 0.0000000e+00 6.1900000e+02 ... 1.0000000e+00
  1.0000000e+00 1.0134888e+05]
 [0.0000000e+00 1.0000000e+00 6.0800000e+02 ... 0.0000000e+00
  1.0000000e+00 1.1254258e+05]
 [0.0000000e+00 0.0000000e+00 5.0200000e+02 ... 1.0000000e+00
  0.0000000e+00 1.1393157e+05]
 ...
 [0.0000000e+00 0.0000000e+00 7.0900000e+02 ... 0.0000000e+00
  1.0000000e+00 4.2085580e+04]
 [1.0000000e+00 0.0000000e+00 7.7200000e+02 ... 1.0000000e+00
  0.0000000e+00 9.2888520e+04]
 [0.0000000e+00 0.0000000e+00 7.9200000e+02 ... 1.0000000e+00
  0.0000000e+00 3.8190780e+04]]


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
np.shape(X_train)

(8000, 11)

---
# Parte 2 -Vamos construir uma ANN!

## Importando o Keras


In [0]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [0]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'selu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Ajustando a ANN ao conjunto de treinamento

In [14]:
classifier.fit(X_train, y_train, batch_size = 128, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 1s 77us/step - loss: 0.6778 - accuracy: 0.7879
Epoch 2/100
8000/8000 [==============================] - 0s 11us/step - loss: 0.5942 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 0s 11us/step - loss: 0.4795 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 0s 12us/step - loss: 0.4464 - accuracy: 0.7960
Epoch 5/100
8000/8000 [==============================] - 0s 14us/step - loss: 0.4388 - accuracy: 0.7960
Epoch 6/100
8000/8000 [==============================] - 0s 12us/step - loss: 0.4349 - accuracy: 0.7960
Epoch 7/100
8000/8000 [==============================] - 0s 12us/step - loss: 0.4322 - accuracy: 0.7960
Epoch 8/100
8000/8000 [==============================] - 0s 11us/step - loss: 0.4304 - accuracy: 0.7960
Epoch 9/100
8000/8000 [==============================] - 0s 12us/step - loss: 0.4290 - accuracy: 0.7960
Epoch 10/100
8000/8000 [==============================] - 0s 12u

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [0]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Criando uma Confusion Matrix

In [16]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1552   43]
 [ 275  130]]


# Initiate activation function experimentation

# Initialising the 2nd ANN

In [17]:
del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'tanh'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 128, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 0s 26us/step - loss: 0.5253 - accuracy: 0.7960
Epoch 2/100
8000/8000 [==============================] - 0s 11us/step - loss: 0.5008 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 0s 11us/step - loss: 0.4897 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 0s 11us/step - loss: 0.4738 - accuracy: 0.7960
Epoch 5/100
8000/8000 [==============================] - 0s 11us/step - loss: 0.4573 - accuracy: 0.7960
Epoch 6/100
8000/8000 [==============================] - 0s 11us/step - loss: 0.4426 - accuracy: 0.7960
Epoch 7/100
8000/8000 [==============================] - 0s 14us/step - loss: 0.4323 - accuracy: 0.7960
Epoch 8/100
8000/8000 [==============================] - 0s 12us/step - loss: 0.4272 - accuracy: 0.7960
Epoch 9/100
8000/8000 [==============================] - 0s 11us/step - loss: 0.4237 - accuracy: 0.7961
Epoch 10/100
8000/8000 [==============================] - 0s 11u

In [0]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix

In [19]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1509   86]
 [ 205  200]]


# Initialising the 3rd ANN

In [20]:
del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'selu'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 128, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 0s 23us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 2/100
8000/8000 [==============================] - 0s 11us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 0s 11us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 0s 11us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 5/100
8000/8000 [==============================] - 0s 11us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 6/100
8000/8000 [==============================] - 0s 11us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 7/100
8000/8000 [==============================] - 0s 12us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 8/100
8000/8000 [==============================] - 0s 12us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 9/100
8000/8000 [==============================] - 0s 12us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 10/100
8000/8000 [==============================] - 0s 12u

In [0]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix

In [22]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1595    0]
 [ 405    0]]


---
# Parte 4 - Evaluating, Improving and Tuning the ANN

## Evaluating the ANN

In [0]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'selu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()

In [24]:
print("accuracies:{}\nmean:{}\nvariance:{}".format(accuracies, mean, variance))

accuracies:[0.83625001 0.83875    0.83249998 0.82875001 0.85000002 0.83125001
 0.83625001 0.82875001 0.8125     0.84625   ]
mean:0.8341250061988831
variance:0.009827419498278325


# Improving the ANN
# Dropout Regularization to reduce overfitting if needed

In [0]:
from keras.layers import Dropout

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()

In [26]:
print("accuracies:{}\nmean:{}\nvariance:{}".format(accuracies, mean, variance))

accuracies:[0.82875001 0.82999998 0.83249998 0.81625003 0.84249997 0.81
 0.82875001 0.8125     0.82499999 0.83375001]
mean:0.8259999990463257
variance:0.00969535154448424


# Tuning the ANN

In [0]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense

def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'selu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier)

In [28]:
parameters = {'batch_size': [128, 256],
              'epochs': [50],
              'optimizer': ['adam', 'rmsprop']}

grid_search = GridSearchCV(estimator = classifier,
                           scoring = 'accuracy',
                           param_grid = parameters,
                           cv = 10)

grid_search = grid_search.fit(X_train, y_train)

best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_


7200/7200 [==============================] - 0s 7us/step - loss: 0.4454 - accuracy: 0.7937
Epoch 13/50
7200/7200 [==============================] - 0s 6us/step - loss: 0.4444 - accuracy: 0.7937
Epoch 14/50
7200/7200 [==============================] - 0s 7us/step - loss: 0.4387 - accuracy: 0.7937
Epoch 15/50
7200/7200 [==============================] - 0s 7us/step - loss: 0.4405 - accuracy: 0.7937
Epoch 16/50
7200/7200 [==============================] - 0s 7us/step - loss: 0.4380 - accuracy: 0.7937
Epoch 17/50
7200/7200 [==============================] - 0s 7us/step - loss: 0.4383 - accuracy: 0.7937
Epoch 18/50
7200/7200 [==============================] - 0s 6us/step - loss: 0.4354 - accuracy: 0.7937
Epoch 19/50
7200/7200 [==============================] - 0s 7us/step - loss: 0.4355 - accuracy: 0.7937
Epoch 20/50
7200/7200 [==============================] - 0s 7us/step - loss: 0.4339 - accuracy: 0.7937
Epoch 21/50
7200/7200 [==============================] - 0s 7us/step - loss: 0.4330 -

In [29]:
print('Melhores Parametros {}\n Melhor Acuracia:{}'.format(best_parameters, best_accuracy))

Melhores Parametros {'batch_size': 128, 'epochs': 50, 'optimizer': 'rmsprop'}
 Melhor Acuracia:0.833125


# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)