# REDES NEURAIS ARTIFICIAIS

[Aula 3 de Deep Learning](http://bit.ly/dn-unb03) da Engenharia de Software da UnB

In [14]:
# Installing Theano
! pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
! pip install --upgrade tensorflow

# Installing Keras
! pip install --upgrade keras
! pip3 install keras

# Install other packages
! pip install --upgrade pip pandas numpy matplotlib sklearn

  Cloning git://github.com/Theano/Theano.git to /private/var/folders/_b/llxvvc0j6gv_kyt5t63q233r0000gn/T/pip-req-build-m08tf19d
  Running command git clone -q git://github.com/Theano/Theano.git /private/var/folders/_b/llxvvc0j6gv_kyt5t63q233r0000gn/T/pip-req-build-m08tf19d
  Created wheel for Theano: filename=Theano-1.0.4+21.g8f510a1f0-cp37-none-any.whl size=2667497 sha256=acb749c746cbb226bd7d4bff6abb088d3a8f85bd997e48e575d54cf687e8e967
  Stored in directory: /private/var/folders/_b/llxvvc0j6gv_kyt5t63q233r0000gn/T/pip-ephem-wheel-cache-nlnh26yb/wheels/ae/32/7c/62beb8371953eb20c271b3bac7d0e56e1a2020d46994346b52
Successfully built Theano
  Found existing installation: Theano 1.0.4+21.g8f510a1f0
    Uninstalling Theano-1.0.4+21.g8f510a1f0:
      Successfully uninstalled Theano-1.0.4+21.g8f510a1f0
     |████████████████████████████████| 102.7MB 140kB/s eta 0:00:01   |██▎                             | 7.4MB 421kB/s eta 0:03:47     |█████▌                          | 17.6MB 815kB/s eta 0:01:

Requirement already up-to-date: pip in ./venv/lib/python3.7/site-packages (19.2.3)
Requirement already up-to-date: pandas in ./venv/lib/python3.7/site-packages (0.25.1)
Requirement already up-to-date: numpy in ./venv/lib/python3.7/site-packages (1.17.2)
Requirement already up-to-date: matplotlib in ./venv/lib/python3.7/site-packages (3.1.1)
Requirement already up-to-date: sklearn in ./venv/lib/python3.7/site-packages (0.0)


! sudo python3 -m pip install tensorflow

# Parte 1 - Preprocessamento dos Dados

### Importar as libs

In [15]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Importar o dataset

In [16]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
z = dataset.head()
print("Z >>\n",z)
print("\n\n\n\nX >>\n",X)
print("y >>\n",y)

Z >>
    RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4      

### Transformando os dados categóricos


In [17]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
print("X >>\n",X)
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
print("X >>\n",X)
X = onehotencoder.fit_transform(X).toarray()
print("X >>\n",X)
X = X[:, 1:]
print("X >>\n",X)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
X >>
 [[619 0 0 ... 1 1 101348.88]
 [608 2 0 ... 0 1 112542.58]
 [502 0 0 ... 1 0 113931.57]
 ...
 [709 0 0 ... 0 1 42085.58]
 [772 1 1 ... 1 0 92888.52]
 [792 0 0 ... 1 0 38190.78]]
X >>
 [[1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  1.0000000e+00 1.0134888e+05]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00 ... 0.0000000e+00
  1.0000000e+00 1.1254258e+05]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 1.1393157e+05]
 ...
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  1.0000000e+00 4.2085580e+04]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 9.2888520e+04]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+0

/Users/caiofernandes/Desktop/Projetos/DeepLearning/BuildingAnn/building-ann/venv/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/Users/caiofernandes/Desktop/Projetos/DeepLearning/BuildingAnn/building-ann/venv/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", Depr

# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

---
# Parte 2 -Vamos construir uma ANN!

## Importando o Keras


In [20]:
import tensorflow
import keras
from keras.models import Sequential
from keras.layers import Dense #Camada de neuronios

Using TensorFlow backend.


In [23]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Ajustando a ANN ao conjunto de treinamento

In [24]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.5283 - accuracy: 0.7933
Epoch 2/100
8000/8000 [==============================] - 1s 127us/step - loss: 0.4795 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 133us/step - loss: 0.4651 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 126us/step - loss: 0.4520 - accuracy: 0.79600s - loss: 0.4550 - accu
Epoch 5/100
8000/8000 [==============================] - 1s 118us/step - loss: 0.4421 - accuracy: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 126us/step - loss: 0.4357 - accuracy: 0.7960
Epoch 7/100
8000/8000 [==============================] - 1s 148us/step - loss: 0.4322 - accuracy: 0.7960
Epoch 8/100
8000/8000 [==============================] - 1s 139us/step - loss: 0.4306 - accuracy: 0.7960
Epoch 9/100
8000/8000 [==============================] - 1s 131us/step - loss: 0.4297 - accuracy: 0.7960
Epoch 10/100
8000/8000 [=======

8000/8000 [==============================] - 1s 146us/step - loss: 0.4000 - accuracy: 0.8345
Epoch 78/100
8000/8000 [==============================] - 1s 142us/step - loss: 0.3999 - accuracy: 0.8347
Epoch 79/100
8000/8000 [==============================] - 2s 201us/step - loss: 0.3996 - accuracy: 0.8344
Epoch 80/100
8000/8000 [==============================] - 2s 230us/step - loss: 0.3996 - accuracy: 0.8363
Epoch 81/100
8000/8000 [==============================] - 1s 172us/step - loss: 0.3995 - accuracy: 0.8345
Epoch 82/100
8000/8000 [==============================] - 1s 168us/step - loss: 0.3991 - accuracy: 0.8354
Epoch 83/100
8000/8000 [==============================] - 2s 191us/step - loss: 0.3991 - accuracy: 0.8355
Epoch 84/100
8000/8000 [==============================] - 1s 167us/step - loss: 0.3989 - accuracy: 0.8349
Epoch 85/100
8000/8000 [==============================] - 1s 137us/step - loss: 0.3988 - accuracy: 0.83550s - loss: 0.3988 - accura
Epoch 86/100
8000/8000 [=========

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [25]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Criando uma Confusion Matrix

In [26]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1540   55]
 [ 260  145]]


# Initiate activation function experimentation

# Initialising the 2nd ANN

In [27]:
del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 1s 139us/step - loss: 0.5196 - accuracy: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 126us/step - loss: 0.4801 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 132us/step - loss: 0.4652 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 137us/step - loss: 0.4519 - accuracy: 0.7960
Epoch 5/100
8000/8000 [==============================] - 1s 135us/step - loss: 0.4418 - accuracy: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 135us/step - loss: 0.4356 - accuracy: 0.7960
Epoch 7/100
8000/8000 [==============================] - 1s 140us/step - loss: 0.4322 - accuracy: 0.7960
Epoch 8/100
8000/8000 [==============================] - 1s 144us/step - loss: 0.4303 - accuracy: 0.7960
Epoch 9/100
8000/8000 [==============================] - 1s 139us/step - loss: 0.4296 - accuracy: 0.7960
Epoch 10/100
8000/8000 [==============================]

8000/8000 [==============================] - 1s 148us/step - loss: 0.3981 - accuracy: 0.8361
Epoch 78/100
8000/8000 [==============================] - 1s 133us/step - loss: 0.3981 - accuracy: 0.8347
Epoch 79/100
8000/8000 [==============================] - 1s 135us/step - loss: 0.3980 - accuracy: 0.8347
Epoch 80/100
8000/8000 [==============================] - 1s 145us/step - loss: 0.3978 - accuracy: 0.8340
Epoch 81/100
8000/8000 [==============================] - 1s 178us/step - loss: 0.3975 - accuracy: 0.8350
Epoch 82/100
8000/8000 [==============================] - 1s 174us/step - loss: 0.3974 - accuracy: 0.8344
Epoch 83/100
8000/8000 [==============================] - 1s 160us/step - loss: 0.3973 - accuracy: 0.8354
Epoch 84/100
8000/8000 [==============================] - 1s 152us/step - loss: 0.3971 - accuracy: 0.8346
Epoch 85/100
8000/8000 [==============================] - 1s 161us/step - loss: 0.3971 - accuracy: 0.8339
Epoch 86/100
8000/8000 [==============================] - 1

In [14]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix

In [15]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1595    0]
 [ 405    0]]


# Initialising the 3rd ANN

In [16]:
del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 1s 154us/step - loss: 0.6138 - accuracy: 0.79501s
Epoch 2/100
8000/8000 [==============================] - 1s 119us/step - loss: 0.5336 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 129us/step - loss: 0.5116 - accuracy: 0.79600s - loss: 0.5109 - accuracy: 
Epoch 4/100
8000/8000 [==============================] - 1s 131us/step - loss: 0.5069 - accuracy: 0.79600s - loss: 0.5048 - accura
Epoch 5/100
8000/8000 [==============================] - 1s 132us/step - loss: 0.5061 - accuracy: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 130us/step - loss: 0.5060 - accuracy: 0.7960
Epoch 7/100
8000/8000 [==============================] - 1s 131us/step - loss: 0.5060 - accuracy: 0.7960
Epoch 8/100
8000/8000 [==============================] - 1s 138us/step - loss: 0.5059 - accuracy: 0.79600s -
Epoch 9/100
8000/8000 [==============================] - 1s 134us/step - loss: 0.5060 - accuracy: 

In [28]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix

In [29]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1531   64]
 [ 247  158]]


---
# Parte 4 - Evaluating, Improving and Tuning the ANN

## Evaluating the ANN

In [30]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()
print("accuracies: %s\n mean: %s\n variance: %s".format(accuracies, mean, variance))

accuracies: %s
 mean: %s
 variance: %s


# Improving the ANN
# Dropout Regularization to reduce overfitting if needed

In [31]:
from keras.layers import Dropout

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()

# Tuning the ANN

In [32]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense

def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier)

In [33]:
parameters = {'batch_size': [10, 10, 10],
              'epochs': [10, 15, 20],
              'optimizer': ['adam', 'rmsprop']}

grid_search = GridSearchCV(estimator = classifier,
                           scoring = 'accuracy',
                           param_grid = parameters,
                           cv = 2)

grid_search = grid_search.fit(X_train, y_train)

best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

Epoch 1/10
4000/4000 [==============================] - 1s 224us/step - loss: 0.5542 - accuracy: 0.7930
Epoch 2/10
4000/4000 [==============================] - 1s 152us/step - loss: 0.4931 - accuracy: 0.7970
Epoch 3/10
4000/4000 [==============================] - 1s 158us/step - loss: 0.4869 - accuracy: 0.79700s - loss: 0.4896 - accuracy: 
Epoch 4/10
4000/4000 [==============================] - 1s 160us/step - loss: 0.4815 - accuracy: 0.7970
Epoch 5/10
4000/4000 [==============================] - 1s 167us/step - loss: 0.4753 - accuracy: 0.7970
Epoch 6/10
4000/4000 [==============================] - 1s 165us/step - loss: 0.4691 - accuracy: 0.7970
Epoch 7/10
4000/4000 [==============================] - 1s 168us/step - loss: 0.4660 - accuracy: 0.7970
Epoch 8/10
4000/4000 [==============================] - 1s 156us/step - loss: 0.4594 - accuracy: 0.7970
Epoch 9/10
4000/4000 [==============================] - 1s 167us/step - loss: 0.4541 - accuracy: 0.7970
Epoch 10/10
4000/4000 [===========

4000/4000 [==============================] - 1s 164us/step - loss: 0.4588 - accuracy: 0.7970
Epoch 10/15
4000/4000 [==============================] - 1s 157us/step - loss: 0.4560 - accuracy: 0.7970
Epoch 11/15
4000/4000 [==============================] - 1s 155us/step - loss: 0.4520 - accuracy: 0.7970
Epoch 12/15
4000/4000 [==============================] - 1s 170us/step - loss: 0.4484 - accuracy: 0.79700s - loss: 0.4442 - ac
Epoch 13/15
4000/4000 [==============================] - 1s 161us/step - loss: 0.4476 - accuracy: 0.79720s - loss: 0.4411 - ac
Epoch 14/15
4000/4000 [==============================] - 1s 143us/step - loss: 0.4443 - accuracy: 0.7970
Epoch 15/15
4000/4000 [==============================] - 1s 143us/step - loss: 0.4411 - accuracy: 0.7970
Epoch 1/15
4000/4000 [==============================] - 1s 253us/step - loss: 0.5569 - accuracy: 0.7908
Epoch 2/15
4000/4000 [==============================] - 1s 162us/step - loss: 0.5007 - accuracy: 0.7950
Epoch 3/15
4000/4000 [===

4000/4000 [==============================] - 1s 139us/step - loss: 0.4399 - accuracy: 0.7972
Epoch 17/20
4000/4000 [==============================] - 1s 144us/step - loss: 0.4408 - accuracy: 0.79700s - loss: 0.4329 - accura
Epoch 18/20
4000/4000 [==============================] - 1s 133us/step - loss: 0.4382 - accuracy: 0.7970
Epoch 19/20
4000/4000 [==============================] - 1s 139us/step - loss: 0.4384 - accuracy: 0.7970
Epoch 20/20
4000/4000 [==============================] - 1s 142us/step - loss: 0.4352 - accuracy: 0.79720s - loss: 0.4223 
Epoch 1/20
4000/4000 [==============================] - 1s 204us/step - loss: 0.5543 - accuracy: 0.7947
Epoch 2/20
4000/4000 [==============================] - 1s 146us/step - loss: 0.5002 - accuracy: 0.7950
Epoch 3/20
4000/4000 [==============================] - 1s 144us/step - loss: 0.4939 - accuracy: 0.7950
Epoch 4/20
4000/4000 [==============================] - 1s 144us/step - loss: 0.4869 - accuracy: 0.7950
Epoch 5/20
4000/4000 [=====

4000/4000 [==============================] - 1s 155us/step - loss: 0.4413 - accuracy: 0.7970
Epoch 14/15
4000/4000 [==============================] - 1s 150us/step - loss: 0.4379 - accuracy: 0.7970
Epoch 15/15
4000/4000 [==============================] - 1s 147us/step - loss: 0.4409 - accuracy: 0.7970
Epoch 1/15
4000/4000 [==============================] - 1s 212us/step - loss: 0.5609 - accuracy: 0.7890
Epoch 2/15
4000/4000 [==============================] - 1s 152us/step - loss: 0.4958 - accuracy: 0.7950
Epoch 3/15
4000/4000 [==============================] - 1s 153us/step - loss: 0.4904 - accuracy: 0.7950
Epoch 4/15
4000/4000 [==============================] - 1s 155us/step - loss: 0.4824 - accuracy: 0.7950
Epoch 5/15
4000/4000 [==============================] - 1s 150us/step - loss: 0.4754 - accuracy: 0.7950
Epoch 6/15
4000/4000 [==============================] - 1s 152us/step - loss: 0.4683 - accuracy: 0.7950
Epoch 7/15
4000/4000 [==============================] - 1s 162us/step - l

4000/4000 [==============================] - 1s 148us/step - loss: 0.4410 - accuracy: 0.7950
Epoch 12/20
4000/4000 [==============================] - 1s 157us/step - loss: 0.4404 - accuracy: 0.7950
Epoch 13/20
4000/4000 [==============================] - 1s 158us/step - loss: 0.4399 - accuracy: 0.7950
Epoch 14/20
4000/4000 [==============================] - 1s 149us/step - loss: 0.4348 - accuracy: 0.7947
Epoch 15/20
4000/4000 [==============================] - 1s 155us/step - loss: 0.4324 - accuracy: 0.7955
Epoch 16/20
4000/4000 [==============================] - 1s 151us/step - loss: 0.4338 - accuracy: 0.7952
Epoch 17/20
4000/4000 [==============================] - 1s 156us/step - loss: 0.4318 - accuracy: 0.79520s - loss: 0.4248 - accuracy
Epoch 18/20
4000/4000 [==============================] - 1s 155us/step - loss: 0.4310 - accuracy: 0.7935
Epoch 19/20
4000/4000 [==============================] - 1s 155us/step - loss: 0.4321 - accuracy: 0.7945
Epoch 20/20
4000/4000 [================

4000/4000 [==============================] - 1s 139us/step - loss: 0.4654 - accuracy: 0.7970
Epoch 9/10
4000/4000 [==============================] - 1s 137us/step - loss: 0.4619 - accuracy: 0.7970
Epoch 10/10
4000/4000 [==============================] - 1s 137us/step - loss: 0.4551 - accuracy: 0.79700s - loss: 0.4565 - accuracy: 
Epoch 1/10
4000/4000 [==============================] - 1s 201us/step - loss: 0.5510 - accuracy: 0.7950
Epoch 2/10
4000/4000 [==============================] - 1s 149us/step - loss: 0.4998 - accuracy: 0.7950
Epoch 3/10
4000/4000 [==============================] - 1s 147us/step - loss: 0.4932 - accuracy: 0.7950
Epoch 4/10
4000/4000 [==============================] - 1s 143us/step - loss: 0.4869 - accuracy: 0.7950
Epoch 5/10
4000/4000 [==============================] - 1s 140us/step - loss: 0.4792 - accuracy: 0.7950
Epoch 6/10
4000/4000 [==============================] - 1s 147us/step - loss: 0.4730 - accuracy: 0.7950
Epoch 7/10
4000/4000 [======================

4000/4000 [==============================] - 1s 144us/step - loss: 0.4705 - accuracy: 0.7970
Epoch 7/20
4000/4000 [==============================] - 1s 147us/step - loss: 0.4635 - accuracy: 0.7970
Epoch 8/20
4000/4000 [==============================] - 1s 148us/step - loss: 0.4615 - accuracy: 0.7970
Epoch 9/20
4000/4000 [==============================] - 1s 144us/step - loss: 0.4552 - accuracy: 0.7970
Epoch 10/20
4000/4000 [==============================] - 1s 145us/step - loss: 0.4464 - accuracy: 0.79700s - loss: 0.4461 - accuracy: 0.79
Epoch 11/20
4000/4000 [==============================] - 1s 148us/step - loss: 0.4476 - accuracy: 0.7970
Epoch 12/20
4000/4000 [==============================] - 1s 152us/step - loss: 0.4439 - accuracy: 0.7970
Epoch 13/20
4000/4000 [==============================] - 1s 156us/step - loss: 0.4407 - accuracy: 0.79700s - loss: 0.4399 - accuracy: 
Epoch 14/20
4000/4000 [==============================] - 1s 148us/step - loss: 0.4418 - accuracy: 0.7970
Epoch 

8000/8000 [==============================] - 1s 148us/step - loss: 0.4709 - accuracy: 0.7960
Epoch 4/10
8000/8000 [==============================] - 1s 146us/step - loss: 0.4597 - accuracy: 0.7960
Epoch 5/10
8000/8000 [==============================] - 1s 165us/step - loss: 0.4503 - accuracy: 0.7960
Epoch 6/10
8000/8000 [==============================] - 1s 151us/step - loss: 0.4431 - accuracy: 0.7960
Epoch 7/10
8000/8000 [==============================] - 1s 146us/step - loss: 0.4390 - accuracy: 0.7960
Epoch 8/10
8000/8000 [==============================] - 1s 147us/step - loss: 0.4367 - accuracy: 0.7959
Epoch 9/10
8000/8000 [==============================] - 1s 149us/step - loss: 0.4340 - accuracy: 0.7960
Epoch 10/10
8000/8000 [==============================] - 1s 150us/step - loss: 0.4364 - accuracy: 0.79610s - loss: 0.4364 - ac


# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)