# REDES NEURAIS ARTIFICIAIS

[Aula 3 de Deep Learning](http://bit.ly/dn-unb03) da Engenharia de Software da UnB

# Parte 1 - Pré-processamento dos Dados

### Importar as libs

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
%pip install -U scikit-learn

You should consider upgrading via the '/opt/homebrew/Cellar/jupyterlab/3.2.9/libexec/bin/python3.9 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [2]:
tf.__version__

'2.8.0'

### Importar o dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head(50)

RowNumber  CustomerId        Surname  CreditScore Geography  Gender  Age  \
0           1    15634602       Hargrave          619    France  Female   42   
1           2    15647311           Hill          608     Spain  Female   41   
2           3    15619304           Onio          502    France  Female   42   
3           4    15701354           Boni          699    France  Female   39   
4           5    15737888       Mitchell          850     Spain  Female   43   
5           6    15574012            Chu          645     Spain    Male   44   
6           7    15592531       Bartlett          822    France    Male   50   
7           8    15656148         Obinna          376   Germany  Female   29   
8           9    15792365             He          501    France    Male   44   
9          10    15592389             H?          684    France    Male   27   
10         11    15767821         Bearce          528    France    Male   31   
11         12    15737173        Andrews          497     Spain    Male   24   
12         13    15632264            Kay          476    France  Female   34   
13         14    15691483           Chin          549    France  Female   25   
14         15    15600882          Scott          635     Spain  Female   35   
15         16    15643966        Goforth          616   Germany    Male   45   
16         17    15737452          Romeo          653   Germany    Male   58   
17         18    15788218      Henderson          549     Spain  Female   24   
18         19    15661507        Muldrow          587     Spain    Male   45   
19         20    15568982            Hao          726    France  Female   24   
20         21    15577657       McDonald          732    France    Male   41   
21         22    15597945       Dellucci          636     Spain  Female   32   
22         23    15699309      Gerasimov          510     Spain  Female   38   
23         24    15725737         Mosman          669    France    Male   46   
24         25    15625047            Yen          846    France  Female   38   
25         26    15738191        Maclean          577    France    Male   25   
26         27    15736816          Young          756   Germany    Male   36   
27         28    15700772        Nebechi          571    France    Male   44   
28         29    15728693     McWilliams          574   Germany  Female   43   
29         30    15656300       Lucciano          411    France    Male   29   
30         31    15589475        Azikiwe          591     Spain  Female   39   
31         32    15706552  Odinakachukwu          533    France    Male   36   
32         33    15750181      Sanderson          553   Germany    Male   41   
33         34    15659428        Maggard          520     Spain  Female   42   
34         35    15732963       Clements          722     Spain  Female   29   
35         36    15794171       Lombardo          475    France  Female   45   
36         37    15788448         Watson          490     Spain    Male   31   
37         38    15729599        Lorenzo          804     Spain    Male   33   
38         39    15717426      Armstrong          850    France    Male   36   
39         40    15585768        Cameron          582   Germany    Male   41   
40         41    15619360          Hsiao          472     Spain    Male   40   
41         42    15738148         Clarke          465    France  Female   51   
42         43    15687946        Osborne          556    France  Female   61   
43         44    15755196         Lavine          834    France  Female   49   
44         45    15684171        Bianchi          660     Spain  Female   61   
45         46    15754849          Tyler          776   Germany  Female   32   
46         47    15602280         Martin          829   Germany  Female   27   
47         48    15771573        Okagbue          637   Germany  Female   39   
48         49    15766205            Yin          550   Germany    Male   38   
49  

In [4]:
dataset.Geography.value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [5]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


### Transformando os dados categóricos


In [6]:
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X[:, 2])

[0 0 0 ... 0 1 0]


In [7]:
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
np.shape(X_train)

(8000, 12)

In [11]:
X_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

---
# Parte 2 -Vamos construir uma ANN!


### Initializing the ANN

In [12]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='softmax'))

### Adding the second hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

### Compiling the ANN

In [16]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

## Part 3 - Training the ANN

### Training the ANN on the Training set

In [17]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 1000)

Epoch 1/1000
155/250 [=================>............] - ETA: 0s - loss: 0.6100 - accuracy: 0.7177 

2022-03-04 23:57:34.998381: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


250/250 [==============================] - 0s 316us/step - loss: 0.5735 - accuracy: 0.7460
Epoch 2/1000
250/250 [==============================] - 0s 300us/step - loss: 0.4765 - accuracy: 0.7960
Epoch 3/1000
250/250 [==============================] - 0s 504us/step - loss: 0.4431 - accuracy: 0.7961
Epoch 4/1000
250/250 [==============================] - 0s 297us/step - loss: 0.4224 - accuracy: 0.8159
Epoch 5/1000
250/250 [==============================] - 0s 293us/step - loss: 0.4101 - accuracy: 0.8195
Epoch 6/1000
250/250 [==============================] - 0s 294us/step - loss: 0.4020 - accuracy: 0.8220
Epoch 7/1000
250/250 [==============================] - 0s 296us/step - loss: 0.3935 - accuracy: 0.8254
Epoch 8/1000
250/250 [==============================] - 0s 294us/step - loss: 0.3843 - accuracy: 0.8386
Epoch 9/1000
250/250 [==============================] - 0s 295us/step - loss: 0.3742 - accuracy: 0.8465
Epoch 10/1000
250/250 [==============================] - 0s 294us/step - loss

250/250 [==============================] - 0s 298us/step - loss: 0.3349 - accuracy: 0.8634
Epoch 80/1000
250/250 [==============================] - 0s 295us/step - loss: 0.3342 - accuracy: 0.8624
Epoch 81/1000
250/250 [==============================] - 0s 292us/step - loss: 0.3349 - accuracy: 0.8630
Epoch 82/1000
250/250 [==============================] - 0s 291us/step - loss: 0.3347 - accuracy: 0.8630
Epoch 83/1000
250/250 [==============================] - 0s 292us/step - loss: 0.3345 - accuracy: 0.8627
Epoch 84/1000
250/250 [==============================] - 0s 294us/step - loss: 0.3346 - accuracy: 0.8630
Epoch 85/1000
250/250 [==============================] - 0s 295us/step - loss: 0.3346 - accuracy: 0.8620
Epoch 86/1000
250/250 [==============================] - 0s 291us/step - loss: 0.3343 - accuracy: 0.8631
Epoch 87/1000
250/250 [==============================] - 0s 293us/step - loss: 0.3347 - accuracy: 0.8621
Epoch 88/1000
250/250 [==============================] - 0s 301us/ste

250/250 [==============================] - 0s 296us/step - loss: 0.3333 - accuracy: 0.8639
Epoch 157/1000
250/250 [==============================] - 0s 299us/step - loss: 0.3334 - accuracy: 0.8634
Epoch 158/1000
250/250 [==============================] - 0s 304us/step - loss: 0.3333 - accuracy: 0.8630
Epoch 159/1000
250/250 [==============================] - 0s 305us/step - loss: 0.3334 - accuracy: 0.8631
Epoch 160/1000
250/250 [==============================] - 0s 300us/step - loss: 0.3330 - accuracy: 0.8644
Epoch 161/1000
250/250 [==============================] - 0s 295us/step - loss: 0.3331 - accuracy: 0.8648
Epoch 162/1000
250/250 [==============================] - 0s 295us/step - loss: 0.3333 - accuracy: 0.8633
Epoch 163/1000
250/250 [==============================] - 0s 298us/step - loss: 0.3331 - accuracy: 0.8637
Epoch 164/1000
250/250 [==============================] - 0s 303us/step - loss: 0.3332 - accuracy: 0.8631
Epoch 165/1000
250/250 [==============================] - 0s 

250/250 [==============================] - 0s 346us/step - loss: 0.3325 - accuracy: 0.8644
Epoch 234/1000
250/250 [==============================] - 0s 301us/step - loss: 0.3327 - accuracy: 0.8637
Epoch 235/1000
250/250 [==============================] - 0s 295us/step - loss: 0.3326 - accuracy: 0.8648
Epoch 236/1000
250/250 [==============================] - 0s 297us/step - loss: 0.3325 - accuracy: 0.8634
Epoch 237/1000
250/250 [==============================] - 0s 296us/step - loss: 0.3326 - accuracy: 0.8641
Epoch 238/1000
250/250 [==============================] - 0s 297us/step - loss: 0.3326 - accuracy: 0.8645
Epoch 239/1000
250/250 [==============================] - 0s 292us/step - loss: 0.3323 - accuracy: 0.8637
Epoch 240/1000
250/250 [==============================] - 0s 293us/step - loss: 0.3328 - accuracy: 0.8639
Epoch 241/1000
250/250 [==============================] - 0s 298us/step - loss: 0.3323 - accuracy: 0.8651
Epoch 242/1000
250/250 [==============================] - 0s 

250/250 [==============================] - 0s 302us/step - loss: 0.3319 - accuracy: 0.8639
Epoch 311/1000
250/250 [==============================] - 0s 297us/step - loss: 0.3315 - accuracy: 0.8635
Epoch 312/1000
250/250 [==============================] - 0s 299us/step - loss: 0.3318 - accuracy: 0.8648
Epoch 313/1000
250/250 [==============================] - 0s 300us/step - loss: 0.3314 - accuracy: 0.8643
Epoch 314/1000
250/250 [==============================] - 0s 293us/step - loss: 0.3315 - accuracy: 0.8644
Epoch 315/1000
250/250 [==============================] - 0s 294us/step - loss: 0.3314 - accuracy: 0.8630
Epoch 316/1000
250/250 [==============================] - 0s 294us/step - loss: 0.3316 - accuracy: 0.8649
Epoch 317/1000
250/250 [==============================] - 0s 295us/step - loss: 0.3320 - accuracy: 0.8641
Epoch 318/1000
250/250 [==============================] - 0s 294us/step - loss: 0.3317 - accuracy: 0.8639
Epoch 319/1000
250/250 [==============================] - 0s 

250/250 [==============================] - 0s 297us/step - loss: 0.3312 - accuracy: 0.8648
Epoch 388/1000
250/250 [==============================] - 0s 293us/step - loss: 0.3311 - accuracy: 0.8631
Epoch 389/1000
250/250 [==============================] - 0s 292us/step - loss: 0.3311 - accuracy: 0.8652
Epoch 390/1000
250/250 [==============================] - 0s 292us/step - loss: 0.3311 - accuracy: 0.8637
Epoch 391/1000
250/250 [==============================] - 0s 296us/step - loss: 0.3313 - accuracy: 0.8649
Epoch 392/1000
250/250 [==============================] - 0s 296us/step - loss: 0.3314 - accuracy: 0.8643
Epoch 393/1000
250/250 [==============================] - 0s 296us/step - loss: 0.3313 - accuracy: 0.8650
Epoch 394/1000
250/250 [==============================] - 0s 292us/step - loss: 0.3313 - accuracy: 0.8641
Epoch 395/1000
250/250 [==============================] - 0s 292us/step - loss: 0.3309 - accuracy: 0.8644
Epoch 396/1000
250/250 [==============================] - 0s 

250/250 [==============================] - 0s 296us/step - loss: 0.3313 - accuracy: 0.8643
Epoch 465/1000
250/250 [==============================] - 0s 295us/step - loss: 0.3310 - accuracy: 0.8656
Epoch 466/1000
250/250 [==============================] - 0s 291us/step - loss: 0.3311 - accuracy: 0.8643
Epoch 467/1000
250/250 [==============================] - 0s 292us/step - loss: 0.3313 - accuracy: 0.8636
Epoch 468/1000
250/250 [==============================] - 0s 291us/step - loss: 0.3310 - accuracy: 0.8639
Epoch 469/1000
250/250 [==============================] - 0s 291us/step - loss: 0.3312 - accuracy: 0.8656
Epoch 470/1000
250/250 [==============================] - 0s 292us/step - loss: 0.3313 - accuracy: 0.8640
Epoch 471/1000
250/250 [==============================] - 0s 295us/step - loss: 0.3309 - accuracy: 0.8643
Epoch 472/1000
250/250 [==============================] - 0s 295us/step - loss: 0.3313 - accuracy: 0.8639
Epoch 473/1000
250/250 [==============================] - 0s 

250/250 [==============================] - 0s 295us/step - loss: 0.3310 - accuracy: 0.8639
Epoch 542/1000
250/250 [==============================] - 0s 297us/step - loss: 0.3310 - accuracy: 0.8645
Epoch 543/1000
250/250 [==============================] - 0s 292us/step - loss: 0.3307 - accuracy: 0.8651
Epoch 544/1000
250/250 [==============================] - 0s 291us/step - loss: 0.3309 - accuracy: 0.8654
Epoch 545/1000
250/250 [==============================] - 0s 290us/step - loss: 0.3309 - accuracy: 0.8635
Epoch 546/1000
250/250 [==============================] - 0s 292us/step - loss: 0.3310 - accuracy: 0.8635
Epoch 547/1000
250/250 [==============================] - 0s 286us/step - loss: 0.3310 - accuracy: 0.8659
Epoch 548/1000
250/250 [==============================] - 0s 288us/step - loss: 0.3309 - accuracy: 0.8645
Epoch 549/1000
250/250 [==============================] - 0s 291us/step - loss: 0.3309 - accuracy: 0.8662
Epoch 550/1000
250/250 [==============================] - 0s 

250/250 [==============================] - 0s 295us/step - loss: 0.3309 - accuracy: 0.8639
Epoch 619/1000
250/250 [==============================] - 0s 287us/step - loss: 0.3307 - accuracy: 0.8649
Epoch 620/1000
250/250 [==============================] - 0s 292us/step - loss: 0.3309 - accuracy: 0.8656
Epoch 621/1000
250/250 [==============================] - 0s 291us/step - loss: 0.3308 - accuracy: 0.8640
Epoch 622/1000
250/250 [==============================] - 0s 291us/step - loss: 0.3310 - accuracy: 0.8641
Epoch 623/1000
250/250 [==============================] - 0s 290us/step - loss: 0.3308 - accuracy: 0.8646
Epoch 624/1000
250/250 [==============================] - 0s 290us/step - loss: 0.3310 - accuracy: 0.8631
Epoch 625/1000
250/250 [==============================] - 0s 292us/step - loss: 0.3310 - accuracy: 0.8656
Epoch 626/1000
250/250 [==============================] - 0s 290us/step - loss: 0.3311 - accuracy: 0.8634
Epoch 627/1000
250/250 [==============================] - 0s 

250/250 [==============================] - 0s 296us/step - loss: 0.3311 - accuracy: 0.8650
Epoch 696/1000
250/250 [==============================] - 0s 293us/step - loss: 0.3310 - accuracy: 0.8640
Epoch 697/1000
250/250 [==============================] - 0s 291us/step - loss: 0.3309 - accuracy: 0.8641
Epoch 698/1000
250/250 [==============================] - 0s 292us/step - loss: 0.3309 - accuracy: 0.8639
Epoch 699/1000
250/250 [==============================] - 0s 291us/step - loss: 0.3308 - accuracy: 0.8648
Epoch 700/1000
250/250 [==============================] - 0s 291us/step - loss: 0.3308 - accuracy: 0.8651
Epoch 701/1000
250/250 [==============================] - 0s 291us/step - loss: 0.3309 - accuracy: 0.8634
Epoch 702/1000
250/250 [==============================] - 0s 290us/step - loss: 0.3310 - accuracy: 0.8649
Epoch 703/1000
250/250 [==============================] - 0s 291us/step - loss: 0.3309 - accuracy: 0.8649
Epoch 704/1000
250/250 [==============================] - 0s 

250/250 [==============================] - 0s 296us/step - loss: 0.3306 - accuracy: 0.8651
Epoch 773/1000
250/250 [==============================] - 0s 294us/step - loss: 0.3308 - accuracy: 0.8645
Epoch 774/1000
250/250 [==============================] - 0s 290us/step - loss: 0.3308 - accuracy: 0.8641
Epoch 775/1000
250/250 [==============================] - 0s 291us/step - loss: 0.3309 - accuracy: 0.8643
Epoch 776/1000
250/250 [==============================] - 0s 291us/step - loss: 0.3308 - accuracy: 0.8643
Epoch 777/1000
250/250 [==============================] - 0s 291us/step - loss: 0.3309 - accuracy: 0.8659
Epoch 778/1000
250/250 [==============================] - 0s 290us/step - loss: 0.3308 - accuracy: 0.8644
Epoch 779/1000
250/250 [==============================] - 0s 291us/step - loss: 0.3308 - accuracy: 0.8637
Epoch 780/1000
250/250 [==============================] - 0s 290us/step - loss: 0.3308 - accuracy: 0.8651
Epoch 781/1000
250/250 [==============================] - 0s 

250/250 [==============================] - 0s 298us/step - loss: 0.3310 - accuracy: 0.8649
Epoch 850/1000
250/250 [==============================] - 0s 293us/step - loss: 0.3306 - accuracy: 0.8645
Epoch 851/1000
250/250 [==============================] - 0s 291us/step - loss: 0.3306 - accuracy: 0.8649
Epoch 852/1000
250/250 [==============================] - 0s 291us/step - loss: 0.3307 - accuracy: 0.8636
Epoch 853/1000
250/250 [==============================] - 0s 291us/step - loss: 0.3309 - accuracy: 0.8640
Epoch 854/1000
250/250 [==============================] - 0s 291us/step - loss: 0.3306 - accuracy: 0.8648
Epoch 855/1000
250/250 [==============================] - 0s 292us/step - loss: 0.3307 - accuracy: 0.8646
Epoch 856/1000
250/250 [==============================] - 0s 291us/step - loss: 0.3307 - accuracy: 0.8656
Epoch 857/1000
250/250 [==============================] - 0s 291us/step - loss: 0.3308 - accuracy: 0.8644
Epoch 858/1000
250/250 [==============================] - 0s 

250/250 [==============================] - 0s 297us/step - loss: 0.3303 - accuracy: 0.8639
Epoch 927/1000
250/250 [==============================] - 0s 292us/step - loss: 0.3307 - accuracy: 0.8646
Epoch 928/1000
250/250 [==============================] - 0s 292us/step - loss: 0.3306 - accuracy: 0.8652
Epoch 929/1000
250/250 [==============================] - 0s 292us/step - loss: 0.3309 - accuracy: 0.8654
Epoch 930/1000
250/250 [==============================] - 0s 291us/step - loss: 0.3304 - accuracy: 0.8645
Epoch 931/1000
250/250 [==============================] - 0s 291us/step - loss: 0.3306 - accuracy: 0.8649
Epoch 932/1000
250/250 [==============================] - 0s 292us/step - loss: 0.3308 - accuracy: 0.8651
Epoch 933/1000
250/250 [==============================] - 0s 292us/step - loss: 0.3307 - accuracy: 0.8652
Epoch 934/1000
250/250 [==============================] - 0s 291us/step - loss: 0.3310 - accuracy: 0.8649
Epoch 935/1000
250/250 [==============================] - 0s 

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [18]:
y_pred = ann.predict(X_test)
y_pred

array([[0.25192118],
       [0.33648187],
       [0.2350232 ],
       ...,
       [0.14955378],
       [0.18565905],
       [0.20293221]], dtype=float32)

In [19]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

# Criando uma Confusion Matrix

In [20]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1517   78]
 [ 202  203]]


# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)