# REDES NEURAIS ARTIFICIAIS
## Evaluate Improve e Tunning

# Parte 1 - Pré-processamento dos Dados

### Importar as libs

In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf

ERROR! Session/line number was not unique in database. History logging moved to new session 23


In [4]:
tf.__version__

'2.1.0'

### Importar o dataset

In [5]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


### Transformando os dados categóricos


In [7]:
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]
[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
np.shape(X_train)

(8000, 12)

---
# Parte 2 -Vamos construir uma ANN!


### Initializing the ANN

In [11]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [12]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='sigmoid'))

### Adding the output layer

In [14]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [15]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [16]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 1s 70us/sample - loss: 0.5031 - accuracy: 0.7960
Epoch 2/100
8000/8000 [==============================] - 0s 24us/sample - loss: 0.4719 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 0s 25us/sample - loss: 0.4419 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 0s 23us/sample - loss: 0.4214 - accuracy: 0.8006
Epoch 5/100
8000/8000 [==============================] - 0s 24us/sample - loss: 0.4089 - accuracy: 0.8131
Epoch 6/100
8000/8000 [==============================] - 0s 26us/sample - loss: 0.3993 - accuracy: 0.8232
Epoch 7/100
8000/8000 [==============================] - 0s 24us/sample - loss: 0.3910 - accuracy: 0.8326
Epoch 8/100
8000/8000 [==============================] - 0s 24us/sample - loss: 0.3829 - accuracy: 0.8375
Epoch 9/100
8000/8000 [==============================] - 0s 25us/sample - loss: 0.3760 - accuracy: 0.8432
Epoch 10/100
8000/8000 [

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [17]:
y_pred = ann.predict(X_test)
y_pred

array([[0.24955438],
       [0.2452886 ],
       [0.12426578],
       ...,
       [0.1127601 ],
       [0.16713966],
       [0.19529301]], dtype=float32)

In [18]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

# Criando uma Confusion Matrix

In [19]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1514   81]
 [ 196  209]]


---
# Avaliando o Modelo

In [20]:
# Evaluating the ANN
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [21]:
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 12))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

In [22]:
classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()

In [23]:
print(mean,variance)

0.8038750112056732 0.015334297098279156


# Melhorando o modelo

In [24]:
# Improving the ANN
# Dropout Regularization to reduce overfitting if needed
from tensorflow.keras.layers import Dropout

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 12))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

In [25]:
classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()

In [26]:
print(mean,variance)

0.799750006198883 0.014872366948667604


# Tuning the ANN

In [ ]:
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 12))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier)

parameters = {
    'batch_size': [10, 25, 32],
    'epochs': [50, 100],
    'optimizer': ['adam', 'rmsprop']
}

grid_search = GridSearchCV(estimator = classifier,
                           scoring = 'accuracy',
                           param_grid = parameters,
                           cv = 10)

In [ ]:
%%time

grid_search = grid_search.fit(X_train, y_train)

Streaming output truncated to the last 5000 lines.
Epoch 2/50
225/225 [==============================] - 1s 2ms/step - loss: 0.4915 - accuracy: 0.7956
Epoch 3/50
225/225 [==============================] - 0s 2ms/step - loss: 0.4763 - accuracy: 0.7956
Epoch 4/50
225/225 [==============================] - 0s 2ms/step - loss: 0.4695 - accuracy: 0.7956
Epoch 5/50
225/225 [==============================] - 0s 2ms/step - loss: 0.4643 - accuracy: 0.7956
Epoch 6/50
225/225 [==============================] - 1s 2ms/step - loss: 0.4588 - accuracy: 0.7956
Epoch 7/50
225/225 [==============================] - 1s 2ms/step - loss: 0.4539 - accuracy: 0.7956
Epoch 8/50
225/225 [==============================] - 0s 2ms/step - loss: 0.4500 - accuracy: 0.7956
Epoch 9/50
225/225 [==============================] - 0s 2ms/step - loss: 0.4457 - accuracy: 0.7956
Epoch 10/50
225/225 [==============================] - 0s 2ms/step - loss: 0.4418 - accuracy: 0.7956
Epoch 11/50
225/225 [===========================

In [ ]:
print('Best params:\n',grid_search.best_params_,'\nBest accuracy:\n',grid_search.best_score_)

Best params:
 {'batch_size': 10, 'epochs': 100, 'optimizer': 'rmsprop'} 
Best accuracy:
 0.83675


# Halving Grid Search

In [27]:
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.experimental import enable_halving_search_cv
from sklearn.model_selection import HalvingGridSearchCV


def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 12))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier)

parameters = {
    'batch_size': [10, 25, 32],
    'epochs': [50, 100],
    'optimizer': ['adam', 'rmsprop']
}

halving_cv = HalvingGridSearchCV(estimator = classifier,
                                  param_grid = parameters,
                                  scoring="accuracy", 
                                  n_jobs=-1, 
                                  min_resources="exhaust", 
                                  factor=3,
                                  cv = 10)

In [28]:
%%time
halving_cv = halving_cv.fit(X_train, y_train)

Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 1s 148us/sample - loss: 0.5148 - accuracy: 0.7958
Epoch 2/100
8000/8000 [==============================] - 1s 82us/sample - loss: 0.4678 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 79us/sample - loss: 0.4565 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 80us/sample - loss: 0.4488 - accuracy: 0.7960
Epoch 5/100
8000/8000 [==============================] - 1s 82us/sample - loss: 0.4424 - accuracy: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 79us/sample - loss: 0.4392 - accuracy: 0.7960
Epoch 7/100
8000/8000 [==============================] - 1s 79us/sample - loss: 0.4378 - accuracy: 0.7961
Epoch 8/100
8000/8000 [==============================] - 1s 80us/sample - loss: 0.4372 - accuracy: 0.7961
Epoch 9/100
8000/8000 [==============================] - 1s 82us/sample - loss: 0.4351 - accuracy: 0.7958
Epoch 10/100
8000/8000 

In [29]:
print('Best params:\n',halving_cv.best_params_,'\nBest accuracy:\n',halving_cv.best_score_)

Best params:
 {'batch_size': 10, 'epochs': 100, 'optimizer': 'rmsprop'} 
Best accuracy:
 0.8359198998748434


# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)