# REDES NEURAIS ARTIFICIAIS
## Evaluate Improve e Tunning

# Parte 1 - Pré-processamento dos Dados

### Importar as libs

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.6.0'

### Importar o dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


### Transformando os dados categóricos


In [5]:
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]
[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
np.shape(X_train)

(8000, 12)

---
# Parte 2 -Vamos construir uma ANN!


### Initializing the ANN

In [12]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=12, activation='sigmoid'))

### Adding the second hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))

### Adding the output layer

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation='relu'))

## Part 3 - Training the ANN

### Compiling the ANN

In [16]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [17]:
### Training the ANN on the Training set

In [18]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

2021-08-22 18:24:08.983011: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


Epoch 1/100
250/250 [==============================] - 0s 611us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 2/100
250/250 [==============================] - 0s 646us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 581us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 786us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 831us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 0s 885us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 7/100
250/250 [==============================] - 0s 774us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 8/100
250/250 [==============================] - 0s 717us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 9/100
250/250 [==============================] - 0s 634us/step - loss: 3.1467 - accuracy: 0.7960
Epoch 10/100
250/250 [==============================] - 0s 786us/step - l

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [19]:
y_pred = ann.predict(X_test)
y_pred

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)

In [20]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

# Criando uma Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1595    0]
 [ 405    0]]


---
# Avaliando o Modelo

In [22]:
# Evaluating the ANN
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [23]:
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 12, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 12))
    classifier.add(Dense(units = 12, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

In [24]:
classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = 1)
mean = accuracies.mean()
variance = accuracies.std()

Epoch 1/10
720/720 [==============================] - 1s 556us/step - loss: 3.1300 - accuracy: 0.7971
Epoch 2/10
720/720 [==============================] - 0s 607us/step - loss: 3.1300 - accuracy: 0.7971
Epoch 3/10
720/720 [==============================] - 0s 566us/step - loss: 3.1300 - accuracy: 0.7971
Epoch 4/10
720/720 [==============================] - 0s 613us/step - loss: 3.1300 - accuracy: 0.7971
Epoch 5/10
720/720 [==============================] - 0s 638us/step - loss: 3.1300 - accuracy: 0.7971
Epoch 6/10
720/720 [==============================] - 0s 648us/step - loss: 3.1300 - accuracy: 0.7971
Epoch 7/10
720/720 [==============================] - 0s 648us/step - loss: 3.1300 - accuracy: 0.7971
Epoch 8/10
720/720 [==============================] - 0s 690us/step - loss: 3.1300 - accuracy: 0.7971
Epoch 9/10
720/720 [==============================] - 0s 596us/step - loss: 3.1300 - accuracy: 0.7971
Epoch 10/10
80/80 [==============================] - 0s 526us/step - loss: 3.2971 

In [22]:
print(mean,variance)

0.7963750064373016 0.009721914717540872


# Melhorando o modelo

In [25]:
# Improving the ANN
# Dropout Regularization to reduce overfitting if needed
from tensorflow.keras.layers import Dropout

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 12))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

In [26]:
classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = 1)
mean = accuracies.mean()
variance = accuracies.std()

Epoch 1/10
720/720 [==============================] - 1s 644us/step - loss: 0.5008 - accuracy: 0.7972
Epoch 2/10
720/720 [==============================] - 0s 622us/step - loss: 0.4370 - accuracy: 0.7971
Epoch 3/10
720/720 [==============================] - 0s 600us/step - loss: 0.4341 - accuracy: 0.7971
Epoch 4/10
720/720 [==============================] - 0s 584us/step - loss: 0.4292 - accuracy: 0.7971
Epoch 5/10
720/720 [==============================] - 0s 597us/step - loss: 0.4264 - accuracy: 0.7971
Epoch 6/10
720/720 [==============================] - 0s 597us/step - loss: 0.4264 - accuracy: 0.7971
Epoch 7/10
720/720 [==============================] - 0s 582us/step - loss: 0.4251 - accuracy: 0.8121
Epoch 8/10
720/720 [==============================] - 0s 599us/step - loss: 0.4245 - accuracy: 0.8242
Epoch 9/10
720/720 [==============================] - 0s 628us/step - loss: 0.4246 - accuracy: 0.8257
Epoch 10/10
80/80 [==============================] - 0s 649us/step - loss: 0.4201 

In [25]:
print(mean,variance)

0.818875002861023 0.01901026843567131


# Tuning the ANN

In [26]:
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 12))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier)

parameters = {
    'batch_size': [10, 25, 32],
    'epochs': [50, 100],
    'optimizer': ['adam', 'rmsprop']
}

grid_search = GridSearchCV(estimator = classifier,
                           scoring = 'accuracy',
                           param_grid = parameters,
                           cv = 10)

In [ ]:
%%time

grid_search = grid_search.fit(X_train, y_train)

Epoch 1/50
720/720 [==============================] - 1s 602us/step - loss: 0.4885 - accuracy: 0.7961
Epoch 2/50
720/720 [==============================] - 0s 574us/step - loss: 0.4362 - accuracy: 0.7971
Epoch 3/50
720/720 [==============================] - 0s 621us/step - loss: 0.4319 - accuracy: 0.7971
Epoch 4/50
720/720 [==============================] - 0s 664us/step - loss: 0.4301 - accuracy: 0.7971
Epoch 5/50
720/720 [==============================] - 0s 684us/step - loss: 0.4291 - accuracy: 0.7971
Epoch 6/50
720/720 [==============================] - 0s 644us/step - loss: 0.4287 - accuracy: 0.7978
Epoch 7/50
720/720 [==============================] - 0s 602us/step - loss: 0.4279 - accuracy: 0.8161
Epoch 8/50
720/720 [==============================] - 0s 620us/step - loss: 0.4268 - accuracy: 0.8211
Epoch 9/50
720/720 [==============================] - 0s 663us/step - loss: 0.4263 - accuracy: 0.8235
Epoch 10/50
720/720 [==============================] - 0s 584us/step - loss: 0.424

In [29]:
print('Best params:\n',grid_search.best_params_,'\nBest accuracy:\n',grid_search.best_score_)

NameError: name 'grid_search' is not defined

# Halving Grid Search

In [ ]:
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.experimental import enable_halving_search_cv
from sklearn.model_selection import HalvingGridSearchCV

def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 12))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier)

parameters = {
    'batch_size': [10, 25, 32],
    'epochs': [50, 100],
    'optimizer': ['adam', 'rmsprop']
}

halving_cv = HalvingGridSearchCV(estimator = classifier,
                                  param_grid = parameters,
                                  scoring="accuracy", 
                                  n_jobs=-1, 
                                  min_resources="exhaust", 
                                  factor=3,
                                  cv = 10)

In [ ]:
%%time
halving_cv = halving_cv.fit(X_train, y_train)

In [ ]:
print('Best params:\n',halving_cv.best_params_,'\nBest accuracy:\n',halving_cv.best_score_)

# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)

In [10]:
import os

In [11]:
os.environ['CUDA_VISIBLE_DEVICES'] = "0"