# REDES NEURAIS ARTIFICIAIS
## Evaluate Improve e Tunning

# Parte 1 - Pré-processamento dos Dados

### Importar as libs

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

2022-03-25 22:33:53.535521: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-25 22:33:53.535550: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
tf.__version__

'2.8.0'

### Importar o dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


### Transformando os dados categóricos


In [5]:
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]
[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
np.shape(X_train)

(8000, 12)

---
# Parte 2 -Vamos construir uma ANN!


### Initializing the ANN

In [9]:
ann = tf.keras.models.Sequential()

2022-03-25 22:33:55.128658: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-25 22:33:55.128803: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-25 22:33:55.128842: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2022-03-25 22:33:55.128872: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2022-03-25 22:33:55.128901: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Co

### Adding the input layer and the first hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [11]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [12]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [13]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [14]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 200)

Epoch 1/200
250/250 [==============================] - 0s 451us/step - loss: 0.5578 - accuracy: 0.7538
Epoch 2/200
250/250 [==============================] - 0s 399us/step - loss: 0.4686 - accuracy: 0.7964
Epoch 3/200
250/250 [==============================] - 0s 479us/step - loss: 0.4481 - accuracy: 0.7966
Epoch 4/200
250/250 [==============================] - 0s 486us/step - loss: 0.4344 - accuracy: 0.8008
Epoch 5/200
250/250 [==============================] - 0s 461us/step - loss: 0.4217 - accuracy: 0.8207
Epoch 6/200
250/250 [==============================] - 0s 458us/step - loss: 0.4077 - accuracy: 0.8295
Epoch 7/200
250/250 [==============================] - 0s 488us/step - loss: 0.3942 - accuracy: 0.8376
Epoch 8/200
250/250 [==============================] - 0s 496us/step - loss: 0.3837 - accuracy: 0.8446
Epoch 9/200
250/250 [==============================] - 0s 470us/step - loss: 0.3757 - accuracy: 0.8476
Epoch 10/200
250/250 [==============================] - 0s 409us/step - l

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [15]:
y_pred = ann.predict(X_test)
y_pred

array([[0.2610299 ],
       [0.23328006],
       [0.10301691],
       ...,
       [0.2947501 ],
       [0.23571274],
       [0.1899991 ]], dtype=float32)

In [16]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

# Criando uma Confusion Matrix

In [17]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1502   93]
 [ 185  220]]


---
# Avaliando o Modelo

In [18]:
# Evaluating the ANN
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [19]:
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 12))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

In [20]:
classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()

/tmp/ipykernel_120335/1297209367.py:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
2022-03-25 22:34:19.428199: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-25 22:34:19.428223: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-03-25 22:34:19.445602: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-25 22:34:19.445628: I tensorflow/stream_executor/cud

Epoch 1/10
Epoch 1/10


2022-03-25 22:34:20.692277: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-25 22:34:20.692443: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-25 22:34:20.692487: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2022-03-25 22:34:20.692524: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2022-03-25 22:34:20.692561: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Co

 82/720 [==>...........................] - ETA: 0s - loss: 0.6758 - accuracy: 0.7866  Epoch 1/10
Epoch 1/10
162/720 [=====>........................] - ETA: 0s - loss: 0.6331 - accuracy: 0.7889Epoch 1/10
Epoch 1/10
Epoch 1/10
720/720 [==============================] - 1s 715us/step - loss: 0.4852 - accuracy: 0.7954
Epoch 2/10
720/720 [==============================] - 1s 777us/step - loss: 0.4923 - accuracy: 0.7962
Epoch 2/10
720/720 [==============================] - 1s 829us/step - loss: 0.4921 - accuracy: 0.7944
Epoch 2/10
720/720 [==============================] - 1s 796us/step - loss: 0.4908 - accuracy: 0.7932
Epoch 2/10
720/720 [==============================] - 1s 817us/step - loss: 0.4897 - accuracy: 0.7969
Epoch 2/10
720/720 [==============================] - 1s 788us/step - loss: 0.4889 - accuracy: 0.7958
Epoch 2/10
720/720 [==============================] - 1s 827us/step - loss: 0.4976 - accuracy: 0.7956
Epoch 2/10
720/720 [==============================] - 1s 831us/step - lo

In [21]:
print(mean,variance)

0.834375 0.01233961016612086


# Melhorando o modelo

In [22]:
# Improving the ANN
# Dropout Regularization to reduce overfitting if needed
from tensorflow.keras.layers import Dropout

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 12))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

In [23]:
classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()

Epoch 1/10
Epoch 1/10
Epoch 1/10
Epoch 1/10
Epoch 1/10
Epoch 1/10
Epoch 1/10
Epoch 1/10


/tmp/ipykernel_120335/1297209367.py:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)


185/720 [======>.......................] - ETA: 0s - loss: 0.6193 - accuracy: 0.7924

2022-03-25 22:34:31.856240: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-25 22:34:31.856261: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-03-25 22:34:31.857436: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-25 22:34:31.857451: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


720/720 [==============================] - 1s 770us/step - loss: 0.4903 - accuracy: 0.7950
Epoch 2/10
720/720 [==============================] - 1s 848us/step - loss: 0.5010 - accuracy: 0.7957
Epoch 2/10
720/720 [==============================] - 1s 811us/step - loss: 0.4990 - accuracy: 0.7935
Epoch 2/10
720/720 [==============================] - 1s 845us/step - loss: 0.4939 - accuracy: 0.7961
Epoch 2/10
720/720 [==============================] - 1s 864us/step - loss: 0.5203 - accuracy: 0.7958
Epoch 2/10
720/720 [==============================] - 1s 851us/step - loss: 0.4891 - accuracy: 0.7957
Epoch 2/10
720/720 [==============================] - 1s 839us/step - loss: 0.4368 - accuracy: 0.7956
Epoch 3/10
720/720 [==============================] - 1s 802us/step - loss: 0.4382 - accuracy: 0.7961
Epoch 3/10
Epoch 3/10
720/720 [==============================] - 1s 821us/step - loss: 0.4383 - accuracy: 0.7944
Epoch 3/10
720/720 [==============================] - 1s 815us/step - loss: 0.4358

2022-03-25 22:34:33.179080: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-25 22:34:33.179294: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-25 22:34:33.179343: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2022-03-25 22:34:33.179387: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2022-03-25 22:34:33.179429: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Co

720/720 [==============================] - 1s 808us/step - loss: 0.4344 - accuracy: 0.7956
Epoch 4/10
720/720 [==============================] - 1s 805us/step - loss: 0.4368 - accuracy: 0.7944
Epoch 4/10
720/720 [==============================] - 1s 815us/step - loss: 0.4215 - accuracy: 0.8196
Epoch 4/10
720/720 [==============================] - 1s 818us/step - loss: 0.4380 - accuracy: 0.7937
Epoch 4/10
720/720 [==============================] - 1s 895us/step - loss: 0.4356 - accuracy: 0.7961
Epoch 4/10
720/720 [==============================] - 1s 877us/step - loss: 0.4298 - accuracy: 0.7975
Epoch 4/10
720/720 [==============================] - 1s 866us/step - loss: 0.4336 - accuracy: 0.8117
Epoch 4/10
720/720 [==============================] - 1s 865us/step - loss: 0.4327 - accuracy: 0.7957
Epoch 4/10
720/720 [==============================] - 1s 926us/step - loss: 0.4311 - accuracy: 0.7956
Epoch 5/10
720/720 [==============================] - 1s 830us/step - loss: 0.4332 - accuracy

In [ ]:
print(mean,variance)

0.824874997138977 0.013698209096119584


# Tuning the ANN

In [ ]:
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 12))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier)

parameters = {
    'batch_size': [10, 25, 32],
    'epochs': [50, 100],
    'optimizer': ['adam', 'rmsprop']
}

grid_search = GridSearchCV(estimator = classifier,
                           scoring = 'accuracy',
                           param_grid = parameters,
                           cv = 10)

/tmp/ipykernel_100712/1068215134.py:16: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  classifier = KerasClassifier(build_fn = build_classifier)


In [ ]:
%%time

grid_search = grid_search.fit(X_train, y_train)

Epoch 1/50
720/720 [==============================] - 1s 477us/step - loss: 0.5003 - accuracy: 0.7965
Epoch 2/50
720/720 [==============================] - 0s 491us/step - loss: 0.4387 - accuracy: 0.7971
Epoch 3/50
720/720 [==============================] - 0s 478us/step - loss: 0.4366 - accuracy: 0.7971
Epoch 4/50
720/720 [==============================] - 0s 455us/step - loss: 0.4294 - accuracy: 0.7971
Epoch 5/50
720/720 [==============================] - 0s 478us/step - loss: 0.4318 - accuracy: 0.7971
Epoch 6/50
720/720 [==============================] - 0s 442us/step - loss: 0.4272 - accuracy: 0.7971
Epoch 7/50
720/720 [==============================] - 0s 427us/step - loss: 0.4262 - accuracy: 0.7971
Epoch 8/50
720/720 [==============================] - 0s 448us/step - loss: 0.4289 - accuracy: 0.8015
Epoch 9/50
720/720 [==============================] - 0s 451us/step - loss: 0.4284 - accuracy: 0.8189
Epoch 10/50
720/720 [==============================] - 0s 449us/step - loss: 0.425

In [ ]:
print('Best params:\n',grid_search.best_params_,'\nBest accuracy:\n',grid_search.best_score_)

Best params:
 {'batch_size': 32, 'epochs': 100, 'optimizer': 'rmsprop'} 
Best accuracy:
 0.8375


# Halving Grid Search

In [ ]:
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.experimental import enable_halving_search_cv
from sklearn.model_selection import HalvingGridSearchCV

def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 12))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier)

parameters = {
    'batch_size': [10, 25, 32],
    'epochs': [50, 100],
    'optimizer': ['adam', 'rmsprop']
}

halving_cv = HalvingGridSearchCV(estimator = classifier,
                                  param_grid = parameters,
                                  scoring="accuracy", 
                                  n_jobs=-1, 
                                  min_resources="exhaust", 
                                  factor=3,
                                  cv = 10)

/tmp/ipykernel_100712/2291648736.py:17: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  classifier = KerasClassifier(build_fn = build_classifier)


In [ ]:
%%time
halving_cv = halving_cv.fit(X_train, y_train)

2022-03-25 20:28:54.742459: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-25 20:28:54.742480: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-03-25 20:28:54.916849: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-25 20:28:54.916882: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-03-25 20:28:54.917881: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or dire

Epoch 1/50
Epoch 1/50
Epoch 1/50
Epoch 1/50
Epoch 1/50
Epoch 1/50
Epoch 1/50
Epoch 1/50
Epoch 1/50
Epoch 1/50
Epoch 1/50
Epoch 1/50
80/80 [==============================] - 0s 874us/step - loss: 0.6834 - accuracy: 0.7722
Epoch 2/50
Epoch 2/50
80/80 [==============================] - 0s 983us/step - loss: 0.6787 - accuracy: 0.7860
Epoch 2/50
80/80 [==============================] - 0s 1ms/step - loss: 0.6807 - accuracy: 0.7785
Epoch 2/50
80/80 [==============================] - 0s 1ms/step - loss: 0.6779 - accuracy: 0.8073
Epoch 2/50
80/80 [==============================] - 1s 1ms/step - loss: 0.6754 - accuracy: 0.7985
Epoch 2/50
80/80 [==============================] - 0s 918us/step - loss: 0.6226 - accuracy: 0.7897
Epoch 3/50
80/80 [==============================] - 0s 1ms/step - loss: 0.6212 - accuracy: 0.8123
Epoch 3/50
Epoch 3/50
80/80 [==============================] - 1s 2ms/step - loss: 0.6815 - accuracy: 0.7710
Epoch 2/50
80/80 [==============================] - 1s 1ms/step - l

In [ ]:
print('Best params:\n',halving_cv.best_params_,'\nBest accuracy:\n',halving_cv.best_score_)

# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)