# REDES NEURAIS ARTIFICIAIS
## Evaluate Improve e Tunning

# Parte 1 - Pré-processamento dos Dados

### Importar as libs

In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [4]:
tf.__version__

'2.3.1'

### Importar o dataset

In [5]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


### Transformando os dados categóricos


In [7]:
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]
[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
np.shape(X_train)

(8000, 12)

---
# Parte 2 -Vamos construir uma ANN!


In [11]:
tf.random.set_seed(0) # Define uma seed padrão para a análise sobre a acurácia não variar

### Initializing the ANN

In [12]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='exponential'))

### Adding the second hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='tanh'))

### Adding the output layer

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [16]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [17]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.6379 - accuracy: 0.6420
Epoch 2/100
250/250 [==============================] - 0s 856us/step - loss: 0.4738 - accuracy: 0.7972
Epoch 3/100
250/250 [==============================] - 0s 848us/step - loss: 0.4462 - accuracy: 0.8060
Epoch 4/100
250/250 [==============================] - 0s 852us/step - loss: 0.4245 - accuracy: 0.8166
Epoch 5/100
250/250 [==============================] - 0s 832us/step - loss: 0.4109 - accuracy: 0.8205
Epoch 6/100
250/250 [==============================] - 0s 819us/step - loss: 0.3983 - accuracy: 0.8255
Epoch 7/100
250/250 [==============================] - 0s 811us/step - loss: 0.3875 - accuracy: 0.8265
Epoch 8/100
250/250 [==============================] - 0s 812us/step - loss: 0.3801 - accuracy: 0.8285
Epoch 9/100
250/250 [==============================] - 0s 820us/step - loss: 0.3748 - accuracy: 0.8329
Epoch 10/100
250/250 [==============================] - 0s 804us/step - los

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [18]:
y_pred = ann.predict(X_test)
y_pred

array([[0.24850568],
       [0.21643874],
       [0.1447384 ],
       ...,
       [0.18251649],
       [0.28312838],
       [0.30762452]], dtype=float32)

In [19]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

# Criando uma Confusion Matrix

In [20]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1519   76]
 [ 190  215]]


In [21]:
from sklearn.metrics import (accuracy_score)
accuracy_score(y_test, y_pred)

0.867

---
# Avaliando o Modelo

In [88]:
# Evaluating the ANN
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [89]:
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'exponential', input_dim = 12))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'tanh'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

In [90]:
classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()

In [91]:
print(mean,variance)

0.8317499935626984 0.010985784746768206


# Melhorando o modelo

In [92]:
# Improving the ANN
# Dropout Regularization to reduce overfitting if needed
from tensorflow.keras.layers import Dropout

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'exponential', input_dim = 12))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'tanh'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

In [93]:
classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()

In [94]:
print(mean,variance)

0.8259999930858613 0.010647770900679292


Tentei por algumas vezes gerar uma variância maior utilizando as funções de ativação que utilizei na primeira parte, porém não consegui, com o melhor resultado sendo o registrado anteriormente, com variância muito próxima, porém diminuindo a média. Alterar o valor do dropout e o otimizador não gerou resultados melhores.

# Tuning the ANN

In [95]:
# Como o professor havia dito durante a aula, decidi não utilizar o GridSearch, pois demanda um processamento muito grande da máquina, sendo apenas algo opcional. 

#from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
#from sklearn.model_selection import GridSearchCV
#from tensorflow.keras.models import Sequential
#from tensorflow.keras.layers import Dense

#def build_classifier(optimizer):
#    classifier = Sequential()
#    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 12))
#    classifier.add(Dropout(rate = 0.1))
#    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
#    classifier.add(Dropout(rate = 0.1))
#    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
#    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
#    return classifier

#classifier = KerasClassifier(build_fn = build_classifier)

#parameters = {
#    'batch_size': [10, 25, 32],
#    'epochs': [50, 100],
#    'optimizer': ['adam', 'rmsprop']
#}

#grid_search = GridSearchCV(estimator = classifier,
#                           scoring = 'accuracy',
#                           param_grid = parameters,
#                           cv = 10)

In [96]:
#%%time

#grid_search = grid_search.fit(X_train, y_train)

In [97]:
#print('Best params:\n',grid_search.best_params_,'\nBest accuracy:\n',grid_search.best_score_)

# Halving Grid Search

In [98]:
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from sklearn.experimental import enable_halving_search_cv
from sklearn.model_selection import HalvingGridSearchCV

def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'exponential', input_dim = 12))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'tanh'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier)

parameters = {
    'batch_size': [10, 25, 32, 64, 128],
    'epochs': [50, 75, 100, 125, 150, 175, 200],
    'optimizer': ['adam', 'rmsprop', 'sgd', 'adadelta', 'adamax', 'adagrad']
}

halving_cv = HalvingGridSearchCV(estimator = classifier,
                                  param_grid = parameters,
                                  scoring="accuracy", 
                                  n_jobs=-1, 
                                  min_resources="exhaust", 
                                  factor=3,
                                  cv = 10)

In [99]:
%%time
halving_cv = halving_cv.fit(X_train, y_train)

Epoch 1/150
800/800 [==============================] - 1s 888us/step - loss: 0.5459 - accuracy: 0.7961
Epoch 2/150
800/800 [==============================] - 1s 778us/step - loss: 0.5026 - accuracy: 0.7960
Epoch 3/150
800/800 [==============================] - 1s 752us/step - loss: 0.4957 - accuracy: 0.7960
Epoch 4/150
800/800 [==============================] - 1s 733us/step - loss: 0.4864 - accuracy: 0.7960
Epoch 5/150
800/800 [==============================] - 1s 728us/step - loss: 0.4698 - accuracy: 0.7960
Epoch 6/150
800/800 [==============================] - 1s 750us/step - loss: 0.4501 - accuracy: 0.7960
Epoch 7/150
800/800 [==============================] - 1s 773us/step - loss: 0.4426 - accuracy: 0.8011
Epoch 8/150
800/800 [==============================] - 1s 748us/step - loss: 0.4352 - accuracy: 0.8116
Epoch 9/150
800/800 [==============================] - 1s 763us/step - loss: 0.4328 - accuracy: 0.8102
Epoch 10/150
800/800 [==============================] - 1s 760us/step - l

In [100]:
print('Best params:\n',halving_cv.best_params_,'\nBest accuracy:\n',halving_cv.best_score_)

Best params:
 {'batch_size': 10, 'epochs': 150, 'optimizer': 'sgd'} 
Best accuracy:
 0.8489281210592686


# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)