In [1]:
pip install -r requirements.txt

SyntaxError: invalid syntax (<ipython-input-1-15707bb57fc2>, line 1)

In [1]:
# Artificial Neural Network

# Installing Theano
# pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
# pip install tensorflow

# Installing Keras
# pip install --upgrade keras

# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [2]:
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]
[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


/home/ita/.local/lib/python2.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [3]:
np.shape(X_train)

(8000, 12)

In [4]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 12))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'tanh'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Using TensorFlow backend.


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Epoch 1/100
8000/8000 [==============================] - 2s 252us/step - loss: 0.5409 - accuracy: 0.7997
Epoch 2/100
8000/8000 [==============================] - 1s 127us/step - loss: 0.4139 - accuracy: 0.8087
Epoch 3/100
8000/8000 [==============================] - 1s 127us/step - loss: 0.3979 - accuracy: 0.8163
Epoch 4/100
8000/8000 [==============================] - 1s 127us/step - loss: 0.3882 - accuracy: 0.8219
Epoch 5/100
8000/8000 [==============================] - 1s 161us/step - loss: 0.3807 - accuracy: 0.8322
Epoch 6/100
8000/8000 [==============================] - 1s 153us/step - loss: 0.3761 - accuracy: 0.8386
Epoch 7/100
8000/8000 [==============================] - 1s 143us/step - loss: 0.3727 - accuracy: 0.8410
Epoch 8/100
8000/8000 [==============================] - 1s 135us/step - loss: 0.3701 - accuracy: 0.8470
Epoch 9/100
8000/8000 [==============================] - 1s 131us

8000/8000 [==============================] - 1s 116us/step - loss: 0.3448 - accuracy: 0.8587
Epoch 74/100
8000/8000 [==============================] - 1s 120us/step - loss: 0.3425 - accuracy: 0.8601
Epoch 75/100
8000/8000 [==============================] - 1s 114us/step - loss: 0.3534 - accuracy: 0.8531
Epoch 76/100
8000/8000 [==============================] - 1s 153us/step - loss: 0.3444 - accuracy: 0.8586
Epoch 77/100
8000/8000 [==============================] - 1s 131us/step - loss: 0.3424 - accuracy: 0.8622
Epoch 78/100
8000/8000 [==============================] - 1s 173us/step - loss: 0.3409 - accuracy: 0.8600
Epoch 79/100
8000/8000 [==============================] - 1s 175us/step - loss: 0.3385 - accuracy: 0.8615
Epoch 80/100
8000/8000 [==============================] - 1s 124us/step - loss: 0.3383 - accuracy: 0.8605
Epoch 81/100
8000/8000 [==============================] - 1s 103us/step - loss: 0.3487 - accuracy: 0.8558
Epoch 82/100
8000/8000 [==============================] - 1

In [7]:
# Part 3 - Making predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [8]:
print(cm)

[[1518   77]
 [ 198  207]]
