#Criando e melhorando redes neurais artificiais



# Parte 1 - Pré-processamento dos Dados

### Importar as libs

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

### Importar o dataset

In [ ]:
#Exportacao do arquivo para a nuvem
from google.colab import files
import io
uploaded = files.upload()
file_name = next(iter(uploaded))
file_name

Saving Churn_Modelling.csv to Churn_Modelling.csv


'Churn_Modelling.csv'

In [ ]:
gfile_name = io.StringIO(uploaded[file_name].decode('ISO 8859-1').strip())
dataset = pd.read_csv(gfile_name)
dataset.head(50)

RowNumber  CustomerId        Surname  CreditScore Geography  Gender  Age  \
0           1    15634602       Hargrave          619    France  Female   42   
1           2    15647311           Hill          608     Spain  Female   41   
2           3    15619304           Onio          502    France  Female   42   
3           4    15701354           Boni          699    France  Female   39   
4           5    15737888       Mitchell          850     Spain  Female   43   
5           6    15574012            Chu          645     Spain    Male   44   
6           7    15592531       Bartlett          822    France    Male   50   
7           8    15656148         Obinna          376   Germany  Female   29   
8           9    15792365             He          501    France    Male   44   
9          10    15592389             H?          684    France    Male   27   
10         11    15767821         Bearce          528    France    Male   31   
11         12    15737173        Andrews          497     Spain    Male   24   
12         13    15632264            Kay          476    France  Female   34   
13         14    15691483           Chin          549    France  Female   25   
14         15    15600882          Scott          635     Spain  Female   35   
15         16    15643966        Goforth          616   Germany    Male   45   
16         17    15737452          Romeo          653   Germany    Male   58   
17         18    15788218      Henderson          549     Spain  Female   24   
18         19    15661507        Muldrow          587     Spain    Male   45   
19         20    15568982            Hao          726    France  Female   24   
20         21    15577657       McDonald          732    France    Male   41   
21         22    15597945       Dellucci          636     Spain  Female   32   
22         23    15699309      Gerasimov          510     Spain  Female   38   
23         24    15725737         Mosman          669    France    Male   46   
24         25    15625047            Yen          846    France  Female   38   
25         26    15738191        Maclean          577    France    Male   25   
26         27    15736816          Young          756   Germany    Male   36   
27         28    15700772        Nebechi          571    France    Male   44   
28         29    15728693     McWilliams          574   Germany  Female   43   
29         30    15656300       Lucciano          411    France    Male   29   
30         31    15589475        Azikiwe          591     Spain  Female   39   
31         32    15706552  Odinakachukwu          533    France    Male   36   
32         33    15750181      Sanderson          553   Germany    Male   41   
33         34    15659428        Maggard          520     Spain  Female   42   
34         35    15732963       Clements          722     Spain  Female   29   
35         36    15794171       Lombardo          475    France  Female   45   
36         37    15788448         Watson          490     Spain    Male   31   
37         38    15729599        Lorenzo          804     Spain    Male   33   
38         39    15717426      Armstrong          850    France    Male   36   
39         40    15585768        Cameron          582   Germany    Male   41   
40         41    15619360          Hsiao          472     Spain    Male   40   
41         42    15738148         Clarke          465    France  Female   51   
42         43    15687946        Osborne          556    France  Female   61   
43         44    15755196         Lavine          834    France  Female   49   
44         45    15684171        Bianchi          660     Spain  Female   61   
45         46    15754849          Tyler          776   Germany  Female   32   
46         47    15602280         Martin          829   Germany  Female   27   
47         48    15771573        Okagbue          637   Germany  Female   39   
48         49    15766205            Yin          550   Germany    Male   38   
49  

In [ ]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


### Transformando os dados categóricos


In [ ]:
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X[:, 2])

[0 0 0 ... 0 1 0]


In [ ]:
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

---
# Parte 2 -Construindo a ANN e avaliando o modelo


In [ ]:
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 12))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

In [ ]:
classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  """Entry point for launching an IPython kernel.


In [ ]:
print(mean,variance)

0.8356249988079071 0.008258522858492165


# Parte 3 - Selecionando os melhores hiperparâmetros pelo Having Grid Search


In [ ]:
from tensorflow.keras.layers import Dropout
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.experimental import enable_halving_search_cv
from sklearn.model_selection import HalvingGridSearchCV

In [ ]:
def build_classifier(optimizer,activation_fn):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = activation_fn, input_dim = 12))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = activation_fn))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = activation_fn))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

In [ ]:
classifier = KerasClassifier(build_fn = build_classifier)

parameters = {
    'batch_size': [10, 25, 32],
    'epochs': [50, 100],
    'optimizer': ['adam', 'rmsprop'],
    'activation_fn':["relu","sigmoid"]
}

halving_cv = HalvingGridSearchCV(estimator = classifier,
                                  param_grid = parameters,
                                  scoring="accuracy", 
                                  n_jobs=-1, 
                                  min_resources="exhaust", 
                                  factor=3,
                                  cv = 10)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  """Entry point for launching an IPython kernel.


In [ ]:
halving_cv = halving_cv.fit(X_train, y_train)

> Murilo Schiler