# REDES NEURAIS ARTIFICIAIS

[Aula 3 de Deep Learning](http://bit.ly/dn-unb03) da Engenharia de Software da UnB

# Parte 1 - Pré-processamento dos Dados

### Importar as libs

In [18]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [19]:
tf.__version__

'2.8.0'

### Importar o dataset

In [20]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head(10000)

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [21]:
dataset.Geography.value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [22]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


### Transformando os dados categóricos


In [23]:
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X[:, 2])

[0 0 0 ... 0 1 0]


In [24]:
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)

# Feature Scaling

In [26]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [27]:
np.shape(X_train)

(9000, 12)

In [28]:
X_train

array([[ 0.99445979, -0.5756396 , -0.57478426, ...,  0.64376017,
         0.97108454,  0.45151104],
       [ 0.99445979, -0.5756396 , -0.57478426, ...,  0.64376017,
        -1.02977646, -1.4892912 ],
       [ 0.99445979, -0.5756396 , -0.57478426, ...,  0.64376017,
         0.97108454,  0.26357605],
       ...,
       [ 0.99445979, -0.5756396 , -0.57478426, ...,  0.64376017,
        -1.02977646,  1.41226003],
       [-1.00557107, -0.5756396 ,  1.73978322, ...,  0.64376017,
         0.97108454,  0.84385822],
       [-1.00557107,  1.73719807, -0.57478426, ...,  0.64376017,
        -1.02977646,  0.32389292]])

---
# Parte 2 -Vamos construir uma ANN!


### Initializing the ANN

In [29]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [30]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [31]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [32]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

### Compiling the ANN

In [33]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

## Part 3 - Training the ANN

### Training the ANN on the Training set

In [34]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 1000)

Epoch 1/1000
282/282 [==============================] - 1s 1ms/step - loss: 0.5527 - accuracy: 0.7854
Epoch 2/1000
282/282 [==============================] - 0s 890us/step - loss: 0.4651 - accuracy: 0.7966
Epoch 3/1000
282/282 [==============================] - 0s 924us/step - loss: 0.4421 - accuracy: 0.7966
Epoch 4/1000
282/282 [==============================] - 0s 947us/step - loss: 0.4338 - accuracy: 0.7966
Epoch 5/1000
282/282 [==============================] - 0s 910us/step - loss: 0.4292 - accuracy: 0.7966
Epoch 6/1000
282/282 [==============================] - 0s 950us/step - loss: 0.4261 - accuracy: 0.7966
Epoch 7/1000
282/282 [==============================] - 0s 947us/step - loss: 0.4227 - accuracy: 0.8109
Epoch 8/1000
282/282 [==============================] - 0s 964us/step - loss: 0.4197 - accuracy: 0.8176
Epoch 9/1000
282/282 [==============================] - 0s 915us/step - loss: 0.4171 - accuracy: 0.8202
Epoch 10/1000
282/282 [==============================] - 0s 849us/

282/282 [==============================] - 1s 2ms/step - loss: 0.3270 - accuracy: 0.8650
Epoch 158/1000
282/282 [==============================] - 0s 2ms/step - loss: 0.3271 - accuracy: 0.8673
Epoch 159/1000
282/282 [==============================] - 0s 2ms/step - loss: 0.3272 - accuracy: 0.8649
Epoch 160/1000
282/282 [==============================] - 0s 2ms/step - loss: 0.3269 - accuracy: 0.8642
Epoch 161/1000
282/282 [==============================] - 0s 2ms/step - loss: 0.3267 - accuracy: 0.8653
Epoch 162/1000
282/282 [==============================] - 0s 2ms/step - loss: 0.3270 - accuracy: 0.8651
Epoch 163/1000
282/282 [==============================] - 0s 2ms/step - loss: 0.3265 - accuracy: 0.8658
Epoch 164/1000
282/282 [==============================] - 0s 2ms/step - loss: 0.3267 - accuracy: 0.8663
Epoch 165/1000
282/282 [==============================] - 0s 2ms/step - loss: 0.3270 - accuracy: 0.8650
Epoch 166/1000
282/282 [==============================] - 0s 2ms/step - loss: 0

282/282 [==============================] - 0s 1ms/step - loss: 0.3246 - accuracy: 0.8673
Epoch 314/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3245 - accuracy: 0.8679
Epoch 315/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3247 - accuracy: 0.8673
Epoch 316/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3243 - accuracy: 0.8673
Epoch 317/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3246 - accuracy: 0.8674
Epoch 318/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3240 - accuracy: 0.8678
Epoch 319/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3243 - accuracy: 0.8676
Epoch 320/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3246 - accuracy: 0.8672
Epoch 321/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3243 - accuracy: 0.8684
Epoch 322/1000
282/282 [==============================] - 0s 1ms/step - loss: 0

282/282 [==============================] - 0s 1ms/step - loss: 0.3232 - accuracy: 0.8678
Epoch 470/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3228 - accuracy: 0.8699
Epoch 471/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3231 - accuracy: 0.8678
Epoch 472/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3228 - accuracy: 0.8699
Epoch 473/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3224 - accuracy: 0.8691
Epoch 474/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3235 - accuracy: 0.8679
Epoch 475/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3222 - accuracy: 0.8676
Epoch 476/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3231 - accuracy: 0.8672
Epoch 477/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3229 - accuracy: 0.8693
Epoch 478/1000
282/282 [==============================] - 0s 1ms/step - loss: 0

282/282 [==============================] - 0s 1ms/step - loss: 0.3224 - accuracy: 0.8677
Epoch 626/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3231 - accuracy: 0.8684
Epoch 627/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3227 - accuracy: 0.8680
Epoch 628/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3226 - accuracy: 0.8687
Epoch 629/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3230 - accuracy: 0.8681
Epoch 630/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3224 - accuracy: 0.8677
Epoch 631/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3226 - accuracy: 0.8666
Epoch 632/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3221 - accuracy: 0.8697
Epoch 633/1000
282/282 [==============================] - 0s 998us/step - loss: 0.3224 - accuracy: 0.8671
Epoch 634/1000
282/282 [==============================] - 0s 992us/step - los

282/282 [==============================] - 0s 1ms/step - loss: 0.3225 - accuracy: 0.8687
Epoch 782/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3223 - accuracy: 0.8681
Epoch 783/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3225 - accuracy: 0.8682
Epoch 784/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3224 - accuracy: 0.8670
Epoch 785/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3226 - accuracy: 0.8682
Epoch 786/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3225 - accuracy: 0.8680
Epoch 787/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3227 - accuracy: 0.8680
Epoch 788/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3218 - accuracy: 0.8686
Epoch 789/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3221 - accuracy: 0.8674
Epoch 790/1000
282/282 [==============================] - 0s 1ms/step - loss: 0

282/282 [==============================] - 0s 1ms/step - loss: 0.3221 - accuracy: 0.8676
Epoch 938/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3222 - accuracy: 0.8676
Epoch 939/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3215 - accuracy: 0.8694
Epoch 940/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3223 - accuracy: 0.8673
Epoch 941/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3217 - accuracy: 0.8697
Epoch 942/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3215 - accuracy: 0.8693
Epoch 943/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3220 - accuracy: 0.8689
Epoch 944/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3217 - accuracy: 0.8679
Epoch 945/1000
282/282 [==============================] - 0s 1ms/step - loss: 0.3220 - accuracy: 0.8682
Epoch 946/1000
282/282 [==============================] - 0s 1ms/step - loss: 0

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [35]:
y_pred = ann.predict(X_test)
y_pred

array([[3.34084630e-01],
       [2.31786638e-01],
       [1.16909146e-01],
       [5.24522960e-02],
       [1.15927756e-02],
       [9.43228722e-01],
       [3.45535278e-02],
       [9.73690748e-02],
       [2.09283233e-01],
       [9.85568762e-01],
       [1.81260705e-02],
       [2.13773489e-01],
       [2.19393134e-01],
       [1.90835387e-01],
       [6.04608715e-01],
       [5.22825241e-01],
       [1.00652039e-01],
       [1.18314981e-01],
       [3.56560349e-02],
       [5.33494353e-02],
       [5.26710629e-01],
       [6.10026717e-03],
       [3.10670733e-02],
       [1.46815121e-01],
       [8.00493360e-03],
       [3.41005802e-01],
       [5.23588061e-02],
       [4.61427867e-02],
       [1.90413803e-01],
       [3.14028800e-01],
       [1.30364895e-02],
       [5.55848002e-01],
       [1.13582790e-01],
       [5.49128652e-03],
       [3.32041740e-01],
       [1.51241720e-02],
       [2.20574439e-02],
       [1.72875822e-02],
       [1.70580149e-02],
       [5.38774133e-02],


In [36]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [

# Criando uma Confusion Matrix

In [37]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[754  40]
 [104 102]]


# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)