In [157]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [158]:
tf.__version__

'2.4.1'

In [159]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [160]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


In [161]:
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]
[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [162]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [163]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [164]:
np.shape(X_train)

(8000, 12)

In [165]:
ann = tf.keras.models.Sequential()

In [166]:
ann.add(tf.keras.layers.Dense(units=6, activation='selu'))

In [167]:
ann.add(tf.keras.layers.Dense(units=6, activation='selu'))

In [168]:
ann.add(tf.keras.layers.Dense(units=6, activation='selu'))

In [169]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [170]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [171]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.6711 - accuracy: 0.6280
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4432 - accuracy: 0.7978
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4375 - accuracy: 0.8028
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4194 - accuracy: 0.8097
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3976 - accuracy: 0.8276
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3887 - accuracy: 0.8336
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3888 - accuracy: 0.8363
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3698 - accuracy: 0.8387
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3671 - accuracy: 0.8433
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3640 - accura

In [172]:
y_pred = ann.predict(X_test)
y_pred

array([[0.26445115],
       [0.26242304],
       [0.18225577],
       ...,
       [0.11231199],
       [0.23770583],
       [0.27999103]], dtype=float32)

In [173]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [174]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1506   89]
 [ 184  221]]
